### PR TITLE
Ref: Set num_ctx config for Ollama

### LINKED ISSUE #2924: [Bug]: CodeActAgent not executing code
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Hi, I'm new to opendevin. I am able to run opendevin locally (using ollama) and it seems working since I'm able to get response from my local model. However, as I try to reproduce the demo here: ,https://github.com/OpenDevin/OpenDevin/assets/38853559/f592a192-e86c-4f48-ad31-d69282d5f6ac I only get code response from model but it seems nothing gets executed. The model I'm running is lamma3:70b. Is it because of the model or I miss anything?

image

### Current OpenDevin version

```bash
0.8.0
```

### Installation and Configuration

```bash
docker run  -it     --pull=always    --add-host host.docker.internal:host-gateway     -e SANDBOX_USER_ID=$(id -u)     -e LLM_API_KEY="ollama"    -e LLM_BASE_URL="http://host.docker.internal:11434"    -e LLM_OLLAMA_BASE_URL="http://host.docker.internal:11434"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000 ghcr.io/opendevin/opendevin:latest
```

### Model and Agent

- Model: llama3:70b
- Agent: CodeActAgent

### Operating System

macos

### Reproduction Steps

_No response_

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SmartManoj**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
Fixes #2924. The default value of num_ctx is 2048 for ollama. Our prompt is greater than that (3909). So, the input is truncated.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**
- Set num_ctx 
- ~[model_info won't return max_input_tokens and max_output_tokens.](https://github.com/BerriAI/litellm/blob/385da04d72168706ac9a6dd705c35d587419bf8a/litellm/utils.py#L4668)~ https://github.com/BerriAI/litellm/issues/4711

**Other references**
https://github.com/ollama/ollama/issues/1005

### CODE REVIEW

**Comment by tobitege** [comment]
I think this should be implemented in a broader way and not just for Ollama.
litellm already keeps an extensive list of models and their config values, like `max_tokens`, `max_input_tokens` and `max_output_tokens`.
One could also use methods like `max_tokens = get_max_tokens(model)`.
Example from their json file:
```json
    "ollama/llama3:70b": {
        "max_tokens": 8192,
        "max_input_tokens": 8192,
        "max_output_tokens": 8192,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "ollama",
        "mode": "chat"
    },
```
It would require a little more time and effort, but would cover a lot more cases in general, if you'd have the time?

**Comment by SmartManoj** [comment]
> * model_info won't return max_input_tokens and max_output_tokens.



> Example from their json file:

Could you please link the json file?

**Comment by tobitege** [comment]
Their json with the model configs:
https://github.com/BerriAI/litellm/blob/2bf1f06a0eff18d41066aacc635fb06003f8cc91/model_prices_and_context_window.json

**Comment by BradKML** [comment]
@tobitege Think LiteLLM gets all their info directly from Ollama, and there are other models that have support for super long context windows.

**Comment by rbren** [comment]
We're doing some cleanup of PRs, and are going to close this one for now.

**Comment by nikhil-swamix** [comment]
@rben do inform if cleanup is done, please make every option configurable via flag, and a json backed setting! this has realworld implications and people are complaining me that ollama hosted model is performing worse, compared to same llama3.2, as context is murdered!

**Comment by rbren** [comment]
@nikhil-swamix feel free to open up a new PR if there's a change you'd like to make here!

**Comment by nikhil-swamix** [comment]
sure, let me run some agents over the source to identify the dependence path , my base approach for storing anything not data heavy,  is this class in `pip install swamix` then you may inspect swamix.classes which will have
```py
import json
import os


class DictFile:
    """
    # Usage
    ```
    df = DictFile("mydict.json") # Use it like a regular dictionary
    df["key1"] = "value1"
    df["key2"] = [1, 2, 3]

    print(df["key1"])  # Outputs: value1
    print(len(df))  # Outputs: 2, The changes are automatically saved to "mydict.json"

    # You can also use other dictionary methods
    df.update({"key3": "value3", "key4": {"nested": "dict"}})
    print(df.keys())  # Outputs: dict_keys(['key1', 'key2', 'key3', 'key4'])

    # Clear the dictionary
    # df.clear()
    # The file "mydict.json" will now contain an empty JSON object: {}
    ```
    """

    def __init__(self, filename):
        self.filename = filename
        self.data = {}
        self.load()

    def load(self):
        if os.path.exists(self.filename):
            with open(self.filename, 'r') as f:
                self.data = json.load(f)

    def save(self):
        with open(self.filename, 'w') as f:
            json.dump(self.data, f, indent="\t")

    def __getitem__(self, key):
        return self.data[key]

    def __setitem__(self, key, value):
        self.data[key] = value
        self.save()

    def __delitem__(self, key):
        del self.data[key]
        self.save()

    def __contains__(self, key):
        return key in self.data

    def __len__(self):
        return len(self.data)

    def __iter__(self):
        return iter(self.data)

    def keys(self):
        return self.data.keys()

    def values(self):
        return self.data.values()

    def items(self):
        return self.data.items()

    def get(self, key, default=None):
        return self.data.get(key, default)

    def clear(self):
        self.data.clear()
        self.save()

    def update(self, *args, **kwargs):
        self.data.update(*args, **kwargs)
        self.save()

    def pop(self, key, default=None):
        value = self.data.pop(key, default)
        self.save()
        return value

    def popitem(self):
        item = self.data.popitem()
        self.save()
        return item

    def setdefault(self, key, default=None):
        if key not in self.data:
            self.data[key] = default
            self.save()
        return self.data[key]

    def __str__(self):
        return str(self.data)

    def __repr__(self):
        return f"DictFile({self.filename})"

```
___
# reason
This approach has worked wonders when buiding something very quickly or has `singleton` datas, and to store state between runs of any script/server. a persistent store for tool calling, and mimics a map/dict but offline. if there is any specific incompatibility of this with GO-ollama ecosystem, let me know, 
not a "go" expert but will give it a go!

**Comment by nikhil-swamix** [comment]
please pardon my extra comments on ollama, i was confused that this issue was linked. haha.
probably AHA and Cline are the best tools atm!

**Pull request closed without merging**
