### PR TITLE
Fix Mac OS CI - usernet unable to resolve IP for SSH forwarding

### PR DESCRIPTION
**Pull request by SmartManoj**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
[Action link](https://github.com/OpenDevin/OpenDevin/actions/runs/9607736887/job/26499400916?pr=2539)

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**
Enabled `--network-address` and used the development version of Colima

**Other references**
[docker not listening on port on OSX - colima](https://stackoverflow.com/a/72810370)
https://github.com/abiosoft/colima/issues/458#issuecomment-2171006045

### CODE REVIEW

**Review by iFurySt — APPROVED** [review]

**Comment by iFurySt** [comment]
Thanks, I hope this can completely resolve the issue❤️

**Comment by SmartManoj** [comment]
> hope

[Why is hope a dangerous thing?](https://medium.com/@daredevilashish/why-is-a-hope-dangerous-thing-8b85fc9fef94)🤣

**Comment by tobitege** [comment]
@SmartManoj I think colima still needs more tweaking, even with this patch.
Maybe we have to forcefully first uninstall colima and install it fresh?
It already waits for 3 minutes for the ssh socket file and still fails, so I doubt it is a timeout issue itself.

**Comment by SmartManoj** [comment]
> Maybe we have to forcefully first uninstall colima and install it fresh?

[GitHub provides Ubuntu Linux, Microsoft Windows, and macOS runners to run your workflows; each workflow run executes in a fresh, newly-provisioned virtual machine.](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions?learn=getting_started&learnProduct=actions#:~:text=GitHub%20provides%20Ubuntu%20Linux%2C%20Microsoft%20Windows%2C%20and%20macOS%20runners%20to%20run%20your%20workflows%3B%20each%20workflow%20run%20executes%20in%20a%20fresh%2C%20newly%2Dprovisioned%20virtual%20machine.)

**Comment by tobitege** [comment]
Please take a look closer, from a current, successful workflow:

https://github.com/OpenDevin/OpenDevin/actions/runs/9610927108/job/26508440819

grafik

**Comment by SmartManoj** [comment]
> Maybe we have to forcefully first uninstall colima and install it fresh?

That's call reinstall. Not upgrading.

https://github.com/actions/runner-images/issues/6216#issuecomment-1274318785

**Comment by tobitege** [comment]
Who said upgrading?

**Comment by SmartManoj** [comment]
Edited.

**Pull request merged**
