### PR TITLE
feat: add workflow to ghcr

### PR DESCRIPTION
**Pull request by iFurySt**
@rbren @xingyaoww once again 🤪,history message is here #121 #171

### CODE REVIEW

**Review by rbren — APPROVED** [review]

**Comment by xingyaoww** [comment]
LGTM and merged! Thank you for your contribution!

**Comment by rbren** [comment]
@iFurySt looks like this action is failing

**Comment by xingyaoww** [comment]
oh wait - can you check the log? https://github.com/OpenDevin/OpenDevin/actions/runs/8454098805/job/23158343441

**Comment by iFurySt** [comment]
let me look at this

**Pull request merged**
