### PR TITLE
Create install_opendevin.sh

### PR DESCRIPTION
**Pull request by skynet-bit**
Shell script to automate the installation process

### CODE REVIEW

**Comment by skynet-bit** [comment]
Remember to replace sk-... with your actual OpenAI API key. Also, note that gnome-terminal is specific to GNOME desktop environments. If you’re using a different desktop environment, you’ll need to replace gnome-terminal with the appropriate command for your terminal emulator. For example, for KDE’s Konsole, it would be konsole -e, and for XFCE’s Terminal, it would be xfce4-terminal -e.

To run the script, save it to a file, for example install_opendevin.sh, and make it executable with the following command:
`chmod +x install_opendevin.sh`
Then you can execute the script using:
`sudo ./install_opendevin.sh`

**Comment by s1moe2** [comment]
I suggest reading the key from an environment variable instead of having to hardcode it into a script that is not even added to .gitignore

**Comment by Kurtisone** [comment]
It only works on Debian-based distributions, you should mention it.

Great work !

**Comment by rbren** [comment]
Given that we have a Makefile now, I don't think we want to maintain this one. Nice to have for posterity though! Thanks for pushing it.

**Comment by skynet-bit** [comment]
**Thanks for the feedback @s1moe2  @Kurtisone  @rbren **  

> To be honest, this is was my first contribution to a open source  project, and it was accidental one, the target branch was supposed to be my main branch of my fork

> Anyways makefile is super helpful

**Pull request closed without merging**
