### PR TITLE
tweaks to chat message CSS stylings for lists

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Numbered lists in chat messages were missing the numbers.

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Tweak some CSS.

Follow up to #3273

### CODE REVIEW

**Review by tofarr — APPROVED** [review]
LGTM! Was there a rule that applied a different list-style-type to ol elements?

**Comment by tobitege** [comment]
> LGTM! Was there a rule that applied a different list-style-type to ol elements?

Idk, the digits just didn't appear for me, like in this example:
grafik

**Comment by amanape** [comment]
The `Markdown` component from `react-markdown` can accept custom component definitions to use when rendering markdown content:

https://github.com/OpenDevin/OpenDevin/blob/733bf2b38cd7d29f5d87c1cef49d342298217bb3/frontend/src/components/chat/ChatMessage.tsx#L80-L82

In the case of an `ol`, Tailwind CSS resets the styles which could be reverted (something like this):

```css
.markdown > ol {
  all: revert;
}
```

To apply custom styles like margin, you can pass a custom component:

```tsx
<Markdown
  components={{
    code,
    ul: ({ children }) => <ul className="list-disc ml-5">{children}</ul>,
  }}
>
  {message.content}
</Markdown>
```

You can read more [here](https://github.com/remarkjs/react-markdown?tab=readme-ov-file#components)

**Comment by tobitege** [comment]
Thanks for the detailed explanations!
I hope to get to do this in a follow up PR in the coming days (unless someone else does it first).

**Pull request merged**
