### PR TITLE
feat: frontend overhaul: sidebar, light/dark theme

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Initial draft of an overhauled frontend/UI.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

- Adds a left-hand, exandable/collapsabe sidebar for e.g. social links, but also features (tbd)
- Settings in a bigger, cleaner display
- Added a Light and Dark Theme toggle
- Configuration and mute button moved into sidebar border
- Default color theme slightly changed
- Fixed beep not get initialized and not checking for cookie value correctly

## Session modal:
grafik
## Dark Themed frontend:
grafik
## Expanded sidebar:
grafik
## Configuration page:
grafik
## Light Theme:
grafik

Even though this PR is a draft, I'd like to invite anyone to try out this branch and provide feedback.

### CODE REVIEW

**Comment by PierrunoYT** [comment]
Looks good but I would choose another color for the light theme.

**Comment by tobitege** [comment]
> Looks good but I would choose another color for the light theme.

It is definitely not set in stone. Right now I'm struggling more with getting all the components "behave" in a consistent way when switching themes. 
Our design specialists will have the last word on it.

**Comment by iFurySt** [comment]
This is a great PR. But I have some concerns about the uniform style. Some details need to be adjusted. 😄

**Comment by enyst** [comment]
Love the settings page! It looks cool... With all that space I'm starting to wonder if maybe we can include some pre-defined configurations sometime, or some filter, maybe per provider, rather than model 😸

**Comment by tobitege** [comment]
> Love the settings page! It looks cool... With all that space I'm starting to wonder if maybe we can include some pre-defined configurations sometime, or some filter, maybe per provider, rather than model 😸

Exactly, no longer using a modal and making it full-client size gives us room to expand into more options.

**Comment by tobitege** [comment]
> This is a great PR. But I have some concerns about the uniform style. Some details need to be adjusted. 😄

Oh, yes, there're tons of those I need to fix. All these different TailwindCSS classes.
That's why I'm considering to use daisyUI for theming+controls:
https://daisyui.com/docs/themes/

**Comment by mamoodi** [comment]
@tobitege I'm wondering since this will change significantly or be re-done based on my understanding from you, would it make sense to close this PR for now and reopen when it's closer to being ready?

**Comment by tobitege** [comment]
> @tobitege I'm wondering since this will change significantly or be re-done based on my understanding from you, would it make sense to close this PR for now and reopen when it's closer to being ready?

Yes, you're right. This will take more time and discussions on how to proceed, in general.

**Pull request closed without merging**
