### PR TITLE
PERSIST_SANDBOX - Just for testing

### LINKED ISSUE #2176: Persistent docker doesn't work with AgentSkills in test
@SmartManoj could you please take a look at this?

image

Persistent docker thing doesn't seem to work well with agent skills. Repro command:

```bash
ONLY_TEST_NAME=test_edits TEST_ONLY=true ONLY_TEST_AGENT=CodeActAgent ./tests/integration/regenerate.sh
```

(with `persist_sandbox = true`)

I think https://github.com/OpenDevin/OpenDevin/pull/1998 causes a regression.

The test passed because you set `persist_sandbox = false` in CI.

If we make this persistence thing by default ON, we shall probably also turn it on in CI?

_Originally posted by @li-boxuan in https://github.com/OpenDevin/OpenDevin/issues/2139#issuecomment-2138723188_

### PR DESCRIPTION
**Pull request by SmartManoj**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
Fixes #2176 

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**
Disabled temp directory creation and emptied workspace after each test.

### CODE REVIEW

**Comment by neubig** [comment]
Just noting that we might remove PERSIST_SANDBOX altogether, based on discussion on slack: https://opendevin.slack.com/archives/C078L0FUGUX/p1718912182528839?thread_ts=1718893390.852169&cid=C078L0FUGUX

**Comment by mamoodi** [comment]
@SmartManoj This can be closed correct?

**Comment by neubig** [comment]
Closing since there was no response to @mamoodi 's comment to the contrary.

**Comment by SmartManoj** [comment]
I have already discussed this with @mamoodi in Slack and have moved the discussion in the #devops channel to [a new thread](https://opendevin.slack.com/archives/C078L0FUGUX/p1719984775838819) as it was a sub-topic in that.


https://github.com/OpenDevin/OpenDevin/pull/2139#issuecomment-2138737229 @li-boxuan all tests were passed.

**Pull request closed without merging**
