### PR TITLE
style: Update agent_controller.py to clean log

### PR DESCRIPTION
**Pull request by assertion**
clean log :

image

@li-boxuan

### CODE REVIEW

**Review by iFurySt — APPROVED** [review]

**Comment by yufansong** [comment]
Why remove it? If agent is not running and get blocked, I think it is reasonable to log.

**Comment by assertion** [comment]
> Why remove it? If agent is not running and get blocked, I think it is reasonable to log.

If agent initialized, but user hasn't input anything yet, it just keeps logging `17:18:30 - opendevin:INFO: agent_controller.py:231 - [Agent Controller dcf49ad2-2623-4219-9f6c-f9ce0ebf7b21] waiting for agent to run... `

@yufansong

**Comment by tobitege** [comment]
If it's logging every second, I'd agree it's just logspam.
How about logging just *once* at that location OR only once per minute?

**Review by li-boxuan — APPROVED** [review]
Good catch, I didn't expect this log to become a spam when user hasn't given any task...  Let's get this merged before it spams more people.

The fact that this keeps logging makes me feel we shouldn't use this polling approach. If we use event-driven approach, this problem would likely go away...

**Pull request merged**
