### PR TITLE
Refactor integration testing CI, add optional Mac tests, and mark a few agents as deprecated

### PR DESCRIPTION
**Pull request by li-boxuan**
This PR reorganizes integration test CI to reduce the number of GitHub Checks. It leverages `regenerate.sh` to avoid inconsistency between `regenerate.sh` and `run-integration-tests.yml`. This PR also adds MacOS platform to integration testing, but only runs it against ssh sandbox.

Motivation of adding tests for MacOS: a month ago, OpenDevin broke on MacOS once: #887. Having integration tests could prevent this from happening again. Note: MacOS integration test suite is optional (non-blocking) due to its slowness.

This PR also marks SWE-Agent as deprecated and removed it from integration testing. They can still be used normally, but eventually we might remove them if we don't see active development and/or usage. Similar for PlannerAgent and MonologueAgent, but at the moment we only remove some tests and retain a basic test to ensure their functionalities don't break.

Finally, this PR also removes excessive logging during the test run.

### CODE REVIEW

**Comment by enyst** [comment]
> UPDATE: I cannot get it work on 3.12. Switching back to 3.11.

Aww. May I ask, what was the issue on 3.12, was it some chroma dependency?

**Comment by rbren** [comment]
Man this is gonna blow out the (already quite large) list of CI checks. I wonder if there's a way to tell github not to show every test in the matrix...

**Comment by li-boxuan** [comment]
> Man this is gonna blow out the (already quite large) list of CI checks. I wonder if there's a way to tell github not to show every test in the matrix...

This PR itself only adds one CI check, but I can merge a few existing CI checks into a single one. Otherwise, as the number of agents grows, the CI list would grow longer and longer.

**Comment by li-boxuan** [comment]
> Aww. May I ask, what was the issue on 3.12, was it some chroma dependency?

@enyst Yep, it seems so: https://github.com/OpenDevin/OpenDevin/actions/runs/9141617963/job/25136227953#step:5:245 do you have any idea on that?

**Comment by li-boxuan** [comment]
Okay now we only have 4 CI checks for integration testing:
- linux + ssh sandbox
- linux + local sandbox
- linux + exec sandbox
- mac + ssh sandbox

**Comment by li-boxuan** [comment]
Sad :( somehow codecov is not able to combine all the reports anymore... checking...

**Review by Th3313 — APPROVED** [review]

**Comment by li-boxuan** [comment]
Coverage dropped by 1.22% because test coverage for SWE-agent was higher than average project coverage. Now that we don't count that package into coverage thus the drop.

**Pull request merged**
