### PR TITLE
chore: use pnpm to manage frontend deps

### PR DESCRIPTION
**Pull request by 94mashiro**
- Use Corepack and the `packageManager` field in `package.json` to specify the package manager and its version.
  - This approach helps avoid conflicts caused by different `npm` versions generating different lockfiles.
- Adopt `pnpm` for managing frontend dependencies because:
  - `pnpm` is more efficient in terms of disk space usage, and installs faster.
    - image

  - It maintains a flat `node_modules` file structure.
  - Many new and popular frontend projects now use `pnpm`, such as:
    - [Vue.js](https://github.com/vuejs/vue)
    - [Vite](https://github.com/vitejs/vite)
  - For more details on `pnpm` versus `npm`, see: [pnpm vs npm](https://pnpm.io/pnpm-vs-npm).
- Automatically detect frontend project dependencies managed by `npm`, delete the `node_modules` directory, and rebuild it using `pnpm`.
- If you're using Volta to manage Node.js versions, the `volta` field in `package.json` can be used to specify the desired Node version (18.20.1 is the latest version of Node 18 (LTS), and it's stable).

### CODE REVIEW

**Comment by xcodebuild** [comment]
Works well in `node 18`, should we consider adding a check to provide a more explicit prompt?

**Comment by 94mashiro** [comment]
> Works well in `node 18`, should we consider adding a check to provide a more explicit prompt?

That's a good idea. I've added a Node script to detect the current environment's Node.js version, or it will abort the `make build`.
I've also replaced the Node.js version number in the `Readme` to support corepack.

**Comment by yimothysu** [comment]
LGTM. @94mashiro can you take a look at the CI errors?

**Comment by 94mashiro** [comment]
> LGTM. @94mashiro can you take a look at the CI errors?

The issue has been fixed, the problem was due to npm's lockfile being out of date, it has now been replaced with pnpm, you can re-run the CI to verify.

**Comment by PierrunoYT** [comment]
> * Use Corepack and the `packageManager` field in `package.json` to specify the package manager and its version.
>       
>       * This approach helps avoid conflicts caused by different `npm` versions generating different lockfiles.
> 
>     * Adopt `pnpm` for managing frontend dependencies because:
>       
>       * `pnpm` is more efficient in terms of disk space usage, and installs faster.
>         
>         * image
>       * It maintains a flat `node_modules` file structure.
>       * Many new and popular frontend projects now use `pnpm`, such as:
>         
>         * [Vue.js](https://github.com/vuejs/vue)
>         * [Vite](https://github.com/vitejs/vite)
>       * For more details on `pnpm` versus `npm`, see: [pnpm vs npm](https://pnpm.io/pnpm-vs-npm).
> 
>     * Automatically detect frontend project dependencies managed by `npm`, delete the `node_modules` directory, and rebuild it using `pnpm`.
> 
>     * If you're using Volta to manage Node.js versions, the `volta` field in `package.json` can be used to specify the desired Node version (18.20.1 is the latest version of Node 18 (LTS), and it's stable).

Installing frontend dependencies with npm...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/eslint-plugin@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/parser@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/scope-manager@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/type-utils@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/utils@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/visitor-keys@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/types@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/typescript-estree@7.5.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '10.5.1' }
npm WARN EBADENGINE }

**Pull request merged**
