### PR TITLE
Remove pyproject workflow and cleanup stale workflow

### PR DESCRIPTION
**Pull request by mamoodi**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

No it does not fix any open issues.

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

* The update-pyproject-version.yml was not working properly and always failing. Right now the update of this file is done manually as part of the release process. Going to remove this for now and revisit the whole thing once it becomes more necessary
* Cleaned up the stale workflow. We do not have an "age-out" label so parts of it were unnecessary

I'm getting familiar with the workflows in general and just doing some cleanup as initial step.

---
**Other references**

### CODE REVIEW

**Comment by tobitege** [comment]
I'm not sure if removal is the best way:
- a workflow (like update-pyproject-version.yml) can be disabled in the Actions tab globally
- even if we don't have the age-out label (yet), removing the code for it will require to re-develop it in case it'll become usefull

This isn't a review, so just mentioning above that if we remove these snippets, it's probably more effort to get them back instead of leaving them in place and/or disable. 🤔

**Comment by mamoodi** [comment]
> I'm not sure if removal is the best way:
> 
> * a workflow (like update-pyproject-version.yml) can be disabled in the Actions tab globally
> * even if we don't have the age-out label (yet), removing the code for it will require to re-develop it in case it'll become usefull
> 
> This isn't a review, so just mentioning above that if we remove these snippets, it's probably more effort to get them back instead of leaving them in place and/or disable. 🤔

The age-out label can be added but there's just not enough of a use-case for it. It's the same thing as the regular flow but just more aggressively. If something needs to be aggressively closed, perhaps a comment and closing the issue or PR is more useful. Those can be reopened anyways if the user comes back and comments.

I can definitely be persuaded regarding the pyproject workflow and just disabling it. I'm just not a fan of having code there that doesn't run or always fails. I'm going to be looking at all the workflows in the coming days/weeks so will likely change that up completely anyways.

**Comment by tobitege** [comment]
Fair enough @mamoodi - I'll leave the review to e.g. @xingyaoww or @li-boxuan

**Review by xingyaoww — APPROVED** [review]
LGTM!

**Pull request merged**
