### PR TITLE
Add specific error to is_stuck check, adjust check down to 3 for identical act/obs

### PR DESCRIPTION
**Pull request by enyst**
The diff for this PR is this: https://github.com/OpenDevin/OpenDevin/compare/enyst/memories-condenser...enyst/memories-is-stuck

(This PR is made on top of the rewrite of the `is_stuck` check in https://github.com/OpenDevin/OpenDevin/pull/2021. The entire check had to be rewritten there since events are no longer available in pairs. So at the moment it's difficult to read the diff directly. Will update when we merge or backport this if we don't.)

- ~~reduce the identical (action, obs) needed to 3 from 4~~ This was backported to `main`.
- add the syntax error as such, discussed here: https://github.com/OpenDevin/OpenDevin/issues/2238#issuecomment-2156659943 (checks for that specific error 4 times in a row)

Please note:
The syntax error check is so specific. I'm looking into other ways too. But what seems a little more risky is that the user works with python code, for example with... this code about syntax errors or its tests. Thus the agent can output the string "syntax error" as part of tests or, I don't know, whatever else the user wants to do. I think in this case the risk is low to have it happen 4 times in a row, all from running code, not messages or other actions, and it's mitigated further by a check that it's always close to the end of the observation.

### CODE REVIEW

**Comment by neubig** [comment]
Hi @enyst , it looks like there are lots of conflicts here. I'm happy to review once the conflicts are resolved, but I'll assign it to you for now.

**Comment by enyst** [comment]
@neubig thanks for checking! Conflicts are fixed. The funny thing was, most conflicts were due to the fact that I backported to `main` the first half of this PR. (I saw meanwhile another case when it mattered, so I rewrote it in `main` style.) Since this particular code was practically completely rewritten on the memories PR (which this one is based on), diff-merge really hated it.

Done, only the syntax error issue remains here, and updated the link in the OP to the "real" diff of this PR.

**Comment by neubig** [comment]
Hey @enyst , since the main PR #2021 is a draft at the moment, I might set this one to draft and re-visit it later if that's OK?

**Comment by enyst** [comment]
Eventually, this PR was merged part into `main`, part into the 2021 branch, so I'm going to close it.

**Pull request closed without merging**
