### PR TITLE
Bash terminal emulator

### PR DESCRIPTION
**Pull request by geohotstan**
Read discussion about needing a Bash Terminal.
I'm not too sure we're going with a python backend to chain everything together but here's a draft of a working bash terminal emulator in python.

It supports:
- running bash commands and returning the result as a python variable 😎 
- maintaining state even after bash commands like `cd ..`
- history, where it prints out the entire bash session log

I'm not sure if this was what was meant by "a bash terminal" but heh
I haven't tested more complicated commands
this is still WIP. Just sharing ideas.
Let me know if this is kinda the right approach? :s 

maybe extracting

\```bash
...
\```

returned by agent, then run it using this and taking the output and passing it back to the agent?

The history can also be sent to the UI to display what is being executed.

### CODE REVIEW

**Review by AbhisekOmkar — COMMENTED** [review]
Can you please share the ss

**Comment by z-zeechung** [comment]
i think we should work out a unified interface for bash module, to allow different bash modules to co-exist, some for shell, some for docker, some for vm, some for ssh, some for embedded devices...

**Comment by geohotstan** [comment]
> Can you please share the ss

what's ss?

**Comment by AbhisekOmkar** [comment]
can you share the screenshots @geohotstan

**Comment by geohotstan** [comment]
> can you share the screenshots @geohotstan

screenshots of what?

**Comment by rbren** [comment]
@geohotstan this is neat!

I have a PR up that implements a basic control loop, but it's missing some of these features.

https://github.com/OpenDevin/OpenDevin/pull/35

Specifically directory tracking is a pretty urgent need--right now my prompt just tells it to always assume the same working directory.

But more urgently, I need the ability to run a command in the background, and kill that command. E.g. if it's building a server in node, it needs to be able to run `node server.js`, then while that command is running, execute `curl localhost:3000`. Is your implementation able to handle that?

**Comment by rbren** [comment]
Another consideration: we'll _also_ need a way to get stdout/stderr from that background process, and feed it back to the LLM

**Comment by geohotstan** [comment]
> Another consideration: we'll _also_ need a way to get stdout/stderr from that background process, and feed it back to the LLM

I think the stdout and stderr is already being passed into the master file descriptor for reading when `_read_output()` is called, if I'm not mistaken...

> But more urgently, I need the ability to run a command in the background, and kill that command. E.g. if it's building a server in node, it needs to be able to run node server.js, then while that command is running, execute curl localhost:3000. Is your implementation able to handle that?

Currently, I don't think so :c
I think it should be possible for that to work.
I'll give it a try :D

**Comment by rbren** [comment]
@geohotstan I've hacked this behavior into my agent, but would love a cleaner approach.

https://github.com/rbren/OpenDevin/blob/main/agent/lib/actions/run.py

https://github.com/rbren/OpenDevin/blob/main/agent/lib/actions/kill.py

https://github.com/rbren/OpenDevin/blob/72a4fe2163f2c5f97c76030b3385189258b42ffd/agent/lib/agent.py#L68

The LLM can add a `background: True` arg to any `run` command. The agent keeps a list of background commands. Every time we send a new prompt to the agent, we pull any new logs from those commands and add them to the context. The agent is allowed to kill the commands at any point (e.g. to restart a server)

**Comment by rbren** [comment]
[In Discord](https://discord.com/channels/1217291564502483015/1218178381527519383/1219119980684115968) @markokraemer suggested keeping several running terminal sessions, which the agent would have access to (rather than having one preferred shell, plus some auxiliary background shells). This might be a more principled approach. But I also worry it adds some overhead to the agent (it needs to decide where to run each command, keep track of cwd for each shell, etc)

**Comment by geohotstan** [comment]
I played around with your fork a bit :D 
The only thing is it currently doesn't track "state"
For example `cd ..` is currently an one-off command.
Though I'm really not sure how important "state" is to LLM shell usage/feedback loop.
Like if a LLM suggests a chain of 5 shell commands to execute (will it even do that?) and command 3 runs into an error, the current solution without `pty` would be to save position of error, insert llm's suggested fix at pos, then rerun them with the fix? (I'm not too familiar with this hehe)

The `background: True` implementation is really neat though.
Also I don't think I have access to that discord :/
I only have access to the slack, which is where I read about the discussion of needing a bash terminal.

**Comment by rbren** [comment]
Here's a discord invite: https://discord.gg/Vjeb8mB5

I think it makes sense to execute one command at a time, so the LLM gets feedback before proceeding. (Sometimes it does use `&&` to run two related commands though, e.g. `apt update && apt install npm -y`)

That said, if the LLM can issue several commands in one go, it reduces the number of round trips, keeping cost down and moving things along faster. So the "rewind" could be a good option to have.

Tracking cwd is probably the biggest shortcoming of my solution right now. But the LLM seems to do just fine so long as it's told that the root dir is _always_ the working dir.

**Comment by geohotstan** [comment]
There are a few implementations better than this now, gonna close this.
Godspeed! gogogo :D

**Pull request closed without merging**
