### PR TITLE
feat: Add Python 3.11 to the sandbox

### LINKED ISSUE #2656: Some way to manage the sandbox environment (e.g. to change python version?)
**What problem or use case are you trying to solve?**

My project uses python 3.11. I wanted to try and make changes, run tests etc. with OpenDevin  but it fails because its python version is 3.10 (it even tried, and failed, to install 3.11 on its own)

**Describe the UX of the solution you'd like**

Problem is that it's set at the docker container level, so I'm not sure how this can be done elegantly without requiring users to clone the repo locally and do lots of manual work...?

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by SmartManoj**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Fixes #2656, Helps #2705

### CODE REVIEW

**Comment by xingyaoww** [comment]
Looks like the build failed?
 https://github.com/OpenDevin/OpenDevin/actions/runs/9695307158/job/26774549296?pr=2658#step:6:50

**Review by neubig — COMMENTED** [review]
Quick question: how much does this increase the size of the sandbox docker? If it's negligible I think this is probably OK. If it's a lot we might need to think about it.

**Comment by SmartManoj** [comment]
I haven't checked the exact increase in size. It would be advisable to evaluate this, especially since many users prefer using the latest stable version of Python.

**Comment by Shimada666** [comment]
Please note, we are not using the Python 3.10 deb package. We are currently using Miniforge to install the Python environment.

**Comment by Shimada666** [comment]
If it's to solve #2656, it's actually not necessary. Users can specify `custom_container_image` to use any image they want, such as python:3.11.

**Comment by SmartManoj** [comment]
Most users will use Python 3.11, and we are also using it. Forcing users to specify custom_container_image to use the latest stable version is not ideal. It would be better to support Python 3.11 directly.

**Comment by Shimada666** [comment]
I don't oppose upgrading the default sandbox image's Python interpreter. But this should be unrelated to solving this issue, or you could say it's not necessary. I have a few questions:

1. How do you determine that most users use Python 3.11?
2. Users have diverse needs. Some need Python 3.11, some need 3.12, and some need Python 3.8. You said specifying custom_container_image is not ideal. So, what do you plan to do instead? In comparison, using a custom_container_image is a more versatile solution.

What I'm saying is, upgrading the default Python interpreter in the sandbox image isn't a bad thing, but users' custom needs should be addressed through custom sandbox images. You can't meet all users' needs with a general image.

**Comment by SmartManoj** [comment]
> 1. How do you determine that most users use Python 3.11?


I mentioned "Most users **will** use Python 3.11" in the future tense;  Because it is [the latest stable version.](https://devguide.python.org/versions/)

---

1. Why are we not supporting 3.10?
https://github.com/OpenDevin/OpenDevin/blob/0973e31f000ea80c522ded9e43d01a16ab5ae0cf/pyproject.toml#L11

2. While I agree that using custom_container_image offers versatility, the goal is to simplify the default setup for the majority who will benefit from having Python 3.11 readily available. For those with specific needs, custom images remain an option.

3. I agree that a single general image can't meet all needs. However, upgrading to Python 3.11 in the default image can streamline the process for most users, reducing the need for custom configurations. Those with unique requirements can still leverage custom sandbox images to meet their specific needs.

**Comment by tobitege** [comment]
> I don't oppose upgrading the default sandbox image's Python interpreter. But this should be unrelated to solving this issue, or you could say it's not necessary. I have a few questions:
> 
>     1. How do you determine that most users use Python 3.11?
> 
>     2. Users have diverse needs. Some need Python 3.11, some need 3.12, and some need Python 3.8. You said specifying custom_container_image is not ideal. So, what do you plan to do instead? In comparison, using a custom_container_image is a more versatile solution.
> 
> 
> What I'm saying is, upgrading the default Python interpreter in the sandbox image isn't a bad thing, but users' custom needs should be addressed through custom sandbox images. You can't meet all users' needs with a general image.

Our workflows (tests) also run explicitly on 3.11, so I wouldn't mind to have 3.11 the default.

**Comment by Shimada666** [comment]
@tobitege 
Hi tobi. The current sandbox environment has two Python environments: the user-facing Python environment at `/usr/bin/python` and the sandbox environment used by opendevin at `/opendevin/miniforge3/bin/python`. Both are currently Python 3.10. If the goal is to align the Python versions used in opendevin development and the actual environment, we should upgrade `/opendevin/miniforge3/bin/python` to 3.11. 😄

I don't mind upgrading to 3.11 as long as it doesn't significantly increase the image size. Upgrading the Python environment is fine. I'm just saying that if the purpose is to resolve this kind of problem., a better approach would be to use a custom sandbox image directly. Manoj and I should both agree on this. The purpose of this PR shouldn't be to solve #2656 ; it just happens to work on it.

**Comment by SmartManoj** [comment]
`python3` will still point to v3.10
It just adds `python3.11`

**Comment by tobitege** [comment]
I think there needs to be input from @neubig and @xingyaoww and the team, what the "default" Python version should be.
As far as I can tell, the workflows run tests explicitly with 3.11.
- Would be our minimum requirement 3.10 or 3.11?
- Should we extend the workflows to test against both 3.10 and 3.11?
- Do we need or want 2 versions at the same time?
Just throwing the questions out there. 😬

**Comment by xingyaoww** [comment]
> python3 will still point to v3.10

I think if we really need to upgrade to python 3.11, i'd root for pointing `python3` to `3.11` as well - so that we only have ONE version of Python in the sandbox as far as user knows?

**Comment by xingyaoww** [comment]
^^
I added an issue https://github.com/OpenDevin/OpenDevin/issues/2845 to track this!

**Comment by neubig** [comment]
Sounds good! I agree with @xingyaoww , so I think we can close this for now and look for an alternative solution.

**Pull request closed without merging**
