### PR TITLE
feat: chat interface autoscroll

### LINKED ISSUE #704: Frontend - Autoscroll toggle button next to setting cog
**What problem or use case are you trying to solve?**
Users many times would need to check up the previous messages while the assistant is typing, but the autoscroll will keep navigating to the latest chat position. (only when acitve messages is typed out by assistant or when new messages are sent by user)

**Describe the UX of the solution you'd like**
Provide a autoscroll check box next the settings cog.

**Do you have thoughts on the technical implementation?**

- create a component for Autoscroll with checkbox and place it next to cog
- Make the checkbox and text clickable (onclick on the div would be nice , would provide good click surface area)
- Add new state to chatslice and tooggling action
- add new action to chatting service
- import the new state and use it inside the useEffect which triggers messageScroll function 
- If this state is false then return  ie. (!autoscrollAcitve) return on the first line within the useEffect.

### PR DESCRIPTION
**Pull request by Shimada666**
resolves #704 

@amanape @808vita @rbren 
I implemented the same autoscroll feature in the chat interface as in Jupyter #1656 , but it conflicted with the mock typing effect, so I created a PR without the typing effect.

I have implemented the following features:

1. When the user is scrolling to previous content, display a "To Bottom" button while disabling autoscroll.
2. Upon clicking the "To Bottom" button, scroll to the bottom, enable autoscroll, and hide the "To Bottom" button.
3. When the user manually scrolls to the bottom, enable autoscroll and hide the "To Bottom" button.
4. Remove the mock typing effect.(Because implementing this feature elegantly with the typing effect was challenging for me, at amanape's suggestion, I removed typing effect and created this PR. Additionally, I believe that when we implement streaming in the future, we won't need to modify the code to make it compatible.)

### CODE REVIEW

**Comment by Shimada666** [comment]
https://github.com/OpenDevin/OpenDevin/assets/33391300/0d7fb084-e130-4b8c-9daf-1310f8c849c4

**Comment by Shimada666** [comment]
Regarding the "Continue" button: Show the "To Bottom" button when the user is browsing previous text, and only display the "Continue" button when the user has scrolled to the bottom and is in the "awaiting user input" state.

**Comment by neubig** [comment]
@amanape , it'd be nice if you could take a look!

**Review by amanape — APPROVED** [review]
Great stuff!

As mentioned though this does remove the typing effect. I am for this change, especially since it is not real streaming and only slows things.

@neubig @yimothysu Should we go ahead with removing the typing effect and create a separate issue/PR for a basic typing indicator (e.g., 3 dots)? It will make things simpler (this PR being an example) and faster at the cost of a downgraded UI indicator.

Maybe if we ever extend the backend to forward stream, we can implement it directly on the frontend too

**Comment by neubig** [comment]
I'm ok with that approach!

**Comment by Shimada666** [comment]
@amanape @neubig 
Thanks for your review!
Should I remove the useTyping-related code? Keeping it in the code without using it might cause confusion.

**Comment by amanape** [comment]
@Shimada666 Yes I missed that. We can remove it on the PR that adds a new replacement (e.g., 3 dot indicator)

**Pull request merged**
