### PR TITLE
Add: a mechanism for tracking contributions to the paper

### PR DESCRIPTION
**Pull request by huybery**
To provide a mechanism for tracking contributions to the paper, we need to discuss and gather as much evidence as possible to fairly decide on contribution points and the order of authorship. This is currently a draft and not yet complete. The names and scores in the table are temporary placeholders. We hope to hear more ideas from everyone.

### CODE REVIEW

**Comment by huybery** [comment]
🤔 I think we can track the contributions of each one under this PR, and for special contributors we can also discuss here.

**Comment by huybery** [comment]
HumanevalPack: https://github.com/OpenDevin/OpenDevin/pull/1917

**Comment by huybery** [comment]
GAIA: https://github.com/OpenDevin/OpenDevin/pull/1911

**Comment by huybery** [comment]
SWE-bench: https://github.com/OpenDevin/OpenDevin/pull/1468
(Undoubtedly, it will receive more points!)

**Comment by neubig** [comment]
Closed as the paper is mostly finished, great work everyone!

**Pull request closed without merging**
