### PR TITLE
Added playwright commands

### PR DESCRIPTION
**Pull request by SmartManoj**
Solves #1172

### CODE REVIEW

**Comment by rbren** [comment]
@SmartManoj were you able to test this?

**Comment by SmartManoj** [comment]
Didn't test yet.

**Comment by rbren** [comment]
Yeah feel free to add an action that tests it!

**Comment by neubig** [comment]
Hi!

@SmartManoj 's original PR was the right command but in the wrong place (it needs to be in the main environment, not the environment that builds the backend venv), so I pushed a fix. I ran this and confirmed that it works.

It
* Fixes https://github.com/OpenDevin/OpenDevin/issues/1276
* Fixes https://github.com/OpenDevin/OpenDevin/issues/1172

**Pull request merged**
