### PR TITLE
Update dev container to Ubuntu 24.04

### PR DESCRIPTION
**Pull request by charliez0**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
Nothing but update ubuntu version does not affect working
---

**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Other references**

### CODE REVIEW

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/issues/1977#issuecomment-2183960361

**Comment by yufansong** [comment]
Why you decide to upgrate it?

**Comment by tobitege** [comment]
The team is working on architectural changes that will also affect the sandbox.
If/when this will include a change to the base image, remains to be seen and needs to happen within our development considerations.
Closing this now.

**Comment by charliez0** [comment]
> Did you get this problem? [#1977 (comment)](https://github.com/OpenDevin/OpenDevin/issues/1977#issuecomment-2183960361)

tested with 24.04, no problem

**Pull request closed without merging**
