### PR TITLE
feat: align status bar with control bar

### PR DESCRIPTION
**Pull request by Sparkier**
Before:
2024-04-19 at 11 04 23

After:
2024-04-19 at 11 03 49

### CODE REVIEW

**Review by rbren — APPROVED** [review]
😌

**Comment by iFurySt** [comment]
image

imo, i think this layout is better, wdyt?😄

**Comment by Sparkier** [comment]
> image
> 
> 
> 
> imo, i think this layout is better, wdyt?😄

Kinda agree. However the number of buttons was supposed to change at some point depending on agent state. If that will is the case I think it might make more sense to keep a is.

**Comment by rbren** [comment]
I was actually thinking we flip it, so message is on the left, and buttons on the right?

**Pull request merged**
