### PR TITLE
Guide for Ollama local LLM

### PR DESCRIPTION
**Pull request by JayQuimby**
I have written a little markdown file to outline the process that has worked for me to get local models running with OpenDevin. 

Main points:
 - setup
 - modify config file
 - litellm CLI
 - running opendevin
 - images for visual reference

### CODE REVIEW

**Comment by yimothysu** [comment]
Awesome, thanks!

**Comment by arcaneum** [comment]
@JayQuimby, thank you for putting this instruction together, 

I tried it, but I am not able to get it working for me with Ollama. For some reason it is saying it is not able to reach the api end point. 

I modified the config.toml file as below:

LLM_API_KEY="0"
WORKSPACE_DIR="./workspace"
LLM_BASE_URL="http://localhost:11434"
LLM_MODEL= "ollama/llama2:13b"

Not sure whether there is any other part of the config that I might need to tweak?

I'm trying to run this on Mac OSX.

**Comment by arcaneum** [comment]
Thank you, @JayQuimby. 
You mean this config below that you proposed? Will try it out. Tried so many things, and since nothing was working, I was taking a break 😊

https://github.com/OpenDevin/OpenDevin/issues/647#issuecomment-2037021007

**Comment by arcaneum** [comment]
> @arcaneum [this](https://github.com/OpenDevin/OpenDevin/issues/647#issuecomment-2037021007) should fix your issue.

@JayQuimby, I tried it, but still not working for me. Still the same error with "no healthy deployment" message and it is still passing the gpt4 model. 

`Oops. Something went wrong: Error condensing thoughts: No healthy deployment available, passed model=gpt-4-0125-preview`

Was wondering whether the "no healthy deployment error" has something to do with Opendevin running inside the docker container and Ollama running outside on my local host machine and not being able to communicate with each other?

I tried to map the two using `OLLAMA_ORIGINS=http://localhost:* ollama serve # Allows any port on localhost`. However, the 'localhost' context is different on my local machine vs. opendevin's localhost running inside the container.

I then tried to map the ollama port to docker with this command, but that didn't solve the issue either — I guess I'm probably not doing it right: `docker run -p 11434:11434 ghcr.io/opendevin/sandbox
`

For now, I've run out of ideas...

**Comment by JayQuimby** [comment]
@arcaneum 

in `opendevin/llms/llm.py` change first line of `__init__` to this:
```
self.model_name = model if model and api_key.lower() != 'ollama' else DEFAULT_MODEL_NAME
```

**Comment by arcaneum** [comment]
> @arcaneum
> 
> in `opendevin/llm/llm.py` change first line of `__init__` to this:
> 
> ```
> self.model_name = model if model and api_key.lower() != 'ollama' else DEFAULT_MODEL_NAME
> ```
> 
> and make sure you have your API key set to `"ollama"` in your config

Yes, I made those changes in llm.py and config file, but no luck...

**Comment by JayQuimby** [comment]
Some random questions:
What OS are you running on?
Did you follow [this](https://github.com/OpenDevin/OpenDevin/blob/main/docs/examples/LOCAL_LLM_GUIDE.md) new version of the guide?
Are you using `make build` then `make run`?
I am not sure that the sandbox works, is that the only one you tried running?

**Comment by JayQuimby** [comment]
> Also, as a side note, would dolphin-mistral be better than codellama:python for Python, in case you have tested it? Many thanks.

I have found dolphin-mistral to be the best in testing, but the benchmarks don't work yet, so that is anecdotal. I have not tried codellama yet.

**Comment by arcaneum** [comment]
@JayQuimby, thank you very much for your patience and help. It's working for me now! I deleted the entire git clone folder and dicker image and started from scratch, and then did the llm.py and config.toml file modifications as per your guidelines....and so it runs now.
But after all that, the result is so underwhelming to say the least as compared to running it on GPT4 😊. Also, it's pushing my M3 Max GPU to the limit (which doesn't normally happen when I'm directly running these models via Ollamac or LMStudio)...and It's not really doing anything....but the Ollama connection works now. 

Also, thank you for testing codellama. I was just testing dolphin-mistral, and it's quite impressive as well, though doesn't seem to play well with OpenDevin.

**Comment by SGr33n** [comment]
Trying to make this work, on WSL. Pulled from the git yesterday, the OpenDevin interface is a bit different to me, I don't have planner but I got a cog icon on the left bottom corner where I can define some options:

image

Looks like that the model defined on this window takes precedence over the LLM_MODEL defined on the config file.
By the way... once started a project with llama2 13b OpenDevin stucks after summarizing the requested task.

**Pull request merged**
