### PR TITLE
fix: test_ipython being skipped

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Fixes: https://github.com/OpenDevin/OpenDevin/issues/2474

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

The integration test `test_ipython` was wrongly skipped due to wrong logical operator in test setup.

### CODE REVIEW

**Review by SmartManoj — APPROVED** [review]

**Comment by tobitege** [comment]
Hmm... test failed, checking...

**Comment by tobitege** [comment]
Ah, this exact bug had the ipython mock data not generated with my last PR.
Gonna regenerate them, again....

**Review by SmartManoj — CHANGES_REQUESTED** [review]
How ~will~ did the last commit fix the test?

---
The text file was not generated due to the prompt mismatch.

**Comment by tobitege** [comment]
> How will the last commit fix the test?

My PR from yesterday was missing updated mock files for the test_ipython due to the bug here, so today the server still had the "old" mock data with the agentskills commands.
This commit now brought the updated prompts and we should be good now.

**Pull request merged**
