### PR TITLE
Revert "Fix/attribute error"

### PR DESCRIPTION
**Pull request by SmartManoj**
Reverts OpenDevin/OpenDevin#1812

#1820 is the correct PR

Solves #1851

### CODE REVIEW

**Review by isavita — APPROVED** [review]

**Comment by isavita** [comment]
I can confirm that I am getting error about this line on the main branch
```bash
Traceback (most recent call last):
  File "/Users/isavita/git/OpenDevin/opendevin/server/session/msg_stack.py", line 102, in _del_messages
    new_data[sid] = [Message.from_dict(msg) for msg in msgs]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isavita/git/OpenDevin/opendevin/server/session/msg_stack.py", line 102, in <listcomp>
    new_data[sid] = [Message.from_dict(msg) for msg in msgs]
                     ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_dict'
```

**Review by neubig — CHANGES_REQUESTED** [review]
Thanks for working on this!

However, I'm not sure that this is correct. The type of `self._messages` is `dict[str, list[Message]]`, but by removing the `Message.from_dict()` call, this would probably result in the values of `self._messages` being of type `list[dict]`, not `list[Message]`.

We may:
1. need a more fundamental solution
2. additionally want to add unit tests to make sure that this function works properly, to prevent regressions in the future

**Comment by SmartManoj** [comment]
data is json.

**Comment by neubig** [comment]
Yes, I understand data is json. Did understand my comment about the typing on `self._messages`? If not I can elaborate!

**Comment by SmartManoj** [comment]
But, we didn't assign `self._messages` in this function.

**Review by neubig — APPROVED** [review]
Oh, I'm really sorry! In the github review interface it didn't give me the function name and when I looked at the whole file I accidentally looked at `_load_messages()`. In that case this looks good (although it'd still be nice to have a unit test).

**Pull request merged**
