### PR TITLE
Fix: Add scroll functionality to file explorer sidepane

### PR DESCRIPTION
**Pull request by richardokonicha**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Fixes issue [#2714](https://github.com/OpenDevin/OpenDevin/issues/2714) Adds more width control and scroll functionality to the File Explorer side pane.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

- Adds scroll functionality for overflow content
- Updates width transition for improved UX

**Other references**

N/A

### CODE REVIEW

**Comment by iFurySt** [comment]
image

the icon will be missing. you can try to solve it or I can help you to handle it later today.

**Comment by richardokonicha** [comment]
https://github.com/OpenDevin/OpenDevin/assets/48168290/e142ed33-207c-47c6-a754-0251fc657de6

branch updated see video for illustration, see last commit to review code.

**Comment by tobitege** [comment]
> @tobitege @iFurySt branch updated see video for illustration, see last commit to review code.

That works much better, cool!

**Review by tobitege — APPROVED** [review]
This looks good, thanks!

**Comment by richardokonicha** [comment]
super ✨ thanks for the assist @tobitege @iFurySt

**Pull request merged**
