### PR TITLE
style: Action and Observation use schema for unifying

### PR DESCRIPTION
**Pull request by iFurySt**
This PR only changes the String Literal of Action and Observation to the schema.ActionType and schema.ObservationType.
but I opened the Black Formater, so the change seems like a lot. 😄

### CODE REVIEW

**Comment by iFurySt** [comment]
are you going to merge this? unifying constant

**Comment by rbren** [comment]
@iFurySt sorry I missed this one! This seems like a great change--sorry for the rebase pain

**Review by rbren — APPROVED** [review]

**Comment by iFurySt** [comment]
okay, i handle it later🥳

**Comment by iFurySt** [comment]
@rbren hard to catch up~ appreciate it if you have time to merge it into the main branch.

**Comment by rbren** [comment]
Thank you!

**Pull request merged**
