### PR TITLE
docs: add docker image docs

### PR DESCRIPTION
**Pull request by yufansong**
As shown in #261, I find many beginners will miss the docker image details. So add some instructions for it.

### CODE REVIEW

**Comment by rbren** [comment]
These images are actually no longer maintained--we just switched to `ghcr.io`.

The images should get downloaded automatically. Did you have to pull them manually?

**Comment by yufansong** [comment]
> These images are actually no longer maintained--we just switched to `ghcr.io`.
> 
> The images should get downloaded automatically. Did you have to pull them manually?

1. I verified again, if no image in local, run `uvicorn opendevin.server.listen:app --port 3000` or `python3 opendevin/sandbox/sandbox.py ` both will trigger the error that image node found. I know when run k8s, it can set [image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy). Not sure whether we can config the similiar thing in sandbox code.
2. I tried `docker pull ghcr.io/opendevin/sandbox:v0.1`, but will get `Error response from daemon: denied`. I wonder if we config `ghcr.io` correctly or I use the wrong url.

**Comment by rbren** [comment]
Whoops--looks like it's private. Asking them to make it public.

That's unfortunate that the image needs to be present. I think these docs are an improvement so let's get it in. We can change the URL once it's fixed.

**Comment by yufansong** [comment]
BTW, can you also add the `latest` tag for the image? It will be more convenient for pulling image.

**Comment by yufansong** [comment]
Open 2 issues for make image public #270 and add `latest` image tag #272

**Pull request merged**
