### PR TITLE
refactor: use Pydantic `BaseModel` instead of `dataclass` in `events` folder files

### LINKED ISSUE #1634: Use pydantic to enforce type checks for Action
**What problem or use case are you trying to solve?**

Actions are decorated by`@dataclass` from `dataclasses` package. This, together with mypy defined in the pre-commit hooks, does static type checks, but still doesn't enforce type checks during runtime. This means a wrong json generated by LLM might be deserialized into an `Action` object without type errors.

Proof: `test_action_serialization.py` has two bugs:
- `test_modify_task_action_serialization_deserialization` uses `int` type for `id` while it should be `str`.
-  `test_cmd_kill_action_serialization_deserialization` uses `str` type for `id` while it should be `int`.

These bugs are not captured by pytest, because we don't enforce type checks during runtime.

**Describe the UX of the solution you'd like**

Use pydantic's BaseModel to replace `@dataclass` annotations for Action classes.

**Do you have thoughts on the technical implementation?**

~~This seems straightforward to fix, but it would be cool if someone could use OpenDevin to fix it!~~

### PR DESCRIPTION
**Pull request by Umpire2018**
close #1634 

**TODO**

- [ ] Modify tests in `tests/unit/test_action_serialization.py` to make sure use the correct type like uses str type for id.
- [ ] Add more tests in `tests/unit/test_observation_serialization.py` 

I think that existing tests lacked full coverage compared to `tests/unit/test_observation_serialization.py` so i expanded the refactor to include the entire `events` folder.

Further more, would it be beneficial to replace all usage of `dataclass` with Pydantic `BaseModel` classes to ensure consistent data validation and type checking across the project?

### CODE REVIEW

**Comment by rbren** [comment]
Nice! I like where this is headed

**Comment by li-boxuan** [comment]
> Further more, would it be beneficial to replace all usage of dataclass with Pydantic BaseModel classes to ensure consistent data validation and type checking across the project?

I agree with that. Doing so only for Action is good enough to me though.

**Comment by Umpire2018** [comment]
Hey guys @rbren @li-boxuan @enyst , i need help here.

If we use Pydantic's `BaseModel`, we can use `model_dump` to return a dictionary of the model's fields and values, which is similar to `asdict` in `dataclass`. 

**Difference**:
- `model_dump` does not return class attributes.
- However, we need to access `action` as a class attribute for mapping purposes: 
  ```python
  ACTION_TYPE_TO_CLASS = {action_class.action: action_class for action_class in actions}
  ```

  and we need to access `action` in `Action to_memory` output.

  ```python
  class Action(Event):
    async def run(self, controller: 'AgentController') -> 'Observation':
        return NullObservation('')

    def to_memory(self):
        d = super().to_memory()
        try:
            v = d.pop('action')
        except KeyError:
            raise NotImplementedError(f'{self=} does not have action attribute set')
        return {'action': v, 'args': d}
  ```
 #### Solution 

It seems like we should use Pydantic's dataclass to achieve this goal while ensuring class attributes are accessible for the mapping.

### Source code

#### BaseModel

```python
from pydantic import BaseModel
from typing import ClassVar

class Event(BaseModel):
    def to_memory(self):
        return super().model_dump()


class MessageAction(Event):
    content: str
    action: ClassVar[str] = 'ActionType.MESSAGE'

message = MessageAction(content="test")
print(message.to_memory())

# Output:
{'content': 'test'}
```

#### dataclass

```python
from dataclasses import asdict, dataclass


@dataclass
class Event:
    def to_memory(self):
        print(f"asdict: {asdict(self)}")
        return asdict(self)

@dataclass
class MessageAction(Event):
    content: str
    action: str = 'ActionType.MESSAGE'

message = MessageAction(content="test")
print(message.to_memory())

# Output
{'content': 'test', 'action': 'ActionType.MESSAGE'}
```

**Comment by enyst** [comment]
IMHO the possible approaches currently in code or discussions are, in order of complexity, from simple to complex (for client code):

- In class/metaclass > pydantic dataclasses > pydantic BaseModel/full framework.

> Further more, would it be beneficial to replace all usage of dataclass with Pydantic BaseModel classes to ensure consistent data validation and type checking across the project?

I made an attempt to use Pydantic's BaseSettings for our config, and I can't say I liked it. I'm proposing dataclasses instead, in this PR: https://github.com/OpenDevin/OpenDevin/pull/1552. It seems to me that pydantic is very _very_ opinionated, and they admit it themselves, it's totally intended. Silly example, but it was funny: right at the first runs it threw a bunch of complaints that my .env had more vars than the settings or something. I think all I did was inherit a class, so... 😅  why did it have to pick on my env?

OK, I get there's a reasoning behind such restriction, but there's _always_ a reasoning behind every restriction in every opinionated framework. It doesn't mean it's always worth the trade-offs... even if, yes, I could simplify my env.

Please see though a more interesting example, partial updates with pydantic BaseModels: https://stackoverflow.com/questions/67699451/make-every-field-as-optional-with-pydantic

Leaving aside whether or not they're needed for events (maybe not; they're needed for others), that discussion is amazing. Considering to fully duplicate code in order to just update an instance? 😢  The chosen solution is even more interesting: it uses a metaclass _to bypass Pydantic's restrictions_. That IMHO is a red flag... How much will we work with it and how much fight with it?

Please do note that I haven't used pydantic this way in any significant measure, but I keep looking into it since it was first proposed in this project, and my heavily Java-influenced brain recognizes a lot of its approach and frustrations with it. IMHO it doesn't fit the style of the codebase and it would really affect simplicity.


So what I wonder is, python is wonderfully dynamic, and if we may need to use metaclasses anyway, couldn't we use them to do only the job we wanted instead? That's what I'm attempting to do [here](https://github.com/OpenDevin/OpenDevin/pull/1552/files#diff-c1fc25486ab02efac71137dfd0a45bbaa34d484fa93f6bd110b8d35412f72756) for partial/full updates.

It simplifies the client code, and IMHO that's what matters. That's us in how we work with it, that's agent developers, and so on. Seamless updates, with simplicity for client code, is what I was aiming for.

Maybe events need more, so we might need to go more to the right side of that list. I'm not sure they do (we could enforce types at creation in the metaclass...), but this is why I suggested pydantic dataclasses in the linked issue, it's at least not fully on the right side...


[1] The solution still makes two classes for the same thing, one normal, one updatable. And it doesn't seem to handle nested classes yet. That's more code needed... _to work around pydantic_.

**Comment by Umpire2018** [comment]
@enyst Thank you so much for all your kind word and suggestion. I will continue to work with `pydantic dataclass` instead of `BaseModel` to aviod breaking changes and any hard case which i don't want currently. :sweat_smile:

**Pull request closed without merging**
