### PR TITLE
feat: add agent status bar.

### PR DESCRIPTION
**Pull request by iFurySt**
and fix #890

### CODE REVIEW

**Comment by iFurySt** [comment]
Xnip2024-04-09_17-53-43

i think this UX is better for whole chat window show init, and we can extend the agent status, like:
 - Agent is typing
 - Agent is initializing
 - Agent is thinking
 - Agent is ready
 - Agent is not available

**Comment by iFurySt** [comment]
https://github.com/OpenDevin/OpenDevin/assets/16201837/b14eb1c6-bce1-4ad4-b422-edd3ce724fc4

**Comment by iFurySt** [comment]
> LGTM! Just I think if the status bar is shown, the input should be just in read-mode what do you think? it was like that before.

you mean the user can't input when init?

**Comment by dorbanianas** [comment]
maybe we can merge this and open a new PR

**Comment by dorbanianas** [comment]
WDYT?

**Comment by iFurySt** [comment]
> yes exactly
it seems good for the user can input when init. you can see this #859

**Comment by iFurySt** [comment]
the user can input but can't submit the message when the agent is initing.

**Comment by dorbanianas** [comment]
AHHHHH got it 👌

**Review by dorbanianas — APPROVED** [review]

**Comment by dorbanianas** [comment]
@iFurySt do you think we are ready to merge it?

**Pull request merged**
