### PR TITLE
docs: update docker run command to pull default 'latest' tag

### PR DESCRIPTION
**Pull request by richardokonicha**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Updates docs to clarify Docker image tags for stable and nightly updates; 
this issue is related to #2730

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

Updates documentation to specify the latest for stable and main for nightly; 

Screenshot 2024-07-05 at 12 10 27 AM

### CODE REVIEW

**Comment by richardokonicha** [comment]
review ready @xingyaoww @tobitege

**Comment by xingyaoww** [comment]
image

The create date of the `latest` tag is still in April.. let me update it first.

**Comment by xingyaoww** [comment]
Manually tagged it

image

**Review by xingyaoww — APPROVED** [review]
LGTM!

**Comment by mamoodi** [comment]
It's kind of a pain but we have the exact same information on this page: https://github.com/OpenDevin/OpenDevin/blob/main/docs/modules/usage/intro.mdx

Are you able to make the same changes there so they are aligned please?

**Comment by richardokonicha** [comment]
> It's kind of a pain but we have the exact same information on this page: https://github.com/OpenDevin/OpenDevin/blob/main/docs/modules/usage/intro.mdx
> 
> Are you able to make the same changes there so they are aligned please?

yes, the update was made on that file [docs/modules/usage/intro.mdx](https://github.com/OpenDevin/OpenDevin/pull/2804/files#diff-cacf07929a1966795daecf4333eb0c5f4c8595211c369b377ec2a54fdb3d66d7)

see https://github.com/OpenDevin/OpenDevin/pull/2804/files

**Comment by tobitege** [comment]
Nicely done!

**Comment by richardokonicha** [comment]
> Nicely done!

thanks💪🏾 @tobitege

**Comment by SmartManoj** [comment]
@richardokonicha Could you update here too?https://github.com/OpenDevin/OpenDevin/blob/a081935fd82478c35d5f7506785ebe93ae1e748d/README.md?plain=1#L67

**Pull request merged**
