### PR TITLE
chore: Add architecture diagram.

### PR DESCRIPTION
**Pull request by iFurySt**
image

### CODE REVIEW

**Comment by tobitege** [comment]
Hmm "Error: Unable to build website for locale en."   Since when is that an issue? 🤯

**Comment by tobitege** [comment]
Awesome diagramm, Leo! Love it!! 🎖️

**Review by tobitege — APPROVED** [review]
Awesome!

**Comment by iFurySt** [comment]
> Hmm "Error: Unable to build website for locale en." Since when is that an issue? 🤯

let me have a look.

**Pull request merged**
