### PR TITLE
[WIP] Implement a search agent based on `moatless-tools` 

### PR DESCRIPTION
**Pull request by ryanhoangt**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
This PR is to integrate `moatless-tools` into OpenDevin's agent hub, as proposed in [#2353](https://github.com/OpenDevin/OpenDevin/issues/2353)

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**
- this implements an agent specializing in searching for relevant code snippets given a task. I'm thinking about making `CodeActAgent` delegate search tasks for it when needed.

**Demo**
An example of running `MoatlessSearchAgent` in the browser:

Screenshot 2024-06-24 at 21 42 22

### CODE REVIEW

**Comment by neubig** [comment]
Heads up @aorwall in case you're interested!

**Comment by tobitege** [comment]
Hey @ryanhoangt 
is this still under development?

**Comment by ryanhoangt** [comment]
Hi @tobitege, sorry for letting the PR unmerged for a very long time. I've finished a draft version of the agent and tried running `swe-bench` eval on it, but the result was not as good as the original `moatless-tools`. Had talked about it with @neubig, considering some other limitations and the current performance of OpenDevin, perhaps we can close this PR for now and wait for a better integration or implement a better search agent if possible.

**Comment by tobitege** [comment]
Understood, thanks for the status update!

**Pull request closed without merging**
