### PR TITLE
(fix) Selectively install poetry

### PR DESCRIPTION
**Pull request by foragerr**

### CODE REVIEW

**Comment by foragerr** [comment]
@dorbanianas @rbren review please.

**Comment by dorbanianas** [comment]
for the command that I it install poetry just if it's not installed, and if there's an update it updates the next version you can check that by running `make build` multiple times so you will notice that it skips poetry installation

**Comment by dorbanianas** [comment]
let me know if I misunderstood!

**Comment by foragerr** [comment]
No, you're right.
My change does not address the global installation issue anyway. I'm closing this.

**Pull request closed without merging**
