### PR TITLE
Refactor: Remove extra log in property

### PR DESCRIPTION
**Pull request by SmartManoj**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

image

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

**Separation of Concerns:**

Properties are intended to provide a simplified, encapsulated way to access class attributes. Logging within a property method mixes concerns, as logging is more about monitoring and debugging rather than data access and manipulation.

**Simplified Interface:**

Keeping property methods concise and focused on their primary purpose (attribute access) ensures that they remain easy to understand and maintain.

**Logging Redundancy:**

If logging of the workspace directory mount point is necessary, it can be handled at a higher level in the application, such as during the initialization phase or when the configuration is first loaded, rather than every time the property is accessed.

By removing the logging statement from the volumes property, we adhere to the principle of keeping property methods focused on their primary role of attribute access. This change enhances the clarity and performance of the code while ensuring that logging, if necessary, is handled in a more appropriate context.

### CODE REVIEW

**Comment by enyst** [comment]
I agree it's a bit redundant, but I'm torn because I kinda like to see it. 😅 

Do we have another line logging the actual workspace?

**Review by neubig — CHANGES_REQUESTED** [review]
Hey @SmartManoj , I agree that this is a good change, but as @enyst points out this will probably remove our only method for logging the workspace. So it'd be good if we re-add it somewhere else more appropriate so we don't lose logging of the directory altogether.

**Comment by tobitege** [comment]
I don't understand the AI reasoning of this PR, which seems to not get the global picture.
This logging provides troubleshooting information at the right place. Removing it defeats the purpose.

**Comment by neubig** [comment]
Hey @tobitege, to explain a little more I think the current log is an incorrect representation of what the function is doing. It's saying "mounting", but actually no mounting is happening in this function (instead, it's probably happening when the docker container is started).

**Comment by tobitege** [comment]
> Hey @tobitege, to explain a little more I think the current log is an incorrect representation of what the function is doing. It's saying "mounting", but actually no mounting is happening in this function (instead, it's probably happening when the docker container is started).

Ok, I see. Then I agree with you saying it better be moved instead.
But logging the name of that folder as a vital startup information I see as a feature, not a bug. 😁

**Review by tobitege — APPROVED** [review]
@neubig As @SmartManoj pointed out to me, in the PR's screenshot above, the occurence in line 709 logs all that info as well.
I mistakenly thought, the values there could be different, but I was wrong.
Having said that, I'm ok with getting this merged.

**Review by neubig — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
