### PR TITLE
chore: update CI workflows to integrate testing with environment setup

### PR DESCRIPTION
**Pull request by Umpire2018**
- Implement reusable workflow `setup-environment.yml` to configure the test environment on both macOS and Ubuntu.
- Add back missing `test-only-sandbox-on-macos` in previous commit.

### CODE REVIEW

**Comment by Umpire2018** [comment]
Not sure why the `actions` are stuck and not getting results.

[Run Unit Tests Result](https://github.com/OpenDevin/OpenDevin/actions/runs/9060179184)

**Review by rbren — APPROVED** [review]
LGTM!

**Comment by rbren** [comment]
Actually--maybe it makes sense to keep the sandbox tests in their own CI check? WDYT?

**Comment by Umpire2018** [comment]
> Actually--maybe it makes sense to keep the sandbox tests in their own CI check? WDYT?

Good idea!

Create a new folder `./tests/sandbox` to isolate from unit/integration tests, providing cleaner test result output and easier environment setup.

**Comment by Umpire2018** [comment]
Close this because of can not pass tests.

**Pull request closed without merging**
