### PR TITLE
[Experiment] Evaluate the effectiveness of using more fine-grained search tools 

### PR DESCRIPTION
**Pull request by ryanhoangt**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

This PR is for running evaluation with ACR's tools integrated, to evaluate the effectiveness of using more search tools. If it proves to be helpful, we can discuss about a full reimplementation.
Currently, I have changed the AST parsing from `ast` to `tree-sitter`, to reuse it from the linter and to add more languages in the future.

---

**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Other references**

### CODE REVIEW

**Comment by ryanhoangt** [comment]
Cc: @neubig, @xingyaoww, if you folks can help me with the eval! Because we can't merge this PR as the code is licensed, and I think the current code already works for the eval, I'm a bit lazy to merge `main` and deal with new config changes 😅 If you find it's necessary, let me know and I can do it.

**Comment by xingyaoww** [comment]
I think the conflict is not hard to resolve - i can help you resolve it if needed? I can look into it later today

**Comment by ryanhoangt** [comment]
That's great, thank you!

**Comment by xingyaoww** [comment]
FYI: I've start running the evaluation!

**Comment by ryanhoangt** [comment]
Close the PR for now, as adding tools naively doesn't seem to help, especially when LLMs are becoming better! Thanks @xingyaoww and @neubig for helping me with this!

**Pull request closed without merging**
