### PR TITLE
Unify linter behaviour across CI and pre-commit-hook

### PR DESCRIPTION
**Pull request by li-boxuan**
Currently, we have some linting rules as part of pre-commit-hook, but not CI. Most importantly, pre-commit-hook contains a double-quote-string-fixer hook which changes all double quotes to single quotes, but I do observe some PRs with massive changes that do the opposite way. I suspect that these authors of these PRs 1) disable or circumvent the pre-commit-hook, and 2) have other linters such as black in their IDE, which automatically change all single quotes to double quotes. This has caused a lot of unnecessary diff, made review really hard, and led to a lot of merge conflicts.

The goal is to make sure pre-commit-hooks don't create any "surprise" behaviour: if they make any changes, the changes  should be required by CI as well. On the other hand, any other linting efforts shall be rejected by CI. The fix is simple: remove other linters in CI and simply run pre-commit tool, which then runs all rules and linters configured in pre-commit-hook.

In addition, this PR disables E501 (max-line-length) for PEP8 which fights with mypy linter a lot.

### CODE REVIEW

**Comment by li-boxuan** [comment]
https://github.com/OpenDevin/OpenDevin/actions/runs/8672278363/job/23782396679?pr=1071 CI failed as expected

**Comment by foragerr** [comment]
Will this change require a 1 time run of the linter across all files?
or is that already included in this PR?

**Comment by li-boxuan** [comment]
A one time run of linters is already included in this PR ;)

Otherwise the CI won’t pass

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by foragerr** [comment]
overall LGTM. 
Branch needs to be caught up with main once more.

**Comment by foragerr** [comment]
re-triggering the failed job.

**Comment by foragerr** [comment]
Thanks for doing this. The constant ping-ponging between `'` and `"` made every PR very hard to read.

**Comment by li-boxuan** [comment]
@foragerr It seems you need to approve this PR on GitHub GUI

**Review by foragerr — APPROVED** [review]

**Pull request merged**
