### PR TITLE
Install chromium only once

### PR DESCRIPTION
**Pull request by SmartManoj**
Skips issue #1562 for subsequent runs.

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
The name `cache/setup.txt` doesn't make it clear what this file indicates. Maybe `cache/playwright_chromium_is_installed.txt` or something would be better?

**Comment by SmartManoj** [comment]
`setup.txt` will be used for similar things in the future with contents like
`playwright_chromium = 1`

**Comment by neubig** [comment]
OK, thanks! Even if that's the case we should probably keep the current state of the code clean, so please either:
1. go ahead and implement it that way now
2. rename the file to be descriptive now, and refactor in the future

**Review by neubig — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
