### PR TITLE
Restore SWE-bench dep refs

### PR DESCRIPTION
**Pull request by john-b-yang**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Restores the references to SWE-bench to be the most recent commit. The PR for fixing Django parsing posted by @xingyaoww was merged, and now the main SWE-bench commit can be incorporated.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

Updates dependency specifications in `pyproject.toml` and `poetry.lock` to reflect this update.

**Other references**

N/A

### CODE REVIEW

**Review by enyst — APPROVED** [review]
Thank you! ❤️

**Comment by tobitege** [comment]
Please run `poetry lock --no-update` and re-commit the poetry.lock file

**Comment by tobitege** [comment]
@enyst does the outdated poetry.lock file get merged in this state (see errors)?

**Comment by enyst** [comment]
Ref: https://github.com/OpenDevin/OpenDevin/pull/2728#discussion_r1663041822

I'll take a look at poetry, thanks!

**Comment by enyst** [comment]
> @enyst does the outdated poetry.lock file get merged in this state (see errors)?

We can't merge with errors, CI won't allow it. (except for Mac, iirc, but that's different)

**Comment by john-b-yang** [comment]
Ah shoot ok, looks like I didn't set up some things properly. I can't get to this at this second, but I can try again later today and see if I can push the correct auto-generated `poetry.lock`. thanks!

**Comment by john-b-yang** [comment]
Ah ok just approved it, thanks @xingyaoww! Still learning the repo a bit - the docs are great, i just messed up and didn't read carefully enough. Just approved + merged the PR you made on my fork!

**Comment by xingyaoww** [comment]
Thanks a lot @john-b-yang - Congrats on the first PR! Let's merge it (if the test suite doesn't complaints 😄 ).

**Comment by john-b-yang** [comment]
Thank you and sounds great! 🥳

**Pull request merged**
