### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AbhisekOmkar**
Updated the README.md file to include comprehensive documentation for setting up the OpenDevin Frontend project. The documentation covers installation instructions, available npm scripts, setting up the terminal, and additional resources for learning React. This commit enhances project clarity and facilitates easier onboarding for new contributors.

### CODE REVIEW

**Comment by neubig** [comment]
Hi @AbhisekOmkar , I'm seeing conflicts with the README, could you please resolve them?

**Comment by AbhisekOmkar** [comment]
Im not able to understand what is the conflict is in README

**Comment by xcodebuild** [comment]
Thanks for your contribution @AbhisekOmkar , the front-end toolchain has been migrated to vite. Most of the information in the README is now obsolete (for example `npm run eject` is no longer valid). You can refer to https://github.com/OpenDevin/OpenDevin/pull/24.

**Comment by AbhisekOmkar** [comment]
i need to update in my local machine and then i can create new PR for it

**Pull request closed without merging**
