### PR TITLE
feat(frontend): Added React Router

### PR DESCRIPTION
**Pull request by ChrisMamatas**
This PR addresses #2055 by adding React Router while maintaining the existing UI as the main index screen.

### CODE REVIEW

**Comment by amanape** [comment]
Thanks for the PR! If you're interested to continue building upon this, take a look at this [Slack thread](https://opendevin.slack.com/archives/C06QT0AGY4W/p1716561163505129).

**Comment by amanape** [comment]
Looks like you got a small linting error to resolve (import order). Push to fix and merge it

**Comment by ChrisMamatas** [comment]
> Thanks for the PR! If you're interested to continue building upon this, take a look at this [Slack thread](https://opendevin.slack.com/archives/C06QT0AGY4W/p1716561163505129).

Can't see the thread. Could you send an invite link to the slack?

**Comment by amanape** [comment]
@ChrisMamatas You can find it at the bottom of the README: https://join.slack.com/t/opendevin/shared_invite/zt-2ggtwn3k5-PvAA2LUmqGHVZ~XzGq~ILw

**Pull request merged**
