### PR TITLE
Update linter

### PR DESCRIPTION
**Pull request by JeffKatzy**
Fixes merge conflicts

### CODE REVIEW

**Comment by JeffKatzy** [comment]
@xingyaoww Can you look over this.

**Comment by xingyaoww** [comment]
Is this PR related to another PR?

**Comment by tobitege** [comment]
> Is this PR related to another PR?

No. It was fine a couple of days ago, but Jeff has to look into merging issues now due to the recent refactors.
This was supposed to be tested then with evals, if you had time and this is were ready.
Will need to revisit when Jeff gives the green light.

**Comment by xingyaoww** [comment]
What was the `OpenDevin/update_linter` branch for - is this for another PR? Since this is not related to the `main` branch, especially if it is related to a ongoing PR, it is probably ok to directly merge it? - let me know when you are ready?

**Comment by JeffKatzy** [comment]
So the update `update_linter` branch was for the same pr, but then it looked like I really messed up the rebase, and unfortunately force pushed to my `remote/update_linter` branch.  

So I pulled from `opendevin/update_linter` and rebased again.  

It looks like my main issue is with the `poetry.lock` file, which I generated by running `poetry lock --no-update` locally and then moved to github.  Should I do this differently, not sure what's wrong.

**Comment by JeffKatzy** [comment]
@xingyaoww, ok, I hope this is now fixed.  Locally, reran `make lint` and all unit tests, and double checked not duplicating libs in `pyproject.toml`.

**Comment by xingyaoww** [comment]
> the update update_linter branch was for the same pr

I'm a bit confused? I thought this PR is only opened 3 hours ago?

**Comment by xingyaoww** [comment]
Ahh do you mean fixing the conflict for this one: https://github.com/OpenDevin/OpenDevin/pull/2489

**Comment by xingyaoww** [comment]
If so, why merge into OpenDevin's `update_linter` branch? My impression is that you could just merge this PR into https://github.com/OpenDevin/OpenDevin/pull/2489 and we can merge that one directly into main?

image

**Comment by JeffKatzy** [comment]
Yes, I think the same commits have been propagated to [2489](https://github.com/OpenDevin/OpenDevin/pull/2489).

**Comment by xingyaoww** [comment]
If that's the case, is it safe to close this PR as we can continue work on this in https://github.com/OpenDevin/OpenDevin/pull/2489?

**Comment by JeffKatzy** [comment]
Yes, you can close this pr.  That sounds good!

**Comment by xingyaoww** [comment]
Thanks!

**Pull request closed without merging**
