### PR TITLE
Creating the experiment folder and adding initial analysis of Devin's evaluation outputs

### PR DESCRIPTION
**Pull request by Jiaxin-Pei**

### CODE REVIEW

**Comment by yufansong** [comment]
Should we always include `experiments/SWE-bench/data/devin_output_diffs.csv` in our commit? Not sure whether we should record the test result details every time. 
I worry if we do it, the repo size will increase quickly.

**Comment by Jiaxin-Pei** [comment]
> Should we always include `experiments/SWE-bench/data/devin_output_diffs.csv` in our commit? Not sure whether we should record the test result details every time. I worry if we do it, the repo size will increase quickly.

@yufansong  That makes sense, I just remove this file. I think in general we could allow some important and relatively small files. For other data files, I agree it would be better to keep them somewhere else and have people pull the data locally.

**Comment by yufansong** [comment]
> I think in general we could allow some important and relatively small files. 

Agree. 

> For other data files, I agree it would be better to keep them somewhere else and have people pull the data locally.

If we have many large experiements file, public google drive maybe a good choice. Welcome any other ideas.

**Comment by libowen2121** [comment]
LGTM. I just updated the folder naming and logistics.

**Pull request merged**
