### PR TITLE
Add contributors list

### PR DESCRIPTION
**Pull request by powerzbt**
Categorize the contributions of contributors in a way that supports and encourages further contributions.

### CODE REVIEW

**Comment by huybery** [comment]
Is there a way to automate this update?

**Comment by rbren** [comment]
+1 love the idea, but we should have a script to keep it updated

**Comment by rbren** [comment]
@powerzbt how did you generate this?

**Comment by powerzbt** [comment]
> +1 love the idea, but we should have a script to keep it updated

I am working on this. thank you for your vote.

**Comment by powerzbt** [comment]
> @powerzbt how did you generate this?

Based on contributor's commit history

**Comment by rbren** [comment]
ahh you wrote it by hand? 👍

**Comment by powerzbt** [comment]
> ahh you wrote it by hand? 👍

yeah 🥹

**Comment by PierrunoYT** [comment]
I don't really know how to this but I think you can do it with Github Actions.

Here is a summary of the key points:

To effectively manage and recognize contributors in a GitHub repository, the following approaches can be used:

1. Automation using GitHub Actions:
   - Create a workflow file to automatically update the contributors list when new contributions are made.
   - Utilize pre-built actions like "all-contributors" to list and categorize contributors.

2. Categorizing contributions:
   - Use the "All Contributors" specification to recognize contributions across different categories (e.g., code, documentation, design).
   - Leverage the "all-contributors" bot or action to maintain the categorization automatically.

3. Custom script for updating the contributors list:
   - Write a script that uses the GitHub API to retrieve the list of contributors and their contributions.
   - Update the contributors list in a file (e.g., `CONTRIBUTORS.md`) based on your categorization logic.
   - Integrate the script into a GitHub Actions workflow.

4. Encouraging further contributions:
   - Ensure the contributors list is prominently displayed in the project (e.g., in the `README.md` file) to show appreciation.
   - Consider including personalized acknowledgments or highlights for special contributions in project updates or newsletters.

The key benefits of these approaches are to save time, keep the recognition of contributors up-to-date, and foster a culture of appreciation and engagement within the project community.

**Comment by rbren** [comment]
There are a handful of utilities out there that automate this, e.g. https://github.com/mgechev/github-contributors-list

I think we just need to pick one and integrate it. Even if someone needs to run it by hand occasionally. But e.g. a github action that runs nightly would be 🥇

**Comment by rbren** [comment]
@powerzbt I'm going to close this, but if you find a way to automate it let us know!

**Pull request closed without merging**
