### PR TITLE
Revamp AgentRejectAction and allow ManagerAgent to handle rejection

### PR DESCRIPTION
**Pull request by li-boxuan**
#1615 introduced a new action type called `AgentRejectAction`, but was accidentally removed in #1626, likely due to merge conflict resolution. This PR adds reject action handling back.

This PR also:
1) Add ManagerAgent to integration testing for existing tests
2) Refine schema of Reject action
3) Prompt ManagerAgent to handle rejection from delegated agents
4) Add a new test that demonstrates rejection action

### CODE REVIEW

**Review by yufansong — APPROVED** [review]

**Comment by li-boxuan** [comment]
Hmmm, delegator action seems to be breaking now. I'll look into how to fix it...

**Comment by neubig** [comment]
Hi @li-boxuan , I'm just going through the backlog, you're still working on and interested in this right? It seems that #1910 was a step in the right direction.

**Comment by li-boxuan** [comment]
@neubig Yep I am working on it. Was busy with some benchmark work earlier but I am back on track with this now.

**Comment by li-boxuan** [comment]
Have to put this on hold again. Need to focus on wrapping up evaluations and paper.

**Review by neubig — APPROVED** [review]
This looks good, thanks @li-boxuan ! I think it can be merged after conflicts are resolved.

**Pull request merged**
