### PR TITLE
add github action for project build on macos and linux

### PR DESCRIPTION
**Pull request by dorbanianas**
This PR try to build make the github action build and run tests check all the possible platforms (macos, linux) and python version that we support (3.11, 3.12)

### CODE REVIEW

**Comment by dorbanianas** [comment]
@rbren I added this PR to ensure that the project works well on different OS but I faced the issue with python 3.12 on mac os  i you have any idea how to fix it let me know

**Comment by dorbanianas** [comment]
😮‍💨 It's working now 😅

**Review by neubig — APPROVED** [review]
LGTM, thanks!

**Comment by yufansong** [comment]
I find after this PR merged, my local env cannot work. Not sure whther it is my personal problem, but it introduce some problem about install chroma-hnswlib on mac with python version 3.12.1. 
Another question is, our code didn't use `chroma-hnswlib`, why we need to install it here?
```
make install-python-dependencies
Installing Python dependencies...
/bin/sh: chroma-hnswlib: command not found
Installing ...
Collecting chroma-hnswlib
  Using cached chroma-hnswlib-0.7.3.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/Users/yufansong/Library/Caches/pypoetry/virtualenvs/opendevin-hferh_kc-py3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/yufansong/Library/Caches/pypoetry/virtualenvs/opendevin-hferh_kc-py3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yufansong/Library/Caches/pypoetry/virtualenvs/opendevin-hferh_kc-py3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yv/zxw6zcm96mv624skng9fwccc0000gn/T/pip-build-env-efxl63ge/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yv/zxw6zcm96mv624skng9fwccc0000gn/T/pip-build-env-efxl63ge/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/yv/zxw6zcm96mv624skng9fwccc0000gn/T/pip-build-env-efxl63ge/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 73, in <module>
        File "<string>", line 90, in BuildExt
      ValueError: list.remove(x): x not in list
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [install-python-dependencies] Error 1
```

**Comment by enyst** [comment]
Looks like it was required by chromadb. I'm on MacBook and I usually update with ```poetry update``` these days.

```poetry show chroma-hnswlib
 name         : chroma-hnswlib          
 version      : 0.7.3                   
 description  : Chromas fork of hnswlib 

dependencies
 - numpy *

required by
 - chromadb 0.7.3

**Comment by yufansong** [comment]
Yeah, that works. First `poetry update` then `make build`

**Pull request merged**
