### PR TITLE
fix(frontend): prevent API key from resetting after modal change

### PR DESCRIPTION
**Pull request by tobitege**
This is something I'd like to kindly ask one of the frontend maintainers  to take a look at:
it is sorta annoying, that whenever the Model name is changed that the API key gets cleared.  

I'd see it as a QoL enhancement that as long as the model provider stays the same (like `openrouter/...` or `ollama/...`), the key is kept in place.  
Apparently it is almost impossible to achieve this as e.g. Firefox and Chrome clear the key regardless as soon as one changes more than 1 character (their "Manage passwords" popup appears).  

Maybe this is an intended security feature?

Anyway, I'm at my rope's end with this _thing_, if someone else might want to take it up? 😀

### CODE REVIEW

**Comment by neubig** [comment]
@amanape : is this something you could take a quick look at?

**Comment by amanape** [comment]
@tobitege @neubig Maybe it would be more convenient to prevent clearing the API key for _any_ model change. It would require a very hacky solution to check for model provider. For example, `gpt-3.5-turbo` uses the same API key as `azure/gpt-35-turbo`, but not the same as required by `azure/mistral-large-latest`.

Same goes for lesser used models/providers listed such as `deepinfra/amazon/MistralLite` and `deepinfra/Phind/Phind-CodeLlama-34B-v2`.

Suggested change from:
https://github.com/OpenDevin/OpenDevin/blob/82d4d25b09413c3e2d8463488e61a70103bf51cf/frontend/src/components/modals/settings/SettingsModal.tsx#L68-L76
to:
```ts
 const handleModelChange = (model: string) => { 
   setSettings((prev) => ({ 
     ...prev, 
     LLM_MODEL: model, 
   })); 
 }; 
```

This should allow the user to decide whether they want to change the key.

**Comment by amanape** [comment]
Unless they actually use the same key? I've never actually used model providers such as azure or deepinfra

**Comment by amanape** [comment]
Well, I'm not entirely sure about providers like `deepinfra`, but here is some info if you'd like to go forward with your change:
Changing the handler to something like this should work:
```ts
  const handleModelChange = (model: string) => {
    let newSettings = { ...settings, LLM_MODEL: model };

    if (settings.LLM_MODEL.split("/")[0] !== model.split("/")[0]) {
      newSettings = {
        ...newSettings,
        LLM_API_KEY: localStorage.getItem(`API_KEY_${model}`) || "",
      };
    }

    setSettings((prev) => ({ ...prev, ...newSettings }));
  };
```

Keep in mind the component actually calls `handleModelChange` on every keystroke. So unless the user directly pastes their desired model or selects it from the dropdown, they API key will reset (because the conditional always fails).

To solve this, you can consider changing the underlying autocomplete component logic from:
https://github.com/OpenDevin/OpenDevin/blob/06a6ffcb09e3cff1f1dbd097503344cb801a376b/frontend/src/components/modals/settings/AutocompleteCombobox.tsx#L67-L75

 to something like this:
```tsx
   onInputChange={(val) => { 
       // remove call
   }} 
   isDisabled={disabled} 
   allowsCustomValue={allowCustomValue} 
 > 
   {(item) => ( 
     <AutocompleteItem
           key={item.value}
           onClick={() => onChange(item.value)} // add it here
       >{item.label}</AutocompleteItem> 
   )} 
```

Caution though: I'm not entirely sure but the input may not change now, so you may have to maintain a state of the copy of the input value until the user makes the selection.

If you're still unable, I'll try to fix it up by the end of today or tomorrow (sorry!)

**Comment by tobitege** [comment]
@amanape Thanks so much for taking the time to take a look!
I'm out of my depth here with React, most of the changes clearly come from gpt-o4 🤣 
I think the issue is not the code itself, but how browsers work these days (probably related autoform filling etc).

Let me ask this another way and assume we just forget about this PR ever happened:
could we just skip having an entry field for the key by default and replace it with a button to actually change it?
Doesn't sound ideal, I know. But having to re-enter that key every time is annoying as well. ;)

**Comment by neubig** [comment]
I think preventing clearing of the key for any model change seems like a good solution, and it would be great if you could try a quick fix @amanape !

**Review by amanape — APPROVED** [review]

**Comment by amanape** [comment]
> could we just skip having an entry field for the key by default and replace it with a button to actually change it?
Doesn't sound ideal, I know. But having to re-enter that key every time is annoying as well. ;)

I just saw this message. Do you mean to replace the input with a button? How so?

**Comment by tobitege** [comment]
@amanape great job, thanks for taking care of things! 😃

**Comment by tobitege** [comment]
> I just saw this message. Do you mean to replace the input with a button? How so?

Was thinking of having a 2-step-approach to entering the API key by replacing the key input be replaced by a button.
But with the just made changes, the issue is resolved in my mind. 👍

**Pull request merged**
