### PR TITLE
UI: Remove min width & height for Containers

### PR DESCRIPTION
**Pull request by SmartManoj**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Solves #1745

---

**Give a summary of what the PR does, explaining any non-trivial design decisions**

image

### CODE REVIEW

**Comment by amanape** [comment]
@SmartManoj Please provide a proper summary and details of your change, they don't make much sense. The issue you linked is suggesting two things:
1. Allow the user to horizontally resize the containers
2. (from the comment) Allow the user to resize the terminal container

For the first point, the user could already adjust their size, and in turn, the size of the editor. The terminal was also able to be resized but may require the user attempting once or twice before managing. Why do your changes remove the minimum widths and heights? What problem does this supposed to solve and how does it solve it?

After testing your changes, I can now reduce the size of the chat completely, which is not good UX. What if I want to reset the size to its original width? What is normally done in this situation is implement a show/hide feature like one for the file explorer (via a toggle), which is clearly not the case here.

Another problem is that I can't seem to resize the terminal anymore. My guess is that the terminal hook's logic responsible for resizing the _actual terminal_ depends on the height set of its container, which you removed. And again, the solution in this case would not be to allow the user to resize the height to 0-like pixels, but instead show/hide with a toggle.

**Comment by SmartManoj** [comment]
> I can now reduce the size of the chat completely,

FYI, you can change the size after this state too.  

---

Alternate solutions:
Using buttons:
image

Collapse button (inverted second last button - down arrow to collapse the terminal)
image

**Comment by SmartManoj** [comment]
> My guess is that the terminal hook's logic responsible for resizing the _actual terminal_ depends on the height set of its container, which you removed.

how does horizontal resize work without `min-w`?

**Comment by SmartManoj** [comment]
Forcing the panes with min-height and min-width is a bad UX.

Example: https://youtu.be/47g53m204k4?t=9 @neubig

**Comment by tobitege** [comment]
> Forcing the panes with min-height and min-width is a bad UX.

So is removing them completely without providing a

**Comment by SmartManoj** [comment]
> > What if I want to reset the size to its original width?
> 
> You can change the size after this state too.

@tobitege, Do you have the same problem?

**Comment by tobitege** [comment]
> > > What if I want to reset the size to its original width?
> > 
> > 
> > You can change the size after this state too.
> 
> @tobitege, Do you have the same problem?

I just tried it out and I can freely resize all the panes (only tried Firefox beta) and the "handle bars" stay in view and can still be grabbed (which was my initial concern), so that's good.

What @amanape was talking about is, I think, that there is no toggle between "maximized" and "default" size.
Like you suggested with the buttons from VSCode.

I'll refer to him to make the final review if we're ok with this PR as it is.

**Comment by rbren** [comment]
We're doing some cleanup of PRs, and are going to close this one for now.

**Pull request closed without merging**
