### PR TITLE
Fix(test,CI): runtime build tests

### PR DESCRIPTION
**Pull request by xingyaoww**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

@tobitege find that `test_runtime_build.py` failed to run, yet all those CI passed.

---

**Give a summary of what the PR does, explaining any non-trivial design decisions**

- Fix `test_runtime_build.py` so it matches the current implementation.
- Update `run-unit-tests.yml` so `test_runtime_build.py` is included in the testing.

---
**Other references**

### CODE REVIEW

**Review by tobitege — APPROVED** [review]
Let's do it :)

**Comment by neubig** [comment]
Hey @xingyaoww , did you confirm that the tests in `test_sandbox.py` and `test_runtime.py` run? I fixed some bugs in the jupyter test, but they don't seem to be fixe din this PR...

**Comment by xingyaoww** [comment]
Yeah... I think after moving the `sandbox`-related test to `test_sanbdox`, these tests passed the CI?
https://github.com/OpenDevin/OpenDevin/actions/runs/10112691054/job/27968196884

**Comment by neubig** [comment]
Actually `test_sandbox` is not tested by CI:
https://github.com/OpenDevin/OpenDevin/blob/1f6e86c932e16914b94a673f22fc791cd8d4d58c/.github/workflows/run-unit-tests.yml#L128

You can run them locally by doing
```
poetry run pytest ./tests/unit/test_sandbox.py
poetry run pytest ./tests/unit/test_runtime.py
```

**Comment by xingyaoww** [comment]
@neubig We have dedicated workflow `test_sandbox` and `test_runtime` actually: because running them together with unit tests typically has some docker related issues

https://github.com/OpenDevin/OpenDevin/blob/1f6e86c932e16914b94a673f22fc791cd8d4d58c/.github/workflows/ghcr.yml#L80

https://github.com/OpenDevin/OpenDevin/blob/1f6e86c932e16914b94a673f22fc791cd8d4d58c/.github/workflows/ghcr-runtime.yml#L96

**Comment by neubig** [comment]
Ohh, I see! My bad.

**Pull request merged**
