### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by PierrunoYT**
Updated Readme for Windows 11 with WSL Ubuntu

### CODE REVIEW

**Comment by PierrunoYT** [comment]
Please include this step. I forgot it docker pull ghcr.io/opendevin/sandbox:v0.1

**Comment by PierrunoYT** [comment]
Please double check it. I only added the Installation steps and nothing more. I think I forgot something.

**Comment by rbren** [comment]
We don't want to put WSL instructions in here. It's outside the scope of this project

**Comment by PierrunoYT** [comment]
So how would people know how to install it correctly? I mean right now the readme is not what it should be. There should should be a guide how to install it which I provided right here.

**Comment by rbren** [comment]
I added a requirement for WSL and a link to the installation instructions

**Pull request closed without merging**
