### PR TITLE
fix: use 127.0.0.1 for api proxy

### PR DESCRIPTION
**Pull request by xcodebuild**
Fix https://github.com/OpenDevin/OpenDevin/issues/508

### CODE REVIEW

**Comment by rbren** [comment]
Do we need this in addition to https://github.com/OpenDevin/OpenDevin/pull/534

**Comment by neubig** [comment]
Yeah, this is probably preferable if it works! I can't test it now

**Comment by ChecksumDev** [comment]
Huh, I would expect `localhost` to be more robust as this change would likely break on an IPv6 only system, because `localhost` can also resolve to `::1`.

**Comment by xcodebuild** [comment]
> Huh, I would expect `localhost` to be more robust as this change would likely break on an IPv6 only system, because `localhost` can also resolve to `::1`.

`vite` only works in development mode, is there a need to develop under an IPv6 only system? Even in this case, we can still specify the IP using `BACKEND_HOST`."

**Comment by adyah** [comment]
I made the change from `localhost` to `127.0.0.1` but the ws error still persists.

**Comment by xcodebuild** [comment]
> I made the change from `localhost` to `127.0.0.1` but the ws error still persists. @adyah 

Could you provide more information?

For me, `fnm use 18` to switch to node `v18.17.0` 
- `localhost:3000` in `vite.config.ts`, get 500 error
image

Errors in vite logs:
```
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
1:38:11 PM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
1:38:11 PM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
1:38:11 PM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
1:38:11 PM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
```


- `127.0.0.1:3000` in `vite.config.ts`, works well
image

**Comment by adyah** [comment]
> Could you provide more information? @xcodebuild 

Screenshot 2024-04-02 at 12 08 56 PM

**Comment by xcodebuild** [comment]
Expected `vite` error is `Error: connect ECONNREFUSED ::1:3000` but yours is `connect ECONNREFUSED 127.0.0.1:3000`. Are you sure the backend has already started at `http://127.0.0.1:3000`?

**Comment by adyah** [comment]
`make run` for some reason is not starting the backend.
starting backend seperately solved the issue. Thanks for your support.

**Pull request merged**
