### PR TITLE
Make the sandbox Python runtime completely transparent

### PR DESCRIPTION
**Pull request by Shimada666**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
Right now,`python` points to `/opendevin/miniforge3/bin/python`, which is not suitable. Users should use a clean Python interpreter that is separate from the python used by the opendevin runtime.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**
We should make the OpenDevIn Python runtime completely transparent to users. Users should continue using whatever interpreter `python` points to, like `/usr/bin/python`, instead of `/opendevin/miniforge3/bin/python`.

**Other references**

### CODE REVIEW

**Review by xingyaoww — APPROVED** [review]
LGTM!

**Review by iFurySt — APPROVED** [review]

**Comment by tobitege** [comment]
@Shimada666 error in CI here:
https://github.com/OpenDevin/OpenDevin/actions/runs/9801641111/job/27065607085#step:7:523

`FAILED tests/unit/test_sandbox.py::test_agnostic_sandbox_jupyter_agentskills_fileop_pwd - docker.errors.BuildError: The command '/bin/sh -c echo "" > /opendevin/bash.bashrcRUN { test -d /opendevin/miniforge3 && echo "/opendevin/miniforge3 already in base image"; } || {     wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" &&     bash Miniforge3-$(uname)-$(uname -m).sh -b -p /opendevin/miniforge3 &&     bash -c ". /opendevin/miniforge3/etc/profile.d/conda.sh && conda config --set changeps1 False && conda config --append channels conda-forge" &&' returned a non-zero code: 2`

**Comment by tobitege** [comment]
Repeated run shows the same error, just fyi.

**Comment by Shimada666** [comment]
@tobitege 
Thank you! I have noticed that `test_ipython_module` succeeded under `codeactagent` but failed under `codeactsweagent`. I don't have much expertise about `codeactsweagent`, so I am asking @xingyaoww  to help me solve this issue. It should be working fine now!

**Comment by Shimada666** [comment]
@xingyaoww @tobitege 
Hi, I just fixed the errors in the agnostic image build script.. Could you help me rerun the CI tests? Thanks!

**Comment by tobitege** [comment]
> @xingyaoww @tobitege Hi, I just fixed the errors in the agnostic image build script.. Could you help me rerun the CI tests? Thanks!

It's rolling now 😂

**Comment by Shimada666** [comment]
@iFurySt  Yes. please merge this PR, thanks!

**Pull request merged**
