### PR TITLE
fix: Update requirements.txt with google-generativai

### LINKED ISSUE #285: Additional install required for Gemini
**Describe the bug**
Setting environment to use Gemini Pro results in error unless an additional package is installed.  I'm opening the issue cause not sure how the maintainers want it handled.  Should we add to `requirements.txt` or add instructions to `README`  to check LiteLLM for model specific install ?

**Steps to Reproduce**
```
export LLM_MODEL=gemini/gemini-pro
export LLM_API_KEY=....GEMINI_API_KEY...
python opendevin/main.py -d ./workspace/ -i 100 -t "Write a bash script that prints hello world"
```

**Expected behavior**
Runs normally

**Actual behavior**
Requires additional pip install

**Additional context**

### PR DESCRIPTION
**Pull request by jojeyh**
Resolves #285 

The package `google-generativeai` was installed using `venv` and `requirements.txt` updated with 
```
pip freeze > requirements.txt
```

This creates versioning numbers for all packages used which were not included before.

### CODE REVIEW

**Comment by rbren** [comment]
@jojeyh I don't think we want to go so far as a `pip freeze`, but it would definitely be nice to have a more reproducible build.

I wonder if a Pipfile is the right way to go? https://pipenv.pypa.io/en/latest/pipfile.html

**Comment by jojeyh** [comment]
Sounds good to me.  I'll try to get it working.  At first glance it looks like pipenv doesn't play nice if there are multiple installations of python on a system (I use Ubuntu), but there's not really a lot of good options for python package management in general.

**Comment by jojeyh** [comment]
@rbren Now works with `pipenv` , also updated and reordered the README a little for better readability

**Review by rbren — APPROVED** [review]

**Comment by rbren** [comment]
LGTM! You just need to resolve the conflicts--looks like maybe someone added a line to requirements.txt you'll need to incorporate

**Comment by jojeyh** [comment]
@rbren Resolved

**Comment by rbren** [comment]
Thanks!

**Pull request merged**
