### PR TITLE
Simply Jupyter execution via heredoc

### PR DESCRIPTION
**Pull request by xingyaoww**
This is part of modification in https://github.com/OpenDevin/OpenDevin/pull/1468. Trying to get in one-by-one to reduce the review burden for https://github.com/OpenDevin/OpenDevin/pull/1468 (which is a gigantic PR)

### CODE REVIEW

**Review by neubig — APPROVED** [review]
I think this is probably OK, but just a comment for completeness:

This is assuming that `/tmp` is the temp directory, which is true in many environments but not all. It might be better to use the Python `tempfile` package to get a temporary file or directory: https://docs.python.org/3/library/tempfile.html

If we can assume that our sandbox will always have `/tmp` it's probably OK though.

**Comment by xingyaoww** [comment]
@neubig added a line in SSHBox to `mkdir /tmp` and an integration test to ensure Jupyter execution is working.

**Comment by li-boxuan** [comment]
Somehow an integration test failed after the merge... I'll take a look

**Comment by li-boxuan** [comment]
Aha I see, it's due to the newly added iteration reminder config after the merge.

**Pull request merged**
