### PR TITLE
Fix issue #2029: Replace defaultProps with JavaScript default parameters

### PR DESCRIPTION
**Pull request by prithvi2226**
This pull request addresses issue #2029, which involves deprecating the use of defaultProps in favor of JavaScript default parameters in function components. This change aligns with React's recent update (version 18.3.0) that issues console warnings for using defaultProps in function components, as it is now deprecated. Successfuly replaced the usage of `defaultProps` with JavaScript default parameters in the given components.

`basemodal.tsx`
`AgentControlBar.tsx`
`ChatInput.tsx`
`ExplorerTree.tsx`
`TreeNode.tsx `
`IconButton.tsx `
`HeaderContent.tsx `
`AutocompleteCombobox.tsx`

**Testing**
- Verified that the components still function as expected with the default values.
- Ensured that there are no more deprecation warnings in the console when running the application with these components.

**Additional Notes:**
```
This change is part of a larger effort to modernize the codebase and adhere to the latest React best practices. 
No functionality has been altered; only the method of setting default prop values has been updated.
```

### CODE REVIEW

**Review by amanape — CHANGES_REQUESTED** [review]
Remove all the comments that you've replaced the `defaultProps` with

**Comment by amanape** [comment]
Also, lint test is failing. You should update the ESLint rules to ignore the `defaultProps` warning thrown by ESLint

**Comment by prithvi2226** [comment]
I have made the required changes in the commit:
```
Removed all the comments (Removed the defaultProps block comment),
and updated the ESLint rules to ignore the defaultProps warning thrown by ESLint.
```

**Comment by amanape** [comment]
Linting failed once more. Run the lint command with the --fix arg to fix any remaining issues before pushing. Alternatively, you can get the ESLint plugin by dbaumer and configure a keyboard shortcut for development if you're going to work on the frontend more often.

Other than that, looks good!

**Review by amanape — APPROVED** [review]

**Pull request merged**
