### PR TITLE
Pull Request Agent (plus, Microagent workflows)

### LINKED ISSUE #1281: [Feature] "open pull request" capability
**What problem or use case are you trying to solve?**

We would like to solve github issues using OpenDevin: https://github.com/OpenDevin/OpenDevin/issues/1067

OpenDevin can get most of the way there, but when it tries to "git push" it will not work, because it does not have appropriate permissions to push to github and send a PR.

**Describe the UX of the solution you'd like**

To fix this, I think we should probably add an `OpenPullRequest` action to our agents.

1. In the case where the user has not configured github credentials, this will trigger a message to the user that in order for the agent to proceed, they should enter their github credentials or cancel.
2. In the case where the user has configured github credentials, this will send a PR to a branch, and open up the github PR page for the user to review the PR before they actually click the "submit pull request" button themselves.

**Describe alternatives you've considered**

Another althernative is to let OpenDevin actually do the PR itself, but this is too risky.

### PR DESCRIPTION
**Pull request by rbren**
This proposes adding a new PullRequestAgent, which can be pointed at a dirty git repo and open up a PR.

It also proposes a new `workflow` key for microagents, which allow microagents to step through a series of tasks. Each task can be delegated out to another agent for any number of steps.

It also includes changes from https://github.com/OpenDevin/OpenDevin/pull/1652 which allows setting env vars like GITHUB_TOKEN

NOTE by @neubig : fixes #1281

### CODE REVIEW

**Comment by PierrunoYT** [comment]
Do we need this with the lastest CodeAct 1.3 Agent?

**Comment by neubig** [comment]
@rbren WDYT about this? Are we going to continue working on this or are we OK with CodeAct's ability to send PRs for now?

**Comment by li-boxuan** [comment]
IMO we should let CodeActAgent delegate to Pull Request Agent as creating a github pr is a very domain-specific task

**Comment by neubig** [comment]
@rbren are we still planning this or shall we close it for now?

**Comment by xingyaoww** [comment]
Let's close it for now - feel free to re-open if we want to further develop.

**Pull request closed without merging**
