### PR TITLE
Add LightCodeActAgent with simplified prompt and removed browsing

### PR DESCRIPTION
**Pull request by isavita**
# Description
This PR introduces LightCodeActAgent, a simplified version of CodeActAgent. 
It features a simpler prompt and has removed browsing functionality to support less capable LLMs and local deployment.

## Testing with different LLMs
- [ ] Test with `phi3:14b`.
  <details>
  <summary>Create a UUID Generator Web Page</summary>

  ```text
  Set up a basic Flask application that serves a simple web page with a button. When the button is clicked, it should generate a random UUID and display it on the page.
  ```
  </details>

- [ ] Test with `llama3:8b`.
- [ ] Try some benchmark.

### CODE REVIEW

**Review by li-boxuan — COMMENTED** [review]
I haven't read your code yet, but from the PR title it seems this agent is essentially a subset of CodeActAgent? If that's the case, I don't think we should create a new agent. We should think about how we could make certain prompts & plugins optional for CodeActAgent.

**Comment by isavita** [comment]
@li-boxuan Yes. The starting point was a copy and paste of the CodeActAgent. However, I am currently trying it and changing the prompting and adding some additional checks. I am not sure if I will be able to make it work with smaller LLMs like phi3:14b and llama3:8b, which I am currently testing. If I manage to make it work on phi3:14b, I will move it out of draft and will add what the differences are if it is more than just the prompts and reduced actions.

**Comment by li-boxuan** [comment]
Copying & pasting just for testing purpose sounds fine! Also excited to see if anything (even trivial tasks) could work with small models.

**Comment by enyst** [comment]
Interesting! CodeAct seems good grounds for experimentation. ❤️

**Comment by frankxu2004** [comment]
Is this superseded by #2105 ? Just curious

**Comment by isavita** [comment]
@frankxu2004 Yes, although this one has a smaller initial prompt for smaller models. I haven’t found a single model under 30B that can make a simple JSON API. I am waiting to get access to Codestal from Mistral API. I have tried Ollama version, but it seems something is wrong with the Q4_0 version.

**Comment by neubig** [comment]
Nice work @isavita , I'm interested in the results of your tests!

**Comment by isavita** [comment]
@neubig Here some of my results, but I am still waiting to have `litellm` integrated **codestral** to test it.
<details>
  <summary>Model Testing Results</summary>
  <details>
    <summary>Task Descriptions</summary>
    <p><strong>Task 1:</strong> Write a Python script that prints all numbers divisible by 7 from 1 to 100.</p>
    <p><strong>Task 2:</strong> Write a simple JSON API in Python that has one GET endpoint. Every time it is called, it should return a random UUID.</p>
    <p><strong>Task 3:</strong> Develop a simple Snake game in Python that runs in a terminal window, allowing control of the snake using arrow keys. The game should end if the snake hits itself or the wall.</p>
  </details>
  <br>
  <table>
    <tr>
      <th>Model</th>
      <th>Task 1</th>
      <th>Task 2</th>
      <th>Task 3</th>
    </tr>
    <tr>
      <td>OpenHermes-2.5-Mistral-7B</td>
      <td>Failed</td>
      <td>Failed</td>
      <td>Failed</td>
    </tr>
    <tr>
      <td>llama3:8b</td>
      <td>Failed</td>
      <td>Failed</td>
      <td>Failed</td>
    </tr>
    <tr>
      <td>llama3:8b-instruct-q5_K_M</td>
      <td>Failed</td>
      <td>Failed</td>
      <td>Failed</td>
    </tr>
    <tr>
      <td>phi3:14b</td>
      <td>Failed</td>
      <td>Failed</td>
      <td>Failed</td>
    </tr>
    <tr>
      <td>codestral:22b-v0.1-q4_K_M</td>
      <td>Not evaluated yet</td>
      <td>Not evaluated yet</td>
      <td>Not evaluated yet</td>
    </tr>
  </table>
  <p><strong>Comments:</strong></p>
  <p>None of the models were able to perform all tasks successfully. OpenHermes-2.5-Mistral-7B, llama3:8b, and llama3:8b-instruct-q5_K_M struggled significantly, particularly llama3 models, which seemed to have a too small context window and were generally too weak in coding tasks. Phi3:14b was the closest to performing well but still failed due to mistakes such as writing to a file incorrectly, improper formatting, or encountering problems when installing Flask. I also tried codestral:22b-v0.1-q4_K_M, but it was very slow on my machine to run it. Now I am waiting for litellm to integrate the new API endpoint from Mistral and will try it.</p>
</details>

**Comment by neubig** [comment]
Hi @isavita ! I'm wondering what (if anything) we should do with this. We could run some tests on SWE-Bench Lite if that'd be helpful.

**Comment by isavita** [comment]
@neubig I closed the PR. I didn't see any noticeable difference with the small local models. It seems they are still too incapable.

**Pull request closed without merging**
