### PR TITLE
Improve browsing agent prompts, allowing agent to properly finish when done

### PR DESCRIPTION
**Pull request by frankxu2004**
@li-boxuan This should make it a bit better - although the gpt4o is quite random some time...

### CODE REVIEW

**Comment by li-boxuan** [comment]
Likely unrelated to this PR, but just want to report that I've hit this issue pretty consistently:

```
21:06:47 - opendevin:INFO: browser_env.py:38 - Starting browser env...
21:06:57 - opendevin:INFO: agent_controller.py:112 - AgentController task was cancelled
ERROR:root:  File "/Users/liboxuan/workspace/OpenDevin/./opendevin/core/main.py", line 127, in <module>
    asyncio.run(main())
  File "/opt/anaconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/liboxuan/workspace/OpenDevin/./opendevin/core/main.py", line 92, in main
    runtime = ServerRuntime(event_stream=event_stream, sandbox=sandbox)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liboxuan/workspace/OpenDevin/opendevin/runtime/server/runtime.py", line 35, in __init__
    super().__init__(event_stream, sid, sandbox)
  File "/Users/liboxuan/workspace/OpenDevin/opendevin/runtime/runtime.py", line 74, in __init__
    self.browser = BrowserEnv()
                   ^^^^^^^^^^^^
  File "/Users/liboxuan/workspace/OpenDevin/opendevin/runtime/browser/browser_env.py", line 41, in __init__
    raise BrowserException('Failed to start browser environment.')

ERROR:root:<class 'opendevin.runtime.browser.browser_env.BrowserException'>: Failed to start browser environment.
21:06:57 - opendevin:INFO: browser_env.py:53 - Browser env started.
```

**Review by li-boxuan — APPROVED** [review]
Agree that gpt-4o seems pretty unstable... but it seems I have higher chance of finishing the task with this PR.

**Comment by li-boxuan** [comment]
I'd like to merge this PR pretty soon and then work on writing a test for BrowserAgent... if anyone intends to review please comment here

**Comment by frankxu2004** [comment]
@li-boxuan Thanks! Giving the agent a bit more turns might help, but each try is not exactly the same. I think that maybe a simpler task might be more stable. For example I have always had success with "tell me the trending project on GitHub". 

I also updated the PR with ability to send messages in the front end to let the user know what's happening under the hood, and a small fix in handling parsing errors in case the user is using very weak LLMs.

**Comment by li-boxuan** [comment]
https://github.com/OpenDevin/OpenDevin/pull/2031 increased overall project coverage by 1.31%...  it would increase more once we start using the prompts that have been checked-in but not in use yet.

**Pull request merged**
