### PR TITLE
Bugfix by added config to disable plugin initialization for Persistent sandbox

### PR DESCRIPTION
**Pull request by SmartManoj**
For persistent sandboxes, need to run `source bashrc`.
As `source ~/.bashrc` was removed in #2172, refactored the logic to execute `source ~/.bashrc`.
Solves current bug due to the removal,  `-bash: execute_cli: command not found` error. 
And with #2177, it won't cause the #2178 problem for persistent sandboxes.

### CODE REVIEW

**Comment by tobitege** [comment]
@SmartManoj 
Isn't it possible that the .bashrc contains a (yet unidentified) command that could cause a user interaction and "cause" the hanging still, regardless of where the "source" is called?
I'm not a Linux guy, so had to ask my buddy WizardLM2 and got this as a reply, if that makes sense:
```def start_ssh_session(self):
    self.__ssh_login()

    # Instead of sourcing .bashrc directly, you can selectively execute non-interactive parts of it.
    # This is a workaround to prevent hanging due to interactive commands in .bashrc.
    try:
        self.ssh.sendline("source /etc/profile.d/*.sh")  # Source system-wide profiles
        self.ssh.prompt()
        self.ssh.sendline("if [ -z \"$PS1\" ]; then . ~/.bashrc; fi")  # Condition to avoid interactive parts
        self.ssh.prompt()
    except pxssh.ExceptionPxssh as e:
        logger.exception('Failed to source .bashrc: %s', e)
        raise e

    # Fix: https://github.com/pexpect/pexpect/issues/669
    self.ssh.sendline("bind 'set enable-bracketed-paste off'")
    self.ssh.prompt()
    # cd to workspace
    self.ssh.sendline(f'cd {self.sandbox_workspace_dir}')
    self.ssh.prompt()
```
Further annotation was:
"This modification attempts to source only the parts of .bashrc that are safe for non-interactive sessions. It checks for the presence of the PS1 variable, which is typically set in interactive shells, to decide whether to source .bashrc."

**Comment by SmartManoj** [comment]
This may be a solution for #2178

---

The current change concerns calling `source ~/.bashrc` when initializing the plugin.

**Comment by tobitege** [comment]
> The current change concerns calling `source ~/.bashrc` when initializing the plugin.

Right, it's hard to keep track with the issues. :)

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/pull/2162

**Comment by ryanhoangt** [comment]
Just tried it locally and I didn't get `execute_cli command not found` anymore. Looks good!

**Review by li-boxuan — COMMENTED** [review]
I am a bit lost in this feature so I'll leave the review burden to Robert or anyone else 😄 . I just have one request:

once all issues with persistent sandbox are resolved, could you please add it to `run-integration-tests.yml`? You could add a new line to `matrix`. We now have three different kinds of sandboxes, and you could add a new dimension - persistent type.

**Comment by rbren** [comment]
@SmartManoj I still don't understand how/why this works. Does the user need to change the value of `init_sandbox_plugins` every time they start the app, depending on whether there's an existing sandbox?

Why is `init_sandbox_plugins` in the top-level configuration, instead of being handled internally like it was before?

**Comment by SmartManoj** [comment]
Scenarios
1. manual trigger when user switching from another agent to codeact act agent 
2. when new plugins are added 
3. for quick debug

**Review by rbren — APPROVED** [review]

**Comment by SmartManoj** [comment]
This PR brings back the old behavior (always initialize). If one wants to disable the plugin initialization, they can set `init_sandbox_plugins` to 0.

**Pull request merged**
