### PR TITLE
fix: enable custom model.

### PR DESCRIPTION
**Pull request by iFurySt**
image

we only support the selectable items right now. but we need to support the user inputting the model like this:

image

### CODE REVIEW

**Review by neubig — APPROVED** [review]
Looks good, thanks!

**Comment by lowlyocean** [comment]
Just tried this. It "worked" at first, by showing the Model as the one I entered into config.toml: "ollama/deepseek-coder:instruct"

However, I cleared the Model in the UI by accident, and now there's no way to get it working again. The config.toml still says "ollama/deepseek-coder:instruct" but I can't enter this manually into the UI (and it doesn't get recognized from the toml)

**Comment by enyst** [comment]
@lowlyocean does it work again if you close both backend and frontend, and restart?

**Comment by lowlyocean** [comment]
Unfortunately not. I also cleared Local Storage, which makes it at least display the expected model at least - but the backend still thinks gpt3 model is selected

**Comment by zhonggegege** [comment]
make build failed:
(opendevin) agent@DESKTOP-OJHF2BM:~/OpenDevin$ make build
Building project...
Checking Python installation...
Python 3 is already installed. Version: 3.11.8
Checking npm installation...
npm is already installed. Version: 10.5.0
Checking Docker installation...
Docker is already installed. Version: 20.10.12,
Installing Python dependencies...
Poetry is already installed.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: opendevin (0.1.0)
Activating Poetry shell...
Setting up frontend environment...
Detect Node.js version...
Current Node.js version is 21.7.1, corepack is supported.
Installing frontend dependencies with npm...
npm notice 
npm notice New patch version of npm available! 10.5.0 -> 10.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.1
npm notice Run npm install -g npm@10.5.1 to update!
npm notice 
npm ERR! Cannot read properties of null (reading 'edgesOut')

npm ERR! A complete log of this run can be found in: /home/agent/.npm/_logs/2024-04-07T00_44_28_358Z-debug-0.log
make: *** [Makefile:38: build] Error 1

log-------------------------------------------------------------------------------------
138 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
138 verbose stack     at #loadPeerSet (/home/agent/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1313:38)
138 verbose stack     at async #buildDepStep (/home/agent/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:924:11)
138 verbose stack     at async Arborist.buildIdealTree (/home/agent/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
138 verbose stack     at async Promise.all (index 1)
138 verbose stack     at async Arborist.reify (/home/agent/.nvm/versions/node/v21.7.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
138 verbose stack     at async Install.exec (/home/agent/.nvm/versions/node/v21.7.1/lib/node_modules/npm/lib/commands/install.js:153:5)
138 verbose stack     at async module.exports (/home/agent/.nvm/versions/node/v21.7.1/lib/node_modules/npm/lib/cli-entry.js:61:5)
139 verbose cwd /home/agent/OpenDevin/frontend
140 verbose Linux 5.10.16.3-microsoft-standard-WSL2
141 verbose node v21.7.1
142 verbose npm  v10.5.0
143 error Cannot read properties of null (reading 'edgesOut')
144 verbose exit 1
145 timing npm Completed in 17512ms
146 verbose unfinished npm timer reify 1712450668585
147 verbose unfinished npm timer reify:loadTrees 1712450668625
148 verbose unfinished npm timer idealTree:buildDeps 1712450672414
149 verbose unfinished npm timer idealTree:node_modules/.pnpm/@monaco-editor+react@4.6.0_monaco-editor@0.47.0_react-dom@18.2.0_react@18.2.0/node_modules/@monaco-editor/react 1712450679767
150 verbose code 1
151 error A complete log of this run can be found in: /home/agent/.npm/_logs/2024-04-07T00_44_28_358Z-debug-0.log

**Comment by enyst** [comment]
@zhonggegege Inside the opendevin project directory there's frontend and in it, node_modules. Please delete node_modules, then try again. This is unrelated to this PR, it's more that the frontend needs to be rebuilt from scratch (ish).

If it still doesn't work, please make a new issue.

**Pull request merged**
