### PR TITLE
Fix browser env leak after resetting agent

### LINKED ISSUE #1528: [Bug]: Memory leak when switching/initializing agents, probably due to Browser
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

If you open the settings modal repeatedly, and switch your settings up to cause a re-init of the agent, the server slowly consumes more and more memory

I had to do this ~50 times before my machine became unresponsive.

When I finally quit, I get a bunch of logs like this:
```bash
11:47:33 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
11:47:33 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
11:47:33 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
11:47:33 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
11:47:34 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
INFO:     Shutting down
11:47:34 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
INFO:     Waiting for background tasks to complete. (CTRL+C to force quit)
11:47:34 - opendevin:INFO: browser_env.py:69 - Browser env process interrupted by user.
```

### Current Version

```bash
On main


commit ce7c7eaae45ce18a13081e63d013a7123bbe95d3 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Thu May 2 11:44:54 2024 -0400

    Refactor actions and observations (#1479)
```
```


### Installation and Configuration

```bash
Running in dev mode
```

### Model and Agent

Various models and agents as I switched around

### Reproduction Steps

1. Fire up the UI
2. Open settings modal
3. Change something and save
4. Repeat ~50 times
5. Your machine will grind to a halt

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by frankxu2004**
Fixes #1528

### CODE REVIEW

**Comment by rbren** [comment]
@frankxu2004 you can probably move this into agent_controller.close() now

**Comment by rbren** [comment]
Looking good! I think we just need to add a `close()` call into agent_controller

**Comment by frankxu2004** [comment]
Added and tested that now after agent re-init  (e.g. change config), the browser process will always shutdown correctly. Should be ready @rbren

**Review by rbren — APPROVED** [review]

**Comment by rbren** [comment]
Thanks Frank!

**Pull request merged**
