### PR TITLE
Add prototype OpenDevin frontend

### PR DESCRIPTION
**Pull request by neubig**
This PR adds a simple prototype frontend in React that is similar to the Devin Frontend. It looks like this, with a chat interface on the left, and two tabs on the right. Shell

Screenshot 2024-03-15 at 8 22 05 PM

and Planner

Screenshot 2024-03-15 at 8 24 03 PM

This is just to bootstrap to have something, and the actual functionality is not implemented yet. In terms of next steps, this could include implementing a backend service to send commands to the command line, and some prompts to make calls to a hosted language model API.

Any comments are welcome!

### CODE REVIEW

**Comment by z-zeechung** [comment]
do we use py for backend and ts for frontend, or use ts for both backend and frontend

**Comment by neubig** [comment]
I'd probably suggest Python for the backend to make it easy to implement for machine learning people

**Comment by xiangyue9607** [comment]
do we want to add other tabs like browser and code editor in the demo?

**Comment by neubig** [comment]
@xiangyue9607 probably, but I didn't have an example of what they look like so I left them out for now. They're pretty easy to add later though.

**Comment by z-zeechung** [comment]
impressive ui ;)

**Comment by geekan** [comment]
Any good ideas for the version management part (scrollbar)?

**Comment by AbhisekOmkar** [comment]
it looks good

**Comment by AbhisekOmkar** [comment]
we need total for sections 
1 Terminal 
2 Code editor 
3 Browser 
4 chat interface

**Comment by xcodebuild** [comment]
Awesome work, we might consider import some component libraries to reduce development time and achieve better presentation.

For instance,
- `antd` for foundational components such as Tabs and Button
- `ChatUI` for implementing chat interface
- `@monaco-editor/react` for code editor

**Pull request merged**
