### PR TITLE
[doc] add README-zh.md

### PR DESCRIPTION
**Pull request by mahone3297**

### CODE REVIEW

**Comment by Umpire2018** [comment]
Note: Need to update with main.

**Comment by mahone3297** [comment]
@Umpire2018 I have updated with the main branch, pls review.

**Comment by Umpire2018** [comment]
LGTM.

**Comment by yimothysu** [comment]
This looks good but I have a concern about maintenance. Whenever we update the English README, we would have to update the Chinese README to match. This can be an issue if maintainers don't know Chinese.

**Comment by rbren** [comment]
I share @yimothysu's concern--I was hoping to take another pass at the README soon.

Maybe we should put a warning at the top saying something like
> WARNING: This README may be out of date. README.md should be considered the source of truth. If you notice differences, please open a pull request to update this README

We should also probably put it in a subdirectory, so that the root directory doesn't get clogged with different languages

**Comment by mahone3297** [comment]
If you are ok with it, I can put it into the docs folder.

**Comment by rbren** [comment]
@mahone3297 docs folder sgtm!

**Comment by mahone3297** [comment]
I have put the `README-zh.md` into the docs folder and put a warning at the top of the file.

**Review by yimothysu — APPROVED** [review]

**Comment by rbren** [comment]
Thank you!

**Pull request merged**
