### PR TITLE
Use python3.11 as default

### PR DESCRIPTION
**Pull request by SmartManoj**
Will use python3.11 as default for now as there are [no wheels for chroma-hnswlib](https://pypi.org/project/chroma-hnswlib/#files) for 3.12

[When should you upgrade to Python 3.12?](https://pythonspeed.com/articles/upgrade-python-3.12/)

Solves #879

### CODE REVIEW

**Comment by lowlyocean** [comment]
This change also helps for someone using Ubuntu 22.04 within WSL. In that environment, python 3.10 is the system default and you have to manually install python3.11

If we merge this PR, then theer's no need to prefix `make build` with `POETRY_VIRTUALENVS_PREFER_ACTIVE_PYTHON=true` as mentioned https://github.com/python-poetry/poetry/issues/7158#issuecomment-1342197929

**Comment by rbren** [comment]
I looks like 3.12 support is trickling through the dependency stream. onnxruntime just added support, which should get pulled in by chromadb

https://github.com/microsoft/onnxruntime/issues/17842

In the meantime, maybe we can adjust the Makefile to ensure that windows users are using exactly 3.11? That way Linux users don't have to downgrade

**Comment by SmartManoj** [comment]
> just added

They did Feb 10 itself (2 months over)
https://github.com/microsoft/onnxruntime/issues/17842#issuecomment-1936484800

**Comment by rbren** [comment]
Actually it looks like Chroma did too? https://github.com/chroma-core/chroma/pull/1715

There's been a release since that merge too, 0.4.24 on 2/27

**Comment by rbren** [comment]
Maybe we need to open an issue here? https://github.com/chroma-core/hnswlib

Regardless--rather than downgrading to 3.11 for everyone, if we want to make a change here we should just downgrade for windows users. Shouldn't bee too hard to [add here](https://github.com/OpenDevin/OpenDevin/blob/9fd95cc35fb1cb05ee72412b6188debda44d25d5/Makefile#L38)

OOC--does this affect WSL users?

**Comment by SmartManoj** [comment]
FYI, the OS in #879 is Mac.

**Comment by rbren** [comment]
Yeah seeing that now. We also have https://github.com/OpenDevin/OpenDevin/issues/1007

Seems like maybe we do need this...

**Review by rbren — APPROVED** [review]

**Comment by rbren** [comment]
Let's get this in. If it creates problems, it'll just be for devs at this point 😄

**Comment by rbren** [comment]
Kept waiting for the tests to pass and realized you removed 3.12 😂 

Removed the requirement for those

**Pull request merged**
