### PR TITLE
feat(frontend): Add Typing Indicator for Agent Response using Tailwind CSS

### PR DESCRIPTION
**Pull request by PierrunoYT**
## PR Summary

**feat(frontend): Implement Animated Typing Indicator for Agent Responses**

### Problem Statement and Solution

This PR addresses the need for visual feedback during agent response generation, enhancing user experience in the chat interface. It implements an animated three-dot typing indicator that appears when the agent is processing user input and generating a response.

Resolves: [Issue #1787 - Display a loading indicator in the chat interface when waiting for a response from OpenDevin](https://github.com/OpenDevin/OpenDevin/issues/1787)

### Key Implementation Details

1. **New Component**: Introduced a `TypingIndicator` component (`frontend/src/components/chat/TypingIndicator.tsx`).
2. **Styling**: Utilized Tailwind CSS for efficient, inline styling of the typing indicator.
3. **Integration**: Updated `ChatInterface.tsx` to incorporate the `TypingIndicator` component, triggered when `AgentState` is `RUNNING`.

### Design Decisions

- **Tailwind CSS**: Chosen for its utility-first approach, allowing for rapid styling and easy maintenance directly within the component file.
- **Conditional Rendering**: The typing indicator is displayed only when the agent is actively processing, ensuring a clean interface at other times.
- **Accessibility**: Ensured the animation is subtle to avoid distracting users while still providing clear visual feedback.

https://github.com/OpenDevin/OpenDevin/assets/95778421/756c1f3a-8420-4c8d-b909-5a48898c9b21

### CODE REVIEW

**Review by amanape — COMMENTED** [review]
Very nice. But you are mixing module css styles with TailwindCSS; try creating the animations with TailwindCSS instead, maybe with [keyframes](https://tailwindcss.com/docs/animation)

**Comment by tobitege** [comment]
> Very nice. But you are mixing module css styles with TailwindCSS; try creating the animations with TailwindCSS instead, maybe with [keyframes](https://tailwindcss.com/docs/animation)

Hmm you're asking a lot from an old man here 🤣 
I'll look into it now 👍

**Comment by tobitege** [comment]
phew... had to fix a self-made error but should be good to go now 😔

**Review by iFurySt — APPROVED** [review]

**Comment by iFurySt** [comment]
LGTM. Thanks!

**Pull request merged**
