### PR TITLE
feat: update opendevin logo 

### PR DESCRIPTION
**Pull request by huybery**
Optimized the logo to make it simpler and changed it to png format to keep the background transparent.

### CODE REVIEW

**Comment by rbren** [comment]
Love it! The `open` text looks a little off to me though...

**Comment by huybery** [comment]
I can remove it!

**Comment by huybery** [comment]
@rbren how about now?

**Comment by rbren** [comment]
😎

**Review by rbren — APPROVED** [review]

**Comment by DevHarshPatel** [comment]
Hey there! I love the OpenDevin but I was just a bit curious if people like my redesign of the logo which is a bit minimalistic and simple and if yes I am more than happy to refine more on it or make any further changes.
OpenDevinLogo

**Comment by rbren** [comment]
@DevHarshPatel this is neat! But we have a designer working on a new logo now 😄

**Comment by DevHarshPatel** [comment]
Thank you very much for your feedback. I would love to help in any further designing or website development help needed in OpenDevin and will try my best to do so. 😊✏️

**Pull request merged**
