### PR TITLE
Clear history at the beginning of a new task🧹

### PR DESCRIPTION
**Pull request by mkavinkumar1**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
Clearing history at the beginning of a new task ensures that any previous data or context is removed, reducing the risk of errors or confusion. This can enhance the accuracy and relevance of the task being performed, preventing any carryover from past tasks. This update addresses any open issues related to context management and data integrity.

**Give a summary of what the PR does, explaining any non-trivial design decisions**
The PR introduces a mechanism to clear the history at the start of each new task. This design decision is made to maintain a clean state and ensure that tasks are executed with a fresh context. This approach avoids potential conflicts and errors that may arise from residual data.

### CODE REVIEW

**Review by xingyaoww — APPROVED** [review]
LGTM! Thanks for this! This definitely annoys me a little bit at some point

**Comment by tobitege** [comment]
> LGTM! Thanks for this! This definitely annoys me a little bit at some point

I don't like this happening on STOPPED. This should be linked to a "Clear Chat" UI button?

**Comment by mkavinkumar1** [comment]
> LGTM! Thanks for this! This definitely annoys me a little bit at some point



> > LGTM! Thanks for this! This definitely annoys me a little bit at some point
> 
> I don't like this happening on STOPPED. This should be linked to a "Clear Chat" UI button?

There is no such button

**Comment by tobitege** [comment]
> > LGTM! Thanks for this! This definitely annoys me a little bit at some point
> 
> > > LGTM! Thanks for this! This definitely annoys me a little bit at some point
> > 
> > 
> > I don't like this happening on STOPPED. This should be linked to a "Clear Chat" UI button?
> 
> There isn't currently a "Clear Chat" button in the UI, so we'd need to create a new one if we go that route. However, I believe it's not necessary at this point. The current implementation should suffice for the intended functionality.

I have a problem with clearing the history without the users' consent just because during a chat session the agent might return the STOPPED state. The user's task might not even be finished.
If the user wants to start a new task, there's a button for that.

I feel like I don't see your use case for this, when this would apply?

**Review by neubig — CHANGES_REQUESTED** [review]
Yes, just to clarify a bit @mkavinkumar1 , the agent can actually return to the `STOPPED` state when it *hasn't* finished the task but needs more input. For example, when it wants to make a PR to github, but doesn't have the appropriate credentials through a github token. In this case, clearing the history would be counter-productive because the agent might forget about what it has done previously.

Because of this, I think maybe we shouldn't make this change, although we do really appreciate the attempt to contribute! We'd be happy to have other changes in the future.

(I will close this later, but keep it open for a little bit in case I missed something)

**Comment by mkavinkumar1** [comment]
> I have a problem with clearing the history without the users' consent just because during a chat session the agent might return the STOPPED state

I have tested It was not happen like this, Please check in which funtion it was used.

**Review by neubig — APPROVED** [review]
Thanks a lot for the clarification! I also missed this (due to github's display of only the changed code). This indeed LGTM

**Pull request merged**
