### PR TITLE
Remove pydantic warnings

### PR DESCRIPTION
**Pull request by SmartManoj**
https://github.com/BerriAI/litellm/pull/2893

### CODE REVIEW

**Comment by enyst** [comment]
Oh thanks! This is good news. LiteLLM is very quick with new patches, they released several within days lately.

I guess we can wait a little bit, rather than hardcode a branch. The warning is annoying though.

@dorbanianas WDYT?

**Comment by dorbanianas** [comment]
@enyst Yeah agree, the warning is too annoying, but as much as it doesn't affect the base execution of our project so we can wait for the update 👌

**Comment by rbren** [comment]
👍 I agree on waiting. If it takes more than a day or two we can poke them to release

**Comment by rbren** [comment]
Thanks for bringing it to our attention @SmartManoj! But let's close this one and just wait for the upstream to flow in

**Comment by ishaan-jaff** [comment]
> I guess we can wait a little bit, rather than hardcode a branch. The warning is annoying though.

Merging it now. Sorry for the warning, do you have suggestions on how we can avoid these types of warnings from re-occuring ?

**Comment by dorbanianas** [comment]
@ishaan-jaff you can simply avoid using the `model_` name for the pydantic class attributes more info [here](https://docs.pydantic.dev/2.0/usage/model_config/#protected-namespaces)

**Comment by ishaan-jaff** [comment]
@dorbanianas tracking this here: https://github.com/BerriAI/litellm/issues/2915 

on our side we'll add testing to ensure that this warning will not re-appear 


> can you pls update to the latest version so the issue would stop it's really annoying

just queued a new release

**Pull request closed without merging**
