### PR TITLE
[DRAFT] add fetching branches feature to BrowsingAgent

### PR DESCRIPTION
**Pull request by tobitege**
My first attempt to extend the BrowsingAgent with a LLM "command" to fetch all branch names of a given repository via GitHub's API.
Whilst I was trying out OpenDevin with git related tasks, this simple task is a not a small amount of data to retrieve and then process/parse and probably not in one turn.
Also added a simple unit test.

Not clear to me yet, what the preferred place is to make these additions.

Wasn't yet able to fully test it, thus draft. Aaand I chose the wrong branch to start with. _sigh_

### CODE REVIEW

**Comment by yufansong** [comment]
Just my personal opinion, I worry this isn't a good place to add. I am not sure whether we should put specific GitHub optimization in agent logic. And also I worry this change will influence our benchmark evaluation performance.

**Comment by tobitege** [comment]
> I mean this optimization is good, but not sure this is the right place to add. cc @frankxu2004

Thanks for the feedback as I had worries it wasn't the right place to add.
I can easily move it to e.g. agentskills instead, if you prefer?

**Comment by frankxu2004** [comment]
I also think it would be better to move this. Actually I think maybe to fetch branches, this might not even need browsing agent right? You could implement the agentskills and just use request.get, or rely on github API to get this information

**Comment by tobitege** [comment]
> I also think it would be better to move this. Actually I think maybe to fetch branches, this might not even need browsing agent right? You could implement the agentskills and just use request.get, or rely on github API to get this information

Yes, that's how this addition would act (using request).

**Comment by tobitege** [comment]
I'll close this PR and move the code to agentskills in a new PR.

**Pull request closed without merging**
