### PR TITLE
dep: poetry.lock updated (lots of changes)

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Update poetry.lock file. It has quite a lot of changes since last update.

### CODE REVIEW

**Comment by tobitege** [comment]
> Does this mean dependabot is not working as we wanted? I don't think that manually update `poetry.lock` is a good idea.

It does add its entries and it's from like 30min ago and on main, but still, having run poetry lock again, this is the result.
Let me know, if this shouldn't be updated this way and I'd close this.

**Comment by Umpire2018** [comment]
> It does add its entries and it's from like 30min ago and on main, but still, having run poetry lock again, this is the result. Let me know, if this shouldn't be updated this way and I'd close this.

Maybe refer to https://github.com/OpenDevin/OpenDevin/pull/1796

**Comment by tobitege** [comment]
Thanks @Umpire2018 for the reference.

cc @rbren @li-boxuan maybe you can re-assess these updates and whether action is required (or none).

**Comment by tobitege** [comment]
Just for fun, I ran an OpenDevin session with this branch just now incl. several file operations (gpt4o) and also shared this via the "Thumbs up" feedback button, referencing this PR at the end of the chat. 😁 
Not a single error message in terminal! 🥳

**Comment by li-boxuan** [comment]
We limited the dependabot frequency, which is probably why we are falling behind on the updates. I agree that we should rely on dependabot to update, mostly because dependabot will list out the breaking changes, which are not possible to spot when developers update the dependencies manually.

**Comment by li-boxuan** [comment]
That being said, I would be happy to approve this PR if you can check and tell us there are no breaking upgrades :P

**Comment by tobitege** [comment]
I plan to give it another round of tasks in OpenDevin (see my previous comment) and when I don't see any errors, will mark it for review.

2 observations, though:
- some changes in the lock file show (to me) weird version jumps or conditions, maybe a detailed look is still warranted.
- the first run of the `poetry lock --no-update` on my fast PC (inside WSL) took over about 90 seconds, just as info.

**Comment by li-boxuan** [comment]
On a side-note, we should probably increase this number: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit by default the limit is 5. Looks like 5 updates a day cannot help us keep up with the upgrades.

**Comment by tobitege** [comment]
So after Step 70 I ended my session with OpenDevin, my prompt was now ~240 KB in size.
Experienced some issues, but those were mainly related to gpt4o being incapable of counting lines.
This time, for a change, I clicked the "thumbs down" button, just for the fact it got stuck in a loop after 3 times. 😬 

No system errors in the front- or backend. This PR is now reviewable, imo.

**Review by enyst — APPROVED** [review]

**Review by li-boxuan — APPROVED** [review]
Thanks for testing it out! I just merged main to ensure it is happy with the new image build process.

**Pull request merged**
