### PR TITLE
bug: #313 responsive width wrt size

### PR DESCRIPTION
**Pull request by ASQUAREEE**

### CODE REVIEW

**Comment by rbren** [comment]
@ASQUAREEE can you include a few screenshots of how this looks?

**Comment by ASQUAREEE** [comment]
> @ASQUAREEE can you include a few screenshots of how this looks?

sure

**Comment by ASQUAREEE** [comment]
image
image
image

**Comment by ASQUAREEE** [comment]
image

**Comment by rbren** [comment]
This LGTM! I'll give FE folks a chance to chime in

**Comment by yimothysu** [comment]
LGTM

**Pull request merged**
