### PR TITLE
Requested change added for linting and Typechecking

### PR DESCRIPTION
**Pull request by sumanxg**
I have added changes suggested by @neubig Now the directory structure is same without moving the files, just dev_config/python is added.

### CODE REVIEW

**Comment by sumanxg** [comment]
@neubig Please review and let me know if more changes are required. Thanks.

**Review by neubig — COMMENTED** [review]
Just to clarify, will this run mypy in pre-commit? It seems like there is only a configuration added for ruff.

**Comment by sumanxg** [comment]
Hi @neubig I have also added mypy in the pre-commit now, I am sure it will run.

**Comment by yimothysu** [comment]
Marking as closed due to https://github.com/OpenDevin/OpenDevin/pull/69 being merged

**Pull request closed without merging**
