### PR TITLE
Add iframe implementation to Browser component

### PR DESCRIPTION
**Pull request by AbhisekOmkar**
This commit adds the implementation for displaying web content within the Browser component using an iframe. It includes the necessary changes to Browser.tsx, App.tsx and Browser.css files. The iframe allows loading external websites such as Wikipedia for display within the application.

### CODE REVIEW

**Comment by AbhisekOmkar** [comment]
@neubig can you review this

**Comment by yimothysu** [comment]
I believe the plan is to render screenshots from the backend browser as discussed in https://github.com/OpenDevin/OpenDevin/issues/37 and https://github.com/OpenDevin/OpenDevin/issues/44

**Comment by AbhisekOmkar** [comment]
As of now until we develop the backend for that we can use iframe

**Comment by yimothysu** [comment]
We should instead focus on developing this frontend <---> backend communication then. I opened a PR https://github.com/OpenDevin/OpenDevin/pull/85 to render updates from `browser` messages sent by the backend.

**Comment by xcodebuild** [comment]
I'm afraid iframes may not be very useful here, as many sites do not allow access through iframe embedding. It's also unreasonable for OpenDevin to let user access to agent-accessed websites through iframes. We'll probably still use images for rendering.

**Comment by AbhisekOmkar** [comment]
How we gone a capture screenshots in browser-content if we are not using iframe

**Comment by neubig** [comment]
We'll probably use Selenium through the Python backend to capture screenshots! So I think as others mentioned it'd probably be better to close this and just continue displaying the screenshots like we have currently.

But thanks for the contribution @AbhisekOmkar !

**Pull request closed without merging**
