### PR TITLE
Fix mock server

### PR DESCRIPTION
**Pull request by yimothysu**
Currently, the mock server is broken because several of the API endpoints aren't implemented. Also, the endpoints were moved under the `/api` route, which hasn't been updated in the mock server. This causes the frontend to crash with a blank page.

This PR fixes the mock server to work properly.

### CODE REVIEW

**Review by rbren — APPROVED** [review]
Thanks for the fix!

**Comment by rbren** [comment]
PS @yimothysu we might want to create a github action that exercises this, to prevent regressions in the future

**Comment by yimothysu** [comment]
@rbren do you think we need to set up end-to-end integration tests? since this error is thrown on the frontend, but the issue is the backend.

**Comment by rbren** [comment]
I'm thinking more about having some frontend tests that run the app while connected to the mock server, and check that things load correctly

**Pull request merged**
