### PR TITLE
Add MIT LICENSE

### PR DESCRIPTION
**Pull request by asadm**
Before we began, we should decide on a license. If this is "open", I would consider MIT or Apache 2.0 to be safe choices.

### CODE REVIEW

**Comment by jjfantini** [comment]
what about an open license that restricts commercial use? to keep it for the people?

**Comment by pombredanne** [comment]
> what about an open license that restricts commercial use? to keep it for the people?

Then this is proprietary, not open source.

**Comment by asadm** [comment]
If we go with a non-commercial license:
- many will not contribute at all, since it's not open source in true sense
- commercial folks will just reimplement ideas here, LoC vs. impact is pretty low in genAI world, will take a weekend to replicate ideas
- this repo will be left behind.

**Comment by hannibalhuang** [comment]
agree with @asadm here and also just commented on issue #10 , MIT or Apache 2.0 are safer choices than CC-bys

**Comment by huybery** [comment]
Thank you @asadm , more people think the MIT license is a better fit for OpenDevin.

**Pull request merged**
