### PR TITLE
refactor(frontend): categorized css files into a separate folder

### PR DESCRIPTION
**Pull request by RenukaCheripally**
- Moved css files to a shared css folder under components

### CODE REVIEW

**Comment by huybery** [comment]
Thanks for the contribution but there is some duplication with PR #296 , a good suggestion would be to deal with browser related styling issues in this PR?

**Comment by RenukaCheripally** [comment]
> Thanks for the contribution but there is some duplication with PR #296 , a good suggestion would be to deal with browser related styling issues in this PR?

Could you please mention if there is any browser related issues i can look into?

**Comment by huybery** [comment]
😃 My point is that your commit could probably be added in PR #296 , since you addressed a similar issue.

**Comment by RenukaCheripally** [comment]
Sure, I will do that

**Comment by huybery** [comment]
Btw, currently the browser is just a static style, it would be nice to implement a screenshot rendering of the URL.

**Comment by huybery** [comment]
@808vita We can create a separate thread for this. Are you in slack?

**Comment by 808vita** [comment]
> Are you in slack?

yes . 
email : its808vita@gmail.com

**Comment by huybery** [comment]
https://forms.gle/758d5p6Ve8r2nxxq6

**Comment by huybery** [comment]
@808vita fill it out and i will invite u.

**Comment by huybery** [comment]
@RenukaCheripally Thanks for your contribution. LGTM.

**Pull request merged**
