### PR TITLE
Update Dockerfile to assign workspace directory properly to user 

### PR DESCRIPTION
**Pull request by jtac**
creating the workspace directory after switching user to fix permission errors https://github.com/OpenDevin/OpenDevin/issues/1560

### CODE REVIEW

**Comment by iFurySt** [comment]
@jtac the workflow failed, can you take a look?

```
> Dockerfile:56
> --------------------
>   54 |     RUN chown -R opendevin:app /app && chmod -R 770 /app
>   55 |     USER opendevin
>   56 | >>> RUN mkdir -p $WORKSPACE_BASE
>   57 |     
>   58 |     ENV VIRTUAL_ENV=/app/.venv \
> --------------------
> ERROR: failed to solve: process "/bin/sh -c mkdir -p $WORKSPACE_BASE" did not complete successfully: exit code: 1
> Error: Process completed with exit code 1.
```

**Comment by rbren** [comment]
User probable doesn't have permission to edit the `/opt` dir. Maybe we should create it as root, then chown it?

**Comment by jtac** [comment]
I moved the creation back to root and instead added a line to assign the directory to the user

**Review by rbren — APPROVED** [review]
LGTM!

**Pull request merged**
