### PR TITLE
fix: change default RUN_AS_DEVIN to true and change some network setting

### PR DESCRIPTION
**Pull request by yufansong**
Quick fix the problem #887 introduced in #847. Firstly change the `RUN_AS_DEVIN: 'true'`.
After changing also meet problem like 
```
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```
After trying locally with `ssh -p 2222 opendevin@localhost` still will meet. 
So do little change to the docker network setting. (not sure this change from my local env setting, or a wrong docker network configruation)

### CODE REVIEW

**Comment by Luckytiger666** [comment]
same problem, met 
```
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```

**Comment by yufansong** [comment]
> same problem, met
> 
> ```
> pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
> ```

Do my new change about netwrok setting can fix it? Or you still meed the problem after my change?

**Comment by Luckytiger666** [comment]
After.
Should I merge xingyaoww's commits too?

**Comment by xingyaoww** [comment]
@Luckytiger666 

Can you try running on #891, too? I didn't encounter any issues with my local setup. Can you try first running `docker ps` to see if there's a container named `sandbox-XXX` created by opendevin, then try to `docker stop` these containers? After this, try rerun the whole thing?

**Comment by Luckytiger666** [comment]
restart the container, and it works fine now

**Comment by marikan114** [comment]
It's better to first check with `ssh -p 2222 opendevin@localhost`. I found that there is an old host key.

> Offending RSA key in ~/.ssh/known_hosts:13

Delete line 13 from the known_hosts file, save, and restart to fix the issue.

**Pull request merged**
