### PR TITLE
feat: use sphinx to build our API document

### PR DESCRIPTION
**Pull request by yufansong**
Because our codebase become larger and larger. I find it is inefficiency to see every line code to catch up our latest progress. I prefer to build a API doc for us to do quick browser.

Solution for building API doc:
1. Pydocs
It is build-in module in python. But find it canot satisfied my requirement, and operation is tedious, I even need to manually  generate every sub module by myself.
2. Sphinx (Prefer)
Sphinx [[github](https://github.com/sphinx-doc/sphinx)] [[doc](https://www.sphinx-doc.org/en/master/)] is a popular open source project to create intelligent and beautiful documentation. After some investigation, I think the final website is better than pydocs. So I choose it.
3. Others
Not sure whether there exist better open source solution. Sphinx already solve my problem. But welcome any other suggestions.

What this PR do:

1. It will show all modules and their sub module architecture.
5. It will show the function signature and class defnition.
6. You can search function/class in website.

I only add the source directory, and ignore the build directory. In this way, we can keep commit clear and small. But when your want to browser the doc, you need to build it manually. I will add some cmd for building in the future PR. 

How to run:
Go to `sphinx` directory run `make clean & make html`, then html file will generate in `sphinx/build` directory. Open index.html in your browser.

How to update:
Go to `sphinx` directory, run `sphinx-apidoc -o source ../opendevin -f `, then do `make clean & make html`. 

Website example:

image

image

image

### CODE REVIEW

**Comment by yimothysu** [comment]
@yufansong we're currently using https://github.com/OpenDevin/OpenDevin/pull/1372 for docs, which generates Python docs using [pydoc-markdown](https://niklasrosenstein.github.io/pydoc-markdown/). do you think this is sufficient?

cc @Sparkier

also see https://github.com/OpenDevin/OpenDevin/pull/1374

**Comment by yufansong** [comment]
> @yufansong we're currently using #1372 for docs, which generates Python docs using [pydoc-markdown](https://niklasrosenstein.github.io/pydoc-markdown/). do you think this is sufficient?
> 
> cc @Sparkier
> 
> also see #1374

Didn't notice you already have tried sphinx before. Let me check it first. :)

**Comment by yufansong** [comment]
@yimothysu  Thanks for you remind. I check the related pr and the previous discussion in slark. 
I think docusaurus is more beautiful than Sphinx. But sphinx can preovide search methods which docusaurus not. Wondering whether we can add search methods into current doc.

But anyway, I will close this PR first.

**Comment by Sparkier** [comment]
Adding search would definitely be nice. Docusaurus also has some support for search: https://docusaurus.io/docs/search

**Comment by Shimada666** [comment]
@Sparkier @yufansong 
Yes, I think the search function is very important. I believe we can start by using a local search plugin because it's simple. I have enabled this feature in vitepress(a similar docs website like Docusaurus, but based on vue). We can integrate Algolia search later when we have more content. 😁

**Comment by Shimada666** [comment]
I prefer Docusaurus over Sphinx. More people are familiar with Markdown than with reStructuredText, and the interface is more beautiful.

**Pull request closed without merging**
