### PR TITLE
feat: Agent buttons hover decor

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

The bottom-left agent buttons get a decent hover effect, if the button is enabled.
Also, mouse cursor showed up differently for buttons.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

Makes things visually nicer to click (cursor wasn't captured, sorry): 😁 
grafik
grafik

### CODE REVIEW

**Review by amanape — APPROVED** [review]
Looks good! But you should consider using TailwindCSS over traditional `.css` files for this project.

Mixing the two can cause confusion for other developers as they now have to check to sources. Prefer only one

**Comment by tobitege** [comment]
> Looks good! But you should consider using TailwindCSS over traditional `.css` files for this project.
> 
> Mixing the two can cause confusion for other developers as they now have to check to sources. Prefer only one

Oh, I had totally forgotten about that, you had mentioned that to me already.

I'll rewrite that accordingly, switching to draft for now.

**Comment by tobitege** [comment]
As recommended, converted the styling to TailwindCSS syntax now. 🎐

**Comment by iFurySt** [comment]
Life is already complicated enough, using Tailwind makes it a bit simpler and more enjoyable.😄

**Review by iFurySt — APPROVED** [review]

**Comment by iFurySt** [comment]
looks good, thanks

**Pull request merged**
