### PR TITLE
tests: more Agentskills tests; updated .gitignore

### PR DESCRIPTION
**Pull request by tobitege**
For tracking down an issue where backticks get escaped in file operations, I've added a test for `_print_window` method and one more multiline edit_file test, both containing especially backticks.
More tests to come in separate PR for `run_ipython` in a new test file when I have the time.

The .gitignore change was only to add ".cursorignore" and moving some entries to better fitting sections instead of just added to end of file.

Example log for the backticks issue (note in the middle the IPythonRunCellObservation where backticks are escaped now):
```bash
16:33:13 - opendevin:INFO: agent_controller.py:278 - CodeActAgent LEVEL 0 STEP 8
16:33:29 - opendevin:WARNING: llm.py:294 - Cost calculation not supported for this model.
16:33:29 - opendevin:INFO: llm.py:229 - Cost: 0.00 USD | Accumulated Cost: 0.00 USD
16:33:29 - opendevin:INFO: agent_controller.py:297 - **IPythonRunCellAction**
THOUGHT: Let's document the findings and steps in the `findings.txt` file.
CODE:
edit_file(
    start=1, 
    end=1, 
    content="""# Findings and Steps for Adding a Theme Switcher

## Step 1: Clone the Repository
- Cloned the repository from https://github.com/tobitege/OpenDevin.

## Step 2: Explore the UI Folder
- Navigated to the `OpenDevin/frontend` folder.
- Identified the main files and structure of the React application.

## Step 3: Search for React Theme Switcher Module
- Identified popular React theme switcher modules:
  - styled-components
  - Material-UI
  - Theme UI
  - React Switch Theme

## Step 4: Determine How to Integrate the Theme Switcher
- Opened the `App.tsx` file in the `OpenDevin/frontend/src` directory.
- The `App.tsx` file is the main component where the theme switcher can be added.

## Next Steps
1. Choose a theme switcher module (e.g., styled-components).
2. Install the chosen module using npm.
3. Integrate the theme switcher in the `App.tsx` file.
4. Test the implementation to ensure it works correctly.
"""
)
16:33:29 - opendevin:INFO: agent_controller.py:171 - **IPythonRunCellObservation**
[File: /workspace/findings.txt (26 lines total after edit)]
1|# Findings and Steps for Adding a Theme Switcher
2|
3|## Step 1: Clone the Repository
4|- Cloned the repository from https://github.com/tobitege/OpenDevin.
5|
6|## Step 2: Explore the UI Folder
7|- Navigated to the \`OpenDevin/frontend\` folder.
8|- Identified the main files and structure of the React application.
9|
10|## Step 3: Search for React Theme Switcher Module
11|- Identified popular React theme switcher modules:
12|  - styled-components
13|  - Material-UI
14|  - Theme UI
15|  - React Switch Theme
16|
17|## Step 4: Determine How to Integrate the Theme Switcher
18|- Opened the \`App.tsx\` file in the \`OpenDevin/frontend/src\` directory.
19|- The \`App.tsx\` file is the main component where the theme switcher can be added.
```
(shortened)

### CODE REVIEW

**Review by enyst — APPROVED** [review]
Nice, thank you!

**Comment by tobitege** [comment]
Ready for review, added a hotfix for integration test

**Comment by enyst** [comment]
@li-boxuan  @tobitege The integration test is still unhappy, because of this:
```
# Previous Actions
-goto('http://localhost:8000')
-
+noop()
```
Which we were just talking about here: https://github.com/OpenDevin/OpenDevin/pull/2170#discussion_r1631066653

If I see this right, it won't be the same when it's a delegate and when it's not, it might be missing a MessageAction so state.history is not 1 now...

**Comment by tobitege** [comment]
@enyst Thanks so much for your help! 🥇

**Pull request merged**
