### PR TITLE
fix: add the community-maintained model list

### PR DESCRIPTION
**Pull request by iFurySt**
#591 #649 #259 multi issues discuss this problem, i just merged the `model_list` and `model_cost.keys()`(community-maintained) to solve this problem for now.

image
image

### CODE REVIEW

**Comment by foragerr** [comment]
I was pondering switching to `model_cost.keys()` as well - the point I got hung up on is, does it make sense for OpenDevin to list vision models?

**Comment by iFurySt** [comment]
yes, but the community-maintained models are not only vision models, sth like
```
  "groq/mixtral-8x7b-32768",
  "groq/llama2-70b-4096",
  "groq/gemma-7b-it",
```
also be used by someone.

**Comment by rbren** [comment]
It seems like the underlying issue was fixed upstream in LiteLLM. Do we still need this?

**Comment by foragerr** [comment]
> Do we still need this?

Maybe. 

There's still a lot of discrepancies between what `model_cost.keys()` returns and `model_list` returns. I can see some value in using a superset. But users should probably be warned that some entries on the super long list (~400 entries) are potentially unusable.

```
Common models: 206
Models in model_cost, but not model_list: 102
Models in model_list, but not model_cost: 45
```

I [posted a question](https://github.com/BerriAI/litellm/issues/2803#issuecomment-2035340744) for the litellm folks for their opinion/guidance.

**Comment by rbren** [comment]
👍 let's keep an eye on LiteLLM's response

**Pull request merged**
