### PR TITLE
Adjust is-stuck check for the same steps to 3 until it's stopped

### PR DESCRIPTION
**Pull request by enyst**
This PR proposes to adjust the check for identical (action, obs) down from 4 of them (current behavior) to 3 of them, before it stops.

Backported from https://github.com/OpenDevin/OpenDevin/pull/2355

I'm seeing reports that it's hard to get 4 (identical) steps, where the loop stops, but the agent is obviously stuck and will stop, just later than it feels like it could have. I think we can stop it at 3 steps. We used to do that (sort of) and it has worked in the past, it's probably not easy to do by accident.

Example issue that takes too long:
https://github.com/OpenDevin/OpenDevin/issues/2238

### CODE REVIEW

**Comment by tobitege** [comment]
This might have an impact on evals, or?
Would a config setting make sense for this?

**Review by SmartManoj — APPROVED** [review]

**Comment by SmartManoj** [comment]
> This might have an impact on evals, or? 

Don't think so.


> Would a config setting make sense for this?

to decrease the value?

**Comment by tobitege** [comment]
> > Would a config setting make sense for this?
> 
> to decrease the value?

To make it configurable in general, set to 3 as default. 
A loop can have many reasons, like the LLM mixing or making up Agentskilll commands and it might get it right on next attempt.
Depending on the model, from the perspective of a user, they might want it at 5 or any other subjective value.

**Comment by SmartManoj** [comment]
Do you have any examples where it was right at 5th step?

**Comment by tobitege** [comment]
Why do I need to have a specific example as screenshot to make an argument?

**Comment by enyst** [comment]
> This might have an impact on evals, or? Would a config setting make sense for this?

I think this was an understatement, @tobitege. You were so right to be suspicious of this. 😅 Evals run into stuck-in-a-loop in an unbelievable number, over 30% as discussed on slack these days. Many of them are this particular sequence, simply 3 identical actions/obs. Many of those are the same failed edit.

On the latest evals I ran these days, I made this back to 4, and added a bit in an attempt to make the LLM re-think: when it did 2 identical steps, it will get a warning that it's almost stuck, and when it did 3 identical steps, it gets a stronger warning. FWIW something about this approach seemed to work or at least to _do something_: the SWE-bench Lite eval has 300 tests, and they ended previously with 93 / 300, or more, stuck-in-a-loop. With the extra warning, they're 60 / 300. I am still to dig into histories to see if it also changed results.

It might make sense to think of a config, too...

**Pull request merged**
