### PR TITLE
fix frontend : highlight active assistant text and maintain chat seq | for  #476

### PR DESCRIPTION
**Pull request by 808vita**
highlight active assistant text and maintain chat seq

[new typing seq.webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/8ed6ffb7-5986-443e-b9e2-48013216f007)

for #476 
This PR instead of #531

### CODE REVIEW

**Comment by 808vita** [comment]
needs some wrangling to find bugs.
note: potential for bugs resides in side effects (useEffects).

**Comment by rbren** [comment]
This is working great!

The one bug I see is that if it prints several lines, the go below the fold, and you have to scroll down to see the full message

**Comment by rbren** [comment]
story

**Comment by 808vita** [comment]
@rbren I have added a new commit which alters the autoscroll behaviour.

[new autoscroll.webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/0f78fbf6-f055-47fc-ba84-e1da37ac175d)

**Comment by rbren** [comment]
👍 let's get this one in

**Pull request merged**
