### PR TITLE
Reorganize documentation into Sphinx

### PR DESCRIPTION
**Pull request by yimothysu**
image

Currently, we have all documentation in a `docs/` directory. This PR moves the documents into Sphinx to generate a documentation website, which has several advantages:
1. More structured and clearer organization
2. More extensible
3. Better search functionality
4. Automatic code documentation from docstrings
5. Easier to navigate on mobile

We can host this on GitHub Pages or ReadTheDocs.

### CODE REVIEW

**Comment by li-boxuan** [comment]
https://github.com/OpenDevin/OpenDevin/pull/1372 seems to overlap with this effort?

**Comment by yimothysu** [comment]
@Sparkier just realized I missed your PR because I started implementing this earlier. Do you have any strong opinions?

I lean towards Sphinx to automatically generate code documentation from Python docstrings, and for integration w/ Python tooling in general.

**Comment by Sparkier** [comment]
Hey, I started a [slack thread](https://opendevin.slack.com/archives/C06P5NCGSFP/p1714147723056999) since this is a bigger decision. Hope that's ok with you.

**Comment by yimothysu** [comment]
Closing in favor of #1372

**Pull request closed without merging**
