### PR TITLE
Updated requirements.txt 

### PR DESCRIPTION
**Pull request by Aadya1603**
Updated requirements.txt file

### CODE REVIEW

**Comment by rbren** [comment]
@Aadya1603 wdyt about merging all the different requirements.txt files here? We have server/requirements.txt and agenthub/langchains_agent/requirements.txt too

**Comment by Aadya1603** [comment]
sorry about that @rbren  . It was for  main/requirements.txt [A starting point for SWE-Bench Evaluation with docker]

**Comment by rbren** [comment]
Right--I was just suggesting we put them all in one place, for simplicity. But we can do that in another PR too (or not at all)

**Review by rbren — APPROVED** [review]

**Comment by xingyaoww** [comment]
Sounds good! Let's do them in another PR

**Pull request merged**
