### PR TITLE
Language Model Manager (LLM) for Text Generation

### PR DESCRIPTION
**Pull request by AbhisekOmkar**
This repository contains code for a Language Model Manager (LLM) that allows users to interact with various text generation models from different providers such as Claude, GPT, and Ollama. The LLM provides functionalities to list available models, generate text based on prompts, and manage token usage. It abstracts away complexities of interacting with different APIs, providing a unified interface for text generation tasks.

Key Features:

List available models from Claude, GPT, and Ollama.
Generate text based on prompts using selected models.
Manage token usage to track resource consumption.
This repository is intended to be a flexible tool for managing and utilizing text generation models in natural language processing tasks.

### CODE REVIEW

**Comment by AbhisekOmkar** [comment]
@neubig @rbren @huybery can you guys review and merge this PR

**Comment by rbren** [comment]
@AbhisekOmkar great minds think alike 😄 

https://github.com/OpenDevin/OpenDevin/pull/114

I think going with a third party like LiteLLM makes more sense here, because we get a dozen or so LLM integrations for free, and we can offload the work of managing each of the different implementations to the LiteLLM library.

**Comment by AbhisekOmkar** [comment]
@rbren , thank you for the suggestion! Using LiteLLM does sound like a promising approach, especially considering the benefits of accessing multiple LLM integrations for free and simplifying the management process.

**Comment by AbhisekOmkar** [comment]
@rbren, currently, I've written basic code. Once we've implemented LiteLLM locally and thoroughly tested it, we can merge it into the main branch.

**Comment by rbren** [comment]
We've got LiteLLM going now, so I think we can close this one--sorry Abhisek!

Your frontend changes might still be worth getting in (not sure what they're getting after). Feel free to open a separate PR

**Pull request closed without merging**
