### PR TITLE
feat: automated Docker compose build and run environment

### PR DESCRIPTION
**Pull request by lehcode**
## Usage from scratch

1. Have Linux with Python 3.11
2. Have `docker compose`
3. Have Python `poetry`
4. Check out repo: [https://github.com/lehcode/oppendevin.git](https://github.com/lehcode/oppendevin.git)
5. `cd repo_folder` && `poetry run`

Full upgrade details are in docker/README.md

I hope this PR would be considered helpful.

### CODE REVIEW

**Comment by rbren** [comment]
@lehcode there's a lot here! Looks like some good stuff.

Can you explain what your overall goal is here? Maybe we can break it down into smaller PRs

**Comment by lehcode** [comment]
Thank you, @rbren !

The major goal is to make a development more consistent for developers and end users at the same time.

## Users features:
**Simple straightforward run of OpenDevin  for end users:**
- Use single simple command to run
- No need to manage dependencies at the user side

## Developers features (WIP)
- Bound folder mounts to reflect local changes in container immediately
- Hot module replacement for AI
- Environment management using environment variables

More... I simply cannot recall everything, will add to docker/README.md 🫤

**Comment by rbren** [comment]
So this part:
> Simple straightforward run of OpenDevin for end users:
> * Use single simple command to run
> * No need to manage dependencies at the user side

I think is taken care of now that we have a `docker run` command.

The developer features seem interesting though. I'm especially interested in the docker-compose that adds ollama--that could be great for both devs and end-users.

This PR is _way_ too big as it stands though. Definitely don't want to support 5 new docker images 😅 

I would encourage you to open a smaller PR that solves a single problem. Maybe open one that just adds a docker-compose that runs both the existing OpenDevin and ollama, and connects them together? That would be super cool.

I'm going to close this one, but please do open up one or more new PRs that tackle some of these problems one at a time! See also: https://graphite.dev/blog/the-ideal-pr-is-50-lines-long

**Comment by lehcode** [comment]
Sure, thanks!

**Comment by rbren** [comment]
Nothing stopping you from maintaining a fork!

But I don't think we want to have two long-lived branches inside this repository--it's very difficult to maintain long-running branches

**Comment by lehcode** [comment]
Thank you @rbren !

**Pull request closed without merging**
