### PR TITLE
Increased codecov threshold

### PR DESCRIPTION
**Pull request by SmartManoj**
Temporarily solves #2369

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
This doesn't solve the problem I think. This PR is still failing, see attached screenshot.

Screenshot 2024-06-16 at 9 46 05 AM

I think that issue cannot be easily solved due to limitations in codecov, so I'll just close it.

**Comment by SmartManoj** [comment]
Because it is > 10, how much drop did you see so far?

**Comment by SmartManoj** [comment]
image

**Review by neubig — CHANGES_REQUESTED** [review]
This doesn't fundamentally fix the issue it sets out to fix, and it loosens our testing criteria. So I think we should probably not do this...

**Comment by tobitege** [comment]
If I'm not mistaken, last time I looked into CodeCov's rating about a merged PR, it looked like it did not limit its rating to the changes made by the author or the PR itself, but everything that came into the branch via updates from main.
So I'm a bit sceptical about what their percentage actually means.

**Comment by SmartManoj** [comment]
> This doesn't fundamentally fix the issue

Yes, it is a temporary workaround.

**Comment by yufansong** [comment]
> This doesn't solve the problem I think. This PR is still failing, see attached screenshot.
> 
> Screenshot 2024-06-16 at 9 46 05 AM
> I think that issue cannot be easily solved due to limitations in codecov, so I'll just close it.

I agree we should close it. It didn't harm anything now. We don't need `Temporarily solves` or `temporary workaround `

**Comment by neubig** [comment]
The core issue was fixed in #2468

**Pull request closed without merging**
