### PR TITLE
style(code editor): improved UI / UX for code editor

### PR DESCRIPTION
**Pull request by akhilvc10**
# Improved Code Editor UI and UX

## Changes

1. Introduces improvements to the Code Editor component's UI and UX based on the new design.

2. Updates the color codes to Tailwind's neutral gray, based on the latest [mockup](https://www.figma.com/file/iM5UBG1lnpg2sgE3cFnF1P/OpenDevin?type=design&node-id=7521-15452&mode=design&t=vGP5hdOOs6ZrzQ07-4).

3. Removes the old theme variables.

### Before: 
Screenshot 2024-04-06 at 7 10 09 PM

### After: 

**Screenshot**
Screenshot 2024-04-08 at 4 19 04 PM

**Video Recording**

https://github.com/OpenDevin/OpenDevin/assets/23031065/20e89f7f-bdeb-4512-a378-d58315d1d9b0

### CODE REVIEW

**Comment by foragerr** [comment]
Looks great!

**Comment by akhilvc10** [comment]
> Looks great! 👏
> How much harder is it to allow multiple files to stay open?

Thanks ! @foragerr 

Allowing multiple files to stay open is not a significantly complex task, but it does require additional development effort and thoughtful implementation.

In this particular PR, my primary focus was on improving the existing UI and enhancing the overall user experience. This was an important step to ensure the core functionality is intuitive and user-friendly.

I plan to create a separate PR dedicated to adding this "multiple file open" functionality in the near future.

**Comment by openartist** [comment]
@akhilvc10 It's looking great but I see a few issues. I'll do a thorough review in a bit.

**Comment by Sparkier** [comment]
Awesome, really like the design. One thing I immediately noticed from the screenshots is that there are some issues with the tab design:
1. it is very hard to recognize the currently active tab
2. the height of the tab bar is larger than the height of the headings of all other containers now

**Review by yimothysu — APPROVED** [review]
Looks great! There's still some package manager merge conflicts so let's merge once fixed.

**Comment by openartist** [comment]
• The font in the file tree is incorrect, the files should be indented
image
• The active tab vs inactive tab color are not correct (see design)
• The stroke around the chat input field is incorrect
image
• Terminal is missing an icon
• If we are going to add tabbed files now, let's add a vertical line that goes across:
image
image
• Can you update the chat box style with the most current?
image
• I found a discrepancy in the design where the tab fonts were using Inter, can you check the design and make sure you're using SF Pro?
image
• There seems to be some spacing that's off in the IDE:
image

**Pull request merged**
