### PR TITLE
feat(frontend): typing chat feature | for  #187

### PR DESCRIPTION
**Pull request by 808vita**
for #187 Print terminal and chat output character by character 

changes:

- created hook - useTypingEffect
- modified chatInterface - created a new jsx typing chat 
- chatSlice - exported Message type

preview (using mock server):

[typing chat preview .webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/619e990c-857c-4b9c-b106-b36654796fde)

### CODE REVIEW

**Comment by rbren** [comment]
This looks awesome!

LGTM but I will let frontend folks look

**Comment by huybery** [comment]
@rbren In the future, should we make the typewriter effect available on the backend? For example using SSE (Server-Sent Events) implementation?

**Comment by rbren** [comment]
IMO it's something for the frontend to handle as it wants--the backend shouldn't concern itself with how data gets displayed.

That said, many of the LLMs offer a "streaming" response, since response generation is slow. So we could stream data to the frontend as it becomes available, rather than waiting for the entire response to buffer and _then_ typing it out.

So I guess the answer is "we should do both"

**Comment by 808vita** [comment]
I have resolved the merge conflicts . 

oof I tried it out 

break words css

[probably because break words css class.webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/d0ace850-42d2-472f-bbfc-57c90b5cd3f1)

**Comment by 808vita** [comment]
actually its `w-4/5` thats causing this

**Comment by 808vita** [comment]
[new typing.webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/cab7018a-9644-4671-9f2e-ef2ae18747a7)

@rbren

**Comment by huybery** [comment]
LGTM. Thank you!

**Pull request merged**
