### PR TITLE
feat: support for stopping automatic scrolling to bottom and add "to bottom" button

### PR DESCRIPTION
**Pull request by Shimada666**
@amanape @Sparkier 
I have written a react hook to support stopping automatic scrolling to bottom and displaying a "To Bottom" button. It is currently effective in Jupyter. Please take a look at it. If everything is fine, I will apply it to the chat UI. 😁

### CODE REVIEW

**Comment by Shimada666** [comment]
https://github.com/OpenDevin/OpenDevin/assets/33391300/3343cb5d-ace5-4741-ab9c-4111db8fce42

**Comment by Shimada666** [comment]
I have implemented the following features:

1. When the user is browsing previous content, display a "To Bottom" button while disabling automatic scrolling.
2. Upon clicking the "back to the bottom" button, scroll to the bottom, enable automatic scrolling, and hide the "To Bottom" button.
3. When the user manually scrolls to the bottom, enable automatic scrolling and hide the "To Bottom" button.

**Review by amanape — APPROVED** [review]
Awesome!

One thought though: maybe we can have the hook expose the Jupyter ref so that we can handle the `onChatBodyScroll` logic *inside* the hook? Would make it more reusable.

See if it would be compatible with how the chat interface is setup, and if you find it convenient, go ahead.

Thanks for this, it will make the interface much more satisfying!

**Comment by Shimada666** [comment]
@amanape 
Thank you for your suggestions! I will consider them carefully.

**Comment by Shimada666** [comment]
Share the recent my work!
I have recently been attempting to implement automatic scrolling to the bottom for the chat UI. However, since the messages are fetched all at once, and the content is loaded using a typewriter-like effect, it's challenging for me to implement the auto-scrolling feature in a more elegant way. I will need some more time to implement this.

**Comment by amanape** [comment]
@Shimada666 There has been discussion of finding potential alternatives to the typing effect since it only "mocks" actual streaming. If you are facing issues with implementing autoscroll that may be resolved _without_ the typing effect, go ahead and attempt it. We can always explore options as we go on

**Comment by Shimada666** [comment]
@amanape 
It's great to get your reply! In fact, this feature is quite easy to implement without the fake typing effect. I will create a PR without using the typing effect, and then we can discuss together which option is better.

**Pull request merged**
