### PR TITLE
Add unit tests for LLM init function

### PR DESCRIPTION
**Pull request by neubig**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

This PR was mostly created as an example of how OpenDevin can create a PR for OpenDevin, but it also increases our code coverage by adding a test for a previously untested file (`llm.py`'s init function).

### CODE REVIEW

**Review by enyst — APPROVED** [review]
Nice to see, thanks!

**Comment by tobitege** [comment]
Shouldn't this be part of the "test_config.py" unit test?

**Comment by neubig** [comment]
> Shouldn't this be part of the "test_config.py" unit test?

I'm agnostic to this, but it seems that since this is testing `llm.py`, then maybe `test_llm.py` is OK?

**Comment by tobitege** [comment]
> > Shouldn't this be part of the "test_config.py" unit test?
> 
> I'm agnostic to this, but it seems that since this is testing `llm.py`, then maybe `test_llm.py` is OK?

Sure, it is a tightly scoped script and fits the name.

**Pull request merged**
