### PR TITLE
Migrate to new folder structure in preparation for refactor

### PR DESCRIPTION
**Pull request by rbren**
This rearranges files in the opendevin/ directory in preparation for moving to a new architecture, as pictured below

image

All changes here are just to folder structure and imports, plus formatting changes enforced by the linter.

Here's the new folder structure. It roughly matches the architecture diagram.

```
opendevin/
    __init__.py
    core/
        schema/
        logger.py
        exceptions.py
        config.py
        main.py
    server/
        mock/
    llm/
    controller/
        state/
    events/
        action/
        observation/
    runtime/
        sandbox/
        browser/
        utils/
```

### CODE REVIEW

**Review by xingyaoww — APPROVED** [review]
LGTM! Good to merge as long as we fix all the tests..

**Comment by rbren** [comment]
Whoops, apparently some of the tests aren't required--automerge beat me 😓

**Comment by rbren** [comment]
Strange...allegedly the integration tests are required, but they didn't pass here...
Screenshot 2024-05-02 at 1 14 44 PM

**Comment by rbren** [comment]
Screenshot 2024-05-02 at 1 14 38 PM

**Pull request merged**
