### PR TITLE
ci/lint: fix calling Ruff's format

### PR DESCRIPTION
**Pull request by Borda**
It seems that Ruff'f format was not called correctly; in fact, as both Ruff's IDs had overwritten `entry`, it was still calling check with a confusion of `id: ruff-format`

Found based on https://github.com/OpenDevin/OpenDevin/pull/1425#discussion_r1582056596

See the original entry call:
https://github.com/astral-sh/ruff-pre-commit/blob/596470fba20d04adc68ec7903ff69a12e5e1a8d3/.pre-commit-hooks.yaml#L15

cc: @rbren @li-boxuan

### CODE REVIEW

**Review by li-boxuan — APPROVED** [review]
LGTM, but it's gonna be a huge pain for people to handle merge conflicts :(

**Comment by Borda** [comment]
> LGTM, but it's gonna be a huge pain for people to handle merge conflicts :(

Yeah, only other way is drop false hook with "formatting"

**Comment by Borda** [comment]
> @Borda I'm generally a fan of enforcing new style changes one by one as they change--is that possible here?

Not sure what you mean, this is Black.

**Comment by li-boxuan** [comment]
> I'm generally a fan of enforcing new style changes one by one as they change--is that possible here?

It should be possible. We just need to run pre-commit only on changed files (i.e. on diff), not all files.

@Borda the ask is, can we avoid linting all files in this PR?

**Comment by Borda** [comment]
> can we avoid linting all files in this PR? This is a huge PR that will cause a lot of open PRs to have merge conflicts.

Yes, we can, just to be aware that many PRs will include unrelated changes to the PR's topic...

**Comment by li-boxuan** [comment]
> For example, simple PR with fixing typo may suddenly include another 50 changes

I think that's fine. It definitely reduces the burden for developers. People hate merge conflicts and if they hate it too much, they will start to hate all linting efforts.

**Comment by Borda** [comment]
@li-boxuan @rbren dropped applied pre-commit but noted that the lining job will fail...

**Comment by iFurySt** [comment]
pre-commit run `--files $(git diff --name-only $(git merge-base main $(git branch --show-current)) $(git branch --show-current) | tr '\n' ' ')` ...

this method can ensure only checking the modified files. but it is a bit troublesome to apply to workflow. it needs to fetch the main and current branch and unshallow clone~

**Comment by iFurySt** [comment]
@rbren @li-boxuan  what do you think of this method to transition?

**Review by rbren — APPROVED** [review]
LGTM!

**Comment by iFurySt** [comment]
> LGTM!

it causes the lint workflow to fail right now 🤔

**Comment by rbren** [comment]
Ugh you're right. Not sure how we did this in the past. Maybe we do just need to delint everything in this PR and deal with the merge headaches

**Comment by li-boxuan** [comment]
In the past we don’t have (enough) linting checks in CI.

How about dropping the CI enforcement for a while?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iFurySt** [comment]
I've push a patch for transition. It only checks the modified files from the commits.

**Pull request merged**
