### PR TITLE
feat: implement basic planner UI

### PR DESCRIPTION
**Pull request by Sparkier**
fix https://github.com/OpenDevin/OpenDevin/issues/139

This is still very alpha. Especially the UI is not close to finished. However, some feedback around the general implementation could be useful.

This needs to be run with an agent that actually sends `add_task` and `modify_task` events, such as the `PlannerAgent`.

### CODE REVIEW

**Comment by Sparkier** [comment]
@rbren would be awesome if you could take a look and check if this implementation generally makes sense.

**Comment by Umpire2018** [comment]
FYI.

```python
{"action": "initialize", "args": {"agent_cls": "PlannerAgent"}}
Message from server: {"action":"initialize","message":"Control loop started."}
```

```
{"action": "start", "args": {"task": "write a hello world in python"}}

Message from server: {"message":"Starting new task..."}
Message from server: {"action":"run","args":{"command":"python -c \"print('Hello, World!')\"","background":false},"message":"Running command: python -c \"print('Hello, World!')\""}
Message from server: {"observation":"run","content":"-bash: !': event not found","extras":{"command_id":-1,"command":"python -c \"print('Hello, World!')\"","exit_code":0},"message":"Command `python -c \"print('Hello, World!')\"` executed with exit code 0."}
Message from server: {"action":"run","args":{"command":"python3 -c \"print('Hello, World!')\"","background":false},"message":"Running command: python3 -c \"print('Hello, World!')\""}
Message from server: {"observation":"run","content":"-bash: !': event not found","extras":{"command_id":-1,"command":"python3 -c \"print('Hello, World!')\"","exit_code":0},"message":"Command `python3 -c \"print('Hello, World!')\"` executed with exit code 0."}
Message from server: {"action":"finish","args":{},"message":"All done! What's next on the agenda?"}
```

**Comment by rbren** [comment]
Excited to try this! Will take a look today

**Comment by rbren** [comment]
@Umpire2018 it's possible you're running into https://github.com/OpenDevin/OpenDevin/issues/1167

**Comment by rbren** [comment]
Structurally this LGTM!

My guess is we'll want to use emoji or images to indicate task state. Something like:

🔲 open task
✅ completed task
🤔 in progress
🔲 ~abandoned~

**Comment by Sparkier** [comment]
> Structurally this LGTM!
> 
> My guess is we'll want to use emoji or images to indicate task state. Something like:
> 
> 🔲 open task ✅ completed task 🤔 in progress 🔲 ~abandoned~

Yep, generally wanted to check if this makes sense before doing that. Now added icons.

**Comment by rbren** [comment]
Looking good! A couple small issues left:
* Overflow is hidden, instead of scrolling
* I think maybe remove the borders, and add indent? it gets kind of busy with lots of nesting
* I like the flat icons, but maybe add some light colors for state (see Paul's designs)

I think there are some issues w/ Paul's designs vs the data structure--going to go back to him for feedback
Screenshot 2024-04-18 at 7 06 36 AM

**Comment by rbren** [comment]
Would also be great if the planner took focus every time there's a plan event!

**Comment by Sparkier** [comment]
> Would also be great if the planner took focus every time there's a plan event!

Do we actually want that? I think then similar things should happen for the code and browser panes but kinda wondering if that actually makes sense. Then you'd be almost constantly redirected, right?

**Comment by rbren** [comment]
> Do we actually want that? I think then similar things should happen for the code and browser panes but kinda wondering if that actually makes sense. Then you'd be almost constantly redirected, right?

I think I'd need to see it in action to see how it feels. It takes ~3-5s between actions for me, so I do think it'd be reasonable. What's weird to me right now is that the agent is actively making a plan, and I can only see that by looking at the logs. From the user's perspective, things just look frozen, unless you click over to the planner tab

**Comment by rbren** [comment]
This is looking rad!

**Comment by rbren** [comment]
Screenshot 2024-04-19 at 1 08 25 PM

**Review by rbren — APPROVED** [review]

**Pull request merged**
