### PR TITLE
Evaluation time travel: allow evaluation on a specific version 

### PR DESCRIPTION
**Pull request by li-boxuan**
As discussed [here](https://opendevin.slack.com/archives/C06QS1MB85P/p1717592311228629), ongoing dev work could impact evaluation, and we sometimes have to pause PRs when running evaluation (which could take days). This is because we don't have a neat way to evaluate OpenDevin at a given version.

This PR adds a utility script that checks out OpenDevin repo to a given version but keeps the evaluation folder untouched. For example, say we want to reproduce the results for git commit a4af937 shown on https://huggingface.co/spaces/OpenDevin/evaluation. We just need to run this:

```bash
./evaluation/swe_bench/scripts/run_infer.sh eval-3 a4af937 CodeActAgent
```

We could also use released tags, e.g.

```bash
./evaluation/swe_bench/scripts/run_infer.sh eval-3 0.6.2 CodeActAgent
```

Limitation: we cannot travel back to an arbitrary history. For example, we cannot travel back to CodeAct agent v1.3 because the current SWE-bench lite evaluation harness assumes existence of `AgentSkillsRequirement` class, which didn't exist back on v1.3.

TODO:

- [x] Apply the same change to other evaluation

### CODE REVIEW

**Comment by yufansong** [comment]
Should we also add time travel to other benchmarks, or only change then when need?

**Comment by li-boxuan** [comment]
> Should we also add time travel to other benchmarks

Yeah I am planning to, otherwise I am afraid no one would do it ever 😆  or should we leave this as low-hanging fruit for new comers?

**Comment by xingyaoww** [comment]
> Should we also add time travel to other benchmarks

I am actually thinking if it is easy for us to add a centralized eval management entry point for all benchmark, and make it really easy for new comers to add eval tasks?

**Comment by li-boxuan** [comment]
> make it really easy for new comers to add eval tasks

Yep I think we need a few iterations of refactoring to get there. I am trying to pull out some common utilities out as a first step.

**Review by neubig — APPROVED** [review]
This looks awesome, thanks for doing this!

**Pull request merged**
