### PR TITLE
fix: test_sandbox tests didn't close dockers

### PR DESCRIPTION
**Pull request by tobitege**
At least on WSL with Docker for Windows, the run of test_sandbox created like 15+ docker instances but not closing a single one.

Added try/finally with box.close() for all test loops.

Request for feedback if this is an issue on other systems.

@li-boxuan @neubig

### CODE REVIEW

**Comment by li-boxuan** [comment]
All sandboxes register close method to `atexit`, so they should close after running...

I tested on my laptop (macos, M1) and there's no stale container left:

```python
poetry run pytest -s tests/unit/test_sandbox.py
```

Did all the tests pass when you run them? I wonder if someone also using WSL could confirm.

**Comment by tobitege** [comment]
> Did all the tests pass when you run them? I wonder if someone also using WSL could confirm.

I just re-ran the command you quoted with the changes of this PR and all tests succeed without errors.

**Comment by li-boxuan** [comment]
> I just re-ran the command you quoted with the changes of this PR

Oh what I am trying to ask is, do you see stale containers after successfully completing all unit tests?

**Comment by tobitege** [comment]
> > I just re-ran the command you quoted with the changes of this PR
> 
> Oh what I am trying to ask is, do you see stale containers after successfully completing all unit tests?

Oh, got you.
So docker *does* closed the containers, but only once the *full* test script finished.
At that point there were like 13+ containers active.
With my PR, each test will have its container closed right away - which I'd prefer, tbh.

**Comment by li-boxuan** [comment]
How about we don't use `try - finally`, and simply close containers at the end of each test? The tests are supposed to pass anyways...

**Comment by tobitege** [comment]
> How about we don't use `try - finally`, and simply close containers at the end of each test? The tests are supposed to pass anyways...

Sure, will do that.

**Comment by tobitege** [comment]
Ready for review.

**Review by li-boxuan — APPROVED** [review]
Thank you!

**Pull request merged**
