### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by dorbanianas**
After adding the readme now we should update the getting started section so there's no need for the whole config that we used to do before, also I made an update to the whole structure to align with our current state

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
I was successfully able to run `make build` and `make setup-config` but when I ran `make run` I got the following error, is this a known bug or should I create an issue?

Screenshot 2024-04-01 at 8 21 12 PM

Also, this PR has conflicts with main in README.md, could you resolve those?

**Comment by dorbanianas** [comment]
@neubig is there any errors shown in the log file or the terminal for the backend?

**Comment by neubig** [comment]
Ah, yes, lots of thes:
```
8:19:29 PM [vite] ws proxy error:
AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1680:7)
8:19:29 PM [vite] http proxy error: /litellm-models
AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1680:7)
8:19:29 PM [vite] http proxy error: /litellm-agents
AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1680:7)
8:19:29 PM [vite] http proxy error: /litellm-models
AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1680:7)
    ```

**Comment by neubig** [comment]
It's probably an instance of this: https://github.com/OpenDevin/OpenDevin/issues/508

**Review by neubig — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
