### PR TITLE
Fix CI workflows [mac-test]

### LINKED ISSUE #2011: [Bug]: Unit and Integration test check prevent PR from merging when changes are on ignored list
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

PRs like this https://github.com/OpenDevin/OpenDevin/pull/1995 won't merge properly because all the edited files are in the ignored list, so the checks will NOT run integration/unit tests, BUT they are still waiting for "All test passed" (and it never passed which blocks the PR from merging).

https://github.com/OpenDevin/OpenDevin/blob/main/.github/workflows/run-integration-tests.yml

image

### Current Version

```bash
N/A
```

### Installation and Configuration

```bash
N/A
```

### Model and Agent

_No response_

### Reproduction Steps

_No response_

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by li-boxuan**
1. GitHub isn't happy about our efforts to save their CPU cycles... This PR fixes the problem by wasting their resources. Fixes #2011
2. Also remove `test_matrix_success` checks as they are not blocking bogus PRs from being merged anyways... See https://github.com/OpenDevin/OpenDevin/issues/2011#issuecomment-2128440865
3. Mac tests have been very unstable due to environment issues. This PR disables integration test on Mac, unless the PR title contains the keyword "mac".

Now that we have fewer CI checks, maybe @rbren you could set up those individual unit tests & integration tests as required now? Or maybe only `Run Integration Tests / Integration Tests on Linux (3.11, ssh)` and `Run Unit Tests / Test on Linux (3.11) (pull_request) `.

### CODE REVIEW

**Comment by li-boxuan** [comment]
image

MacOS integration check skipped.

**Review by enyst — APPROVED** [review]
Frankly not everything in the behavior of Github here is clear to me, but I'll approve this hoping it unblocks your attempt to fix things. I trust your judgment whether to merge as you see fit.

**Comment by enyst** [comment]
Ah, won't work without an admin disabling those two.

**Review by neubig — APPROVED** [review]
Looks good! And I set the required tests to be the following:

Screenshot 2024-05-24 at 5 20 57 AM

**Pull request merged**
