### PR TITLE
Automate regression test checking

### PR DESCRIPTION
**Pull request by dorbanianas**
- This is related to #269 issue

### CODE REVIEW

**Comment by dorbanianas** [comment]
if you execute run.py this would be the result so now we need to have more structured way to handle tests
image

**Comment by rbren** [comment]
This looks awesome!

Do the bash and python do the same thing? I'd rather only maintain one if so, and python seems much better for the task.

I do think we'll need to be able to output the results to YAML/JSON for any post processing (e.g. failing CI/CD)

**Comment by dorbanianas** [comment]
the result that you see was built using python, the bash script was just the first version I will try to remove it after trying to make an architecture for the regression framework

**Comment by rbren** [comment]
Closing this one in favor of the more recent one @dorbanianas put together

**Pull request closed without merging**
