### PR TITLE
docs: fixed typo in launch command

### PR DESCRIPTION
**Pull request by JensRoland**
The argument `--add-host host.docker.internal:host-gateway` should be `--add-host host.docker.internal=host-gateway` (with an `=` character).

Solves `Error creating controller: Could not establish connection to host` errors.

### CODE REVIEW

**Comment by yimothysu** [comment]
Thanks for the fix! This looks right according to https://docs.docker.com/reference/cli/docker/container/run/#add-host

**Review by yimothysu — APPROVED** [review]

**Comment by enyst** [comment]
I'm not sure this was a typo, it was coming from: https://github.com/OpenDevin/OpenDevin/pull/1604
The linked issue shows problems with =.

The doc linked also says: 
> The --add-host flag also accepts a : separator, for example:
> $ docker run --add-host=my-hostname:8.8.8.8 --rm -it alpine

@JensRoland @yimothysu wdyt?

**Comment by yimothysu** [comment]
> I'm not sure this was a typo, it was coming from: https://github.com/OpenDevin/OpenDevin/pull/1604
> 
> The linked issue shows problems with =.
> 
> 
> 
> The doc linked also says: 
> 
> > The --add-host flag also accepts a : separator, for example:
> 
> > $ docker run --add-host=my-hostname:8.8.8.8 --rm -it alpine
> 
> 
> 
> @JensRoland is : causing problems?
> 
> @yimothysu wdyt?

Gotcha, I wasn't aware before. @JensRoland do you only get "Error creating controller: Could not establish connection to host" with :? If not, we can revert.

**Comment by JensRoland** [comment]
@yimothysu correct, I got the error when using `:` but not using `=` (on MacOS Sonoma on an M1 Mac running Colima)

**Comment by rbren** [comment]
@JensRoland we just reverted your change unfortunately. What happens if you do `--add-host=x:y` (with the equals sign)?

The syntax changed at some point, but `:` _should_ be forward and backward compatible. E.g. see this article from 2017 with the `:` syntax

https://www.cloudbees.com/blog/using-the-add-host-flag-for-dns-mapping-within-docker-containers

**Comment by rbren** [comment]
FWIW I'm on Mac OS with docker 26.0.0, and `--add-host host.docker.internal:host-gateway` works fine for me

**Comment by rbren** [comment]
Maybe it's a Colima issue?

**Comment by JensRoland** [comment]
I can verify that it works with the =: syntax with Colima on MacOS. Thanks for the help.

**Pull request merged**
