### PR TITLE
Add Windows instructions to README.md

### PR DESCRIPTION
**Pull request by AbdelrahmanHassan111**
trying to add  commands that is Compatible with Windows Terminal

### CODE REVIEW

**Comment by PierrunoYT** [comment]
I thought you need WSL

**Comment by enyst** [comment]
IMHO if we attempt to document the use of Windows without WSL, it comes across as "official support" and that seems like a lot of potential headaches, at least for now.

**Comment by AbdelrahmanHassan111** [comment]
> IMHO if we attempt to document the use of Windows without WSL, it comes across as "official support" and that seems like a lot of potential headaches, at least for now.

I agree with you and in my journey to run Opendevin on Windows I face many errors but I'm working on it and when I finish it I'll share every thing needed to run opendvein on windows

**Comment by subos2008** [comment]
Wouldn’t docker compose solve this?

**Comment by rbren** [comment]
Yeah I'm inclined to agree with @enyst. But given how many people are trying it out on windows, it might make sense to have a separate `Windows.md` file, where we make it _very_ clear that it's not officially supported, but at least share everything we've learned

**Pull request closed without merging**
