### PR TITLE
Add config.toml.template to streamline configuration setup (fixes #2361)

### LINKED ISSUE #2361: [Feature]: Create a default `config.template.toml` to help people quickly on-board
**Describe the UX of the solution you'd like**

Create a default template of `config.toml` with all the common config configurations with explanations to help people onboard quickly. They just need to rename `config.template.toml` to `config.toml` and customize it to their needs.

It should ideally contain examples of:
- different sandbox configurations
- sandbox env var settings
- local LLM / examples of using different LLM providers

EDIT: suggest by @SmartManoj , we should use `config.toml.template` instead

### PR DESCRIPTION
**Pull request by PierrunoYT**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

This pull request introduces a `config.toml.template` file to the root of the workspace. It provides a structured and commented configuration template that users can easily customize to set up their environment. This PR fixes issue [#2361](https://github.com/OpenDevin/OpenDevin/issues/2361).

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

The `config.toml.template` file includes various configuration settings for core, sandbox, LLM providers, agent, and environment variables. All settings are initially commented out, allowing users to uncomment and configure the necessary sections according to their needs. The `[core]` section is placed at the top for better visibility, and the `enable_auto_lint` option has been removed as it is not intended for normal users. This template helps streamline the setup process for new users and ensures consistency in configuration across different environments.

**Other references**

N/A

### CODE REVIEW

**Comment by tobitege** [comment]
I'm wondering if this would be even better as an extended help page, where each entry has its actual description (purpose, maybe even value ranges, default/optional).
That would go a long way to help new and existing users as a "go to" page to look stuff up.

The bare, minimum config file the user is supposed to generate via `make setup-config` anyways.

Maybe there are others, who'd like to chime in here and collaborate in this effort.

**Comment by Shimada666** [comment]
This looks a bit confusing to me. I feel that beginners might miss the main points.

I agree with @tobitege opinion to use `make setup-config` for minimal configuration. For more custom options, maybe we should put them in the documentation.

**Comment by PierrunoYT** [comment]
Okay so should we close this?

**Comment by tobitege** [comment]
> Okay so should we close this?

No, not necessarily, depending on if you'd like to take up the idea of e.g. adding a new documentation file (just add to `docs/modules/usage` a markdown file with ".md" extention).
You could use the content of your template file as a start and add to it, also you can edit your PR's title to reflect the new purpose.

Right now I'm not sure a template file alone in this length helps avoiding problems/questions.

**Comment by mamoodi** [comment]
@PierrunoYT will you be taking up the task suggested by tobi or should we close this PR?

**Comment by PierrunoYT** [comment]
@mamoodi No sorry but I'm trying to contribute on other ways.

**Pull request closed without merging**
