### PR TITLE
feat: added 'fetch_github_branches' to agentskills incl. unit tests

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Introduce for CodeAct agent the skill to fetch a list of available branches for a given repository.

**Give a brief summary of what the PR does, explaining any non-trivial design decisions**

It should be an easy task, but in my tests it swallows a lot of tokens with several page-reloads
if the agent is supposed to open the repo page and extract the available ones via HTML parsing etc.
(delegated to browsing agent).

This new skill should speed up things and reduce cost in the process as it uses an existing
Github API wrapper for Python.
Multiple unit tests included and added an appropriate hint in the prompt for the LLM.

@xingyaoww I didn't want to touch the integration test prompt without first asking for your feedback and maybe guidance on how to add best add this skill there (if this PR was actually positively reviewed).

### CODE REVIEW

**Comment by iFurySt** [comment]
Could you please convert this PR to a draft if it's not ready for review? 😄

**Comment by li-boxuan** [comment]
Debate: should GitHub related stuff be put into `agentskills`, or a separate agent?

Thumb up this message if you think they should be moved to a separate agent (similar to BrowsingAgent, where other agents could then delegate to).

**Comment by li-boxuan** [comment]
Debate: should GitHub related stuff be put into `agentskills`, or a separate agent?

Thumb up this message if you think they should be sitting in `agentskills` so that they would appear as part of CodeActAgent (and any other agent that uses agentskills) prompts.

**Comment by neubig** [comment]
I think this is a bigger discussion of three options:
1. Sub-agents
2. Tools
3. Documentation lookup ([DocPrompting](https://arxiv.org/abs/2207.05987)/RAG)

I think all of these are reasonable options here, and each have their tradeoffs. Overall I'm pretty bullish on the third option, which would use a single agent and not create separate tools, but instead look up documentation about how to do things with code. This is more like how human programmers work, and seems to be a pretty nice and scalable option. (if you want, you could thumbs-up this method for "3")

**Comment by xingyaoww** [comment]
Yeah, I think "Documentation lookup ([DocPrompting](https://arxiv.org/abs/2207.05987)/RAG)" pretty much aligns with what I'm thinking about for the next step of `agentskills` -- given task instruction, we can retrieve relevant tools for the agent; on the other hand, the agent can also browse the `agentskills` library for more details.

Right now, I'm a bit worried about bloating the `agentskills` library too much -- But i think it is acceptable now. We should really start working on the tool retrieval functionality of `agentskills` library described in https://github.com/OpenDevin/OpenDevin/pull/1941

**Comment by tobitege** [comment]
> Right now, I'm a bit worried about bloating the `agentskills` library too much -- But i think it is acceptable now. Maybe after this PR, we should really start working on the tool retrieval functionality of `agentskills` library described in #1941 so that the system prompt can be a little bit more concise for the agent.

Thanks to all for the discussion!

Just speaking to the agentskills and the generated system prompt, which was around 11 KB last time I checked (don't have the tokenized number).
Instead of pulling in the whole agentskills'  docprompt collection, could we instead provide a strong hint like
"`For preferred file operations please ask for <insert keyword>.`"
so the LLM could ask OpenDevin for more details when needed, and then we send the full skills docs.
Obviously, there'd be mixed results if the LLM would even _care to ask_ and/or ignore this, but just as an tangent idea.

As to this PR itself: the aim was to reduce roundtrips and token usage. Using the browser instead of the existing API is rather expensive, e.g. OpenDevin's repo page alone is over 400KB. And that might be multiplied by any number of times till the HTML parsing and clicking around by the LLM actually manages extract the right information.

For the architectural location of it: since Github is a major topic for the project, could a specialized GithubAgent be an option?

**Comment by li-boxuan** [comment]
> As to this PR itself: the aim was to reduce roundtrips and token usage. Using the browser instead of the existing API is rather expensive, e.g. OpenDevin's repo page alone is over 400KB. And that might be multiplied by any number of times till the HTML parsing and clicking around by the LLM actually manages extract the right information.

I think that's a very interesting topic. Browsing is actually very human-alike - the agent itself doesn't know it's very costly to browse. It doesn't have a "cost model" as any mature database optimizer does! As a database query optimizer developer myself, I always like to think everything from costing perspective. Btw, https://arxiv.org/pdf/2405.14696 is an interesting read if someone is interested in connecting the dots.

**Comment by tobitege** [comment]
> Could you please convert this PR to a draft if it's not ready for review? 😄

Just to clarify: the reason was the missing integration tests or did you have other concerns in mind?

**Comment by tobitege** [comment]
Will work on the integration test(s) in the coming days.

**Comment by enyst** [comment]
The agent/sub-agent option could also take the form of multiple or composite micro-agents, something like [this](https://github.com/OpenDevin/OpenDevin/pull/1660).

As for the agent skills option, if main agentskills is a location others are okay with, for now, it's good for me too.

It's so interesting though, the agent skills option raises again the question of optional agent skills. That, IMHO, would be the best place, except we don't have it yet. 😅 I believe we need something like optional agent skills / optional actions that the agent retrieves from an action library of sorts _when it needs it_. I can't wait to finish with my in-progress work on short term memory so I can focus on that. (to my mind, it's all about memory lol, action library is long term memory/RAG)
So, FWIW, I added a thumbs up on @neubig 's post.

**Review by neubig — COMMENTED** [review]
Please re-request review when this is ready to merge! Just leaving a comment to pop it off my review stack.

**Comment by tobitege** [comment]
Just for reference, a test to confirm the LLM "knows" the method and is capable of using it (no token defined here):
grafik
grafik

**Comment by tobitege** [comment]
After further thinking about this, I'll drop this PR and not introduce more code to maintain and test.

It'd be easy to tell the LLM in chat to use **_pyGithub_** package instead of browsing a Github page.

**Pull request closed without merging**
