### PR TITLE
Unrevert: fix(backend) changes to improve Command-R+ behavior, plus file i/o error improvements.

### PR DESCRIPTION
**Pull request by rbren**
Reverts OpenDevin/OpenDevin#1405

### CODE REVIEW

**Comment by rbren** [comment]
CC @computer-whisperer and @li-boxuan

**Comment by computer-whisperer** [comment]
It was passing the integration tests when I last committed, looks like your merge is what broke it.

**Comment by computer-whisperer** [comment]
I also don't think I can commit to this branch, so you will have to make the fixes unless I re-create the original PR from my branch.

**Comment by computer-whisperer** [comment]
I have resolved the issue in a new pr from my branch, which is now ready for review https://github.com/OpenDevin/OpenDevin/pull/1417

**Comment by enyst** [comment]
Fixed by the linked PR.

**Comment by rbren** [comment]
Thanks @computer-whisperer! Sorry for the mixup

**Pull request closed without merging**
