### PR TITLE
Some cleanups of python code

### PR DESCRIPTION
**Pull request by marksmayo**
Cleaned white space
Tidied imports
black formatting

### CODE REVIEW

**Comment by rbren** [comment]
Cleanup LGTM! You might want to recreate due to merge conflicts though 😄 

Also--we should revert everything under `regression/`--that's generated by the LLM

**Comment by huybery** [comment]
@marksmayo This branch has conflicts that must be resolved.

**Comment by rbren** [comment]
We might want to implement this as a pre-commit, so we only change a few files at a time, and don't cause merge headaches for everyone

**Comment by huybery** [comment]
As @rbren said, we had better adopt the pre-commit approach. Close this issue and re-open it if needed or discuss it in slack.

**Pull request closed without merging**
