### PR TITLE
fix(controller): "agent task already running"

### PR DESCRIPTION
**Pull request by xingyaoww**
- Fixes https://github.com/OpenDevin/OpenDevin/issues/1492.
- <s>Also fixes: https://github.com/OpenDevin/OpenDevin/issues/1492#issuecomment-2090316167 </s> Will fix in a separate PR

image

### CODE REVIEW

**Review by amanape — COMMENTED** [review]
Pausing or restarting the agent does not work. (responds with a "Current task state not recognized." message)

**Comment by xingyaoww** [comment]
@amanape should be fixed in the new commit!

**Comment by amanape** [comment]
image

Model: `gpt-3.5-turbo`
Agent: `CodeActAgent`

I can't seem to replicate this behavior every time. But the buttons don't seem react either now. I can't seem to pause, or restart. UI does not change. Anybody else can confirm?

**Comment by xingyaoww** [comment]
@amanape, this seems to be a much more complex issue that involves the front end. How about i revert the attempted fix for "Current task state not recognized", and starts a separate PR for this? I can reproduce some of the behavior (e.g., reset button doesn't work, pause state propagate to the backend but UI does not change, etc), but I guess this will take more time to figure out.

**Comment by rbren** [comment]
🤔 this seems like a legit error to me--in what case do we get a `START` without getting a cancel first?

**Comment by amanape** [comment]
@rbren There seem to be more issues with the agent actions than appear on the surface. I'm not sure if it was due to recent merges or they were dormant for a while. 

For example, I managed to achieve a `ValueError: Task (state: TaskState.PAUSED) is not in a state to add user message` error than resulted in an unpaused state in the FE and paused state in the BE. This also somehow ended up rendering the `<LoadPreviousSessionModal>` every message after.

I'll take a peek into the FE later today and see if I can find anything. Worth setting up tests for these too

**Comment by xingyaoww** [comment]
@rbren This PR basically reverts changes I made at https://github.com/OpenDevin/OpenDevin/pull/1290. The reason I add that assert statement is we had a `start_task_or_chat` function - later your proposed PR break this down to `start_task` and some `add_user_message` function, but we forget to change the assert back :(

**Pull request merged**
