### PR TITLE
Fix pylint warning `unspecified-encoding`

### PR DESCRIPTION
**Pull request by RatishT**
Changes Made:

- Applied automated fixes for the pylint warning unspecified-encoding.
"It is better to specify an encoding when opening documents. Using the system default implicitly can create problems on other operating systems. See [https://peps.python.org/pep-0597/](https://peps.python.org/pep-0597/)"

Note:

This pull request is part of a research project conducted by researchers from TU Delft, titled "PyWarnFixer: Using ML to Fix Pylint Warnings." The goal of this study is to investigate the perceptions and practices of code quality among developers in Python open-source projects and to develop a tool that uses AI to automatically fix pylint warnings.

### Research Study Information:
This pull request is part of a research project. For more information about the study, please visit the [project's information page](https://github.com/RatishT/PyWarnFixer/blob/main/README.md).

### Consent to Participate:
If you review this pull request, you are invited to participate in our study. Your participation is voluntary. To provide your consent, just open an issue in our repository with the provided template using the following link: [consent issue template](https://github.com/RatishT/PyWarnFixer/issues/new/choose) .

---

Thank you for considering participation in our research. Your feedback is crucial and highly valued. If you have any questions or concerns, please contact the Responsible Researcher at R.K.Thakoersingh@student.tudelft.nl.

### CODE REVIEW

**Comment by tobitege** [comment]
...or one of a couple of alternatives, use wrappers:
```py
def safe_open_read(file_path, encoding='utf-8'):
    return open(file_path, 'r', encoding=encoding)

def safe_open_write(file_path, encoding='utf-8'):
    return open(file_path, 'w', encoding=encoding)

with safe_open_read('file.txt') as f:
    content = f.read()

with safe_open_write('output.txt') as f:
    f.write(content)
```

**Review by neubig — CHANGES_REQUESTED** [review]
Hey @RatishT, tests are failing. Could you please fix them?

**Comment by tobitege** [comment]
> Hey @RatishT, tests are failing. Could you please fix them?

It seems that the encoding change would need the agentskills' file "open" commands to work for both modes.
Something along these lines (example):
```py
mode = 'w' if isinstance(contents, str) else 'wb'
        with open(full_path, mode) as f:
```

**Review by tobitege — CHANGES_REQUESTED** [review]
@RatishT you applied changes to most if not all evaluation suits as well.
Every of those encoding changes must be confirmed to work with both w and wb mode, otherwise we cannot merge these "as is".

cc @neubig

**Comment by neubig** [comment]
Yeah, @RatishT , while I appreciate your work on trying to improve software engineering, it may be necessary to have some informed human supervision before we can merge this in. In particular, our project already is using linting as specified in CI, and we confirm that linting passes according to our linting standards, so it's not very obvious that this is necessary. I'll close it for now.

**Pull request closed without merging**
